### ISSUE TITLE
[Bug Fix]: NDI using OBS-NDI 4.13.0 on MacOS Sonoma

### ISSUE THREAD

**Issue by JeneralPain** [obs-ndi/obs-ndi#1001]
### Operating System Version

Sonoma 14.4.1 (23E224) - Mac M1 Max

### CPU

Apple M1 Max

### GPU

Apple M1 Max

### OBS Version

30.1.2

### OBS Installation Method

pkg for Mac

### OBS-NDI Version

NDI 6

### OBS-NDI Installation Method

pkg and NDI tools

### [Extra] Installation Steps

After spending the better part of a day trying to figure out why trying to solve the "NDI5RunTime" cant be found, I finally figured it all out.

There are a couple of steps to solve the problem but it's pretty much identical.

1. Install OBS as per normal
2. Install OBS-NDI as per normal
3. Install NDI5Runtime (or NDI6 Core Suite - dealers choice)

Once all of this is done, you need to do these couple of steps.
`1. sudo cp /Applications/NDI\ Video\ Monitor.app/Contents/Frameworks/libndi_advanced.dylib /usr/local/lib`
`2. sudo cp /usr/local/lib/libndi_advanced.dylib /usr/local/lib/libndi.dylib`
`3. Open finder and show hidden files CMD+SHIFT+.`
`4. Go into MacHDD > usr > local`
`5. Find "lib" and Right Click+"Get Info"`
`6. Pop out the "Permissions and Sharing"`
`7. Click the padlock and "unlock" the settings page (finger print, watch, password etc)`
`8. Add either your group of accounts or your own account`
`9. Change it to "Read+Write"`

After that, OBS NDI is working just fine.

It just seems SONOMA locks down the /usr/local/lib folder, but because by default the user accounts do not have permissions, OBS can't see it. I didn't have to reboot, I didn't have to do anything, it just started working. 

### NDI Version

NDI SDK Apple 15:45:25 Apr 5 2024 6.0.0

### Describe the bug

When opening the OBS app with NDI installed on Sonoma/M1 Silicon, you get the pop up that complains Runtime is missing but you know you've installed it.

You can see you'll have the problem during the install of NDIRuntime because the "lib" folder will have a little red (-) over it.

### Additional context

Sonoma/Silicon locks down the /usr/local/lib folder.

**Comment by Trouffman** [comment]
Thanks for posting.

This is a known issue and soon the be resolved.

This comes from an issue on the lib_for_MAC.pkg provided by NDI.
They are already aware and the fix is ready, waiting for release.

Note to fix this :
Open terminal and type :
sudo chmod 755 /use/local/lib

**Comment by calebvaq24** [comment]
that solution no longer works

**Comment by Trouffman** [comment]
FYI libndi_advanced.dylib is not used by this plugin.

Please stick to the plugin's official suggestion for installing the Runtime.

**Comment by Trouffman** [comment]
NDI released LibNDI runtime 6.0.12 that fixes most of theses issues.
