### ISSUE TITLE
OBS-NDI Devices Do Not Show Up In PowerPoint 365

### ISSUE THREAD

**Issue by tictag** [obs-ndi/obs-ndi#1005]
### Operating System Version

Windows 10 23H2

### CPU

12th Gen Intel(R) Core(TM) i9-12900HK

### GPU

Intel Iris(R) Xe Graphics & NVIDIA GeForce RTX 3050 Ti

### NDI Devices

Those created by OBS-NDI ('Main output & 'Preview Output')

### OBS Version

v30.1.2

### OBS Installation Method

Via Windows x64 installer (OBS-Studio-30.1.2-Full-Installer-x64.exe)

### OBS-NDI Version

v4.13.1

### OBS-NDI Installation Method

Via Windows x64 installer (obs-ndi-4.13.1-windows-x64-Installer.exe)

### [Extra] Installation Steps

NIL

### OBS Log [URL]

https://obsproject.com/logs/ZX9mvjjHXwNEOfr2

### NDI Version

NDI SDK WIN64 03:20:51 Feb 17 2024 5.6.1.0

### Describe the bug

Neither the 'Main Output', 'Preview Output' NDI devices, nor the 'Dedicated NDI Output' Video Filter show up  / are displayed / are available in PowerPoint 365 (_x64 Version 2402 Build 16.0.17328.20282_)   [_see screenshot 2024-04-21_19-20-55.png_]

**Note 1:** They ARE listed and function normally in NDI Tools v6 > Studio Monitor  [_see screenshot 2024-04-21_19-27-40.png_]
**Note 2:** With NDI Tools v6 installed, **NDI Webcam Video 1 - 4** ARE listed in PowerPoint  [_see screenshot 2024-04-21_19-32-32.png_] and these function normally.

### Steps to reproduce the problem

1. Open PowerPoint
2. Create a blank PowerPoint document
3. Add Cameo feature Menu > Record > Cameo > This Slide
4. TEST: Click Preview ... ERROR! No NDI devices are listed/available
5. TEST: Click Record > From Beginning > Presenter View > Ellipses Menu > Camera ... ERROR! No NDI devices are listed/available

### Expected behavior

When previewing Cameo or Recording, OBS-NDI devices should be listed as available video devices.

### Screenshots

![2024-04-21_19-20-55](https://github.com/obs-ndi/obs-ndi/assets/12136834/c7ec9dbb-53e6-4f96-a169-f1122ab0f32d)
![2024-04-21_19-27-40](https://github.com/obs-ndi/obs-ndi/assets/12136834/f4358a07-651a-45ba-a301-19ddff0297f6)
![2024-04-21_19-32-32](https://github.com/obs-ndi/obs-ndi/assets/12136834/9e5be312-2bdd-45f5-a65d-3f417c36226b)

### Additional context

I have installed OBS-NDI in a Windows 10 23H2 new-build (i.e. vanilla) virtual machine and get the same issue.

**Comment by RayneYoruka** [comment]
This sounds  like a firewall issue, please disable, try again and report back.

**Comment by tictag** [comment]
@RayneYoruka Thank you for the advice.

I tried simply disabling the firewall, no change, then also uninstalling/re-installing OBS-NDI with the firewall disabled, no change.

I also tried installing OBS-NDI on a vanilla build of Windows 11 23H2 virtual machine and get the same issue, so that's three separate computers, all with the same issue, the only common denominator being the version of PowerPoint 365, which was downloaded directly from https://office.com. Is it possible that this latest version of PowerPoint 365 doesn't support OBS-NDI?

**Comment by Rotund** [comment]
The other common denominator is that they're all virtual machines. No idea if that is the problem, but it's also common. The NDI mDNS packet (discovery packet) is a multicast UDP packet. However you're sharing your network card to your virtual machines may be blocking them or they're on different networks. Can you try connecting directly to the IP address OBS is using? Might it be on a network doesn't get routed to the virtual machines?

**Comment by RayneYoruka** [comment]
> I tried simply disabling the firewall, no change, then also uninstalling/re-installing OBS-NDI with the firewall disabled, no change.
> 
> I also tried installing OBS-NDI on a vanilla build of Windows 11 23H2 virtual machine and get the same issue, so that's three separate computers, all with the same issue, the only common denominator being the version of PowerPoint 365, which was downloaded directly from https://office.com. Is it possible that this latest version of PowerPoint 365 doesn't support OBS-NDI?

Normally NDI has different versions of the protocol and it detects that it's using an older version it's supposed to adjust to it.

> The other common denominator is that they're all virtual machines. No idea if that is the problem, but it's also common. The NDI mDNS packet (discovery packet) is a multicast UDP packet. However you're sharing your network card to your virtual machines may be blocking them or they're on different networks. Can you try connecting directly to the IP address OBS is using? Might it be on a network doesn't get routed to the virtual machines?

This is a really good point @Rotund !, normally depending of how it's being virtualized some times the hypervisor might have firewall rules for every virtual adapter, I use proxmox and I do know they exist but I haven't encountered any issue with them nor in the pas when I used to run virtualbox with dedicated network adapters

**Comment by tictag** [comment]
> The other common denominator is that they're all virtual machines.
@Rotund and @RayneYoruka Thank you for the advice.

Interesting. I didn't realise that NDI introduced itself to a system as a network broadcast, I thought it would be some kind of device driver or some other software device. Yes, in this case, the virtual machines add an unnecessary layer of technical complexity, let's ignore them, back to my main system (note: not a virtual machine).

Considering that (1) NDI Tools v6 > Studio Monitor detects the OBS-NDI streams and (2) Both PowerPoint and Studio Monitor exist in the same execution environment (_i.e. Windows 10 23H2, being served by the same network stack_), why would one application detect these mDNS discovery packets and not the other?

Also, why would PowerPoint detect mDNS broadcast packets from NDI Tools v6 and not OBS-NDI? Are they implemented in different ways? Maybe there's been an update to the NDI SDK that OBS-NDI hasn't 'caught up with' yet?

I know that my firewall operates at both the network stack and application layers, I'm going to try uninstalling it completely, rather than just disabling it, and will report back.

**Comment by tictag** [comment]
Finally got around to uninstalling my firewall completely and the short version is: no change.

So I am left with: 

- PowerPoint 365 **does not** identify/display OBS NDI streams, but **does** display NDI Tools streams like webcam and test screen.
- OBS NDI Studio Monitor **does** identify/display OBS NDI streams.

Firewall is not involved.

**Comment by RayneYoruka** [comment]
Seeing the post again I bet powerpoint only accepts webcam devices, NDI webcam installs a system driver to act as a webcam reciever to be able to be used with any webcam/network NDI stream.

I thought at first it will have native NDI support but I doubt thats the case since the other devices listed in PP365 are indeed webcamera devices.

The right way is to pite NDI or with the NDI webcam or with OBS and virtualcamera within.

**Comment by Trouffman** [comment]
Confirmed : Powerpoint only accept Webcam-like stream (DirectShow). 
NDI is not that.

To achieve what you want / need you must use NDI Webcam and configure it to pull on of the NDI stream you are sending.

**Comment by tictag** [comment]
OK, we should close the issue as a non-issue.
