### ISSUE TITLE
[Bug]:  NDI Runtime Don't Install

### ISSUE THREAD

**Issue by imCruxi** [obs-ndi/obs-ndi#1011]
### Operating System Version

Ubuntu 24.04 LTS

### OBS Version

30.0.2.1

### OBS Installation Method

apt

### OBS-NDI Version

4.13.2

### OBS-NDI Installation Method

.deb

### [Extra] Installation Steps

sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt update
sudo apt install ffmpeg obs-studio

sudo chmod -R 777 libndi-get.sh
sudo bash libndi-get.sh

sudo apt install avahi-daemon ffmpeg
sudo systemctl enable avahi-daemon
sudo systemctl start avahi-daemon
sudo ufw allow 5353/udp
sudo ufw allow 5959:5969/tcp
sudo ufw allow 5959:5969/udp
sudo ufw allow 6960:6970/tcp
sudo ufw allow 6960:6970/udp
sudo ufw allow 7960:7970/tcp
sudo ufw allow 7960:7970/udp
sudo ufw allow 5960/tcp

sudo chmod -R 777 obs-ndi-4.13.2-x86_64-linux-gnu.deb
sudo dpkg -i obs-ndi-4.13.2-x86_64-linux-gnu.deb

### NDI Version

libndi.so.5.6.1

### Describe the bug

after follow steps, i try open OBS Studio and this show me a MessageBox: "NDI Runtime not found download here: https://github.com/obs-ndi/obs-ndi/blob/master/CI/libndi-get.sh"

### Screenshots

![Captura desde 2024-05-07 21-17-01](https://github.com/obs-ndi/obs-ndi/assets/99058402/90e53bea-4f57-4400-8feb-bc4bafac2bf3)

**Comment by youcangetme** [comment]
Hello, this is a known issue. You need to reboot after the install. The runtime writes paths to the various libraries and those need to be updated before the OBS plugin will work again. I have seen this on both the Windows and Linux machines I recently updated.

**Comment by imCruxi** [comment]
> Hello, this is a known issue. You need to reboot after the install. The runtime writes paths to the various libraries and those need to be updated before the OBS plugin will work again. I have seen this on both the Windows and Linux machines I recently updated.

Hi, i reboot the system but the problem persists

**Comment by RayneYoruka** [comment]
We haven't tested on Ubuntu 24.04 since it was just released, please provide a obs log, most likely it's missing the libs linking that obs needs to work.

**Comment by RayneYoruka** [comment]
> We haven't tested on Ubuntu 24.04 since it was just released, please provide a obs log, most likely it's missing the libs linking that obs needs to work.


And to add, have you ran the script that is provided on the link ??
`
sudo ./libndi-get.sh`

**Comment by imCruxi** [comment]
> We haven't tested on Ubuntu 24.04 since it was just released, please provide a obs log, most likely it's missing the libs linking that obs needs to work.
> 
> And to add, have you ran the script that is provided on the link ?? ` sudo ./libndi-get.sh`

where i can found the obs log? btw, yes, i ran the script before install obs-ndi-4.13.2-x86_64-linux-gnu.deb

**Comment by Trouffman** [comment]
It seems the NDI Runtime are not in there. ANd this step was missing in the installation wiki.

Please retry the process described at : the [linux pre-requisites installation steps](https://github.com/obs-ndi/obs-ndi/wiki/1.-Installation#linux).

**Comment by Trouffman** [comment]
@imCruxi : please try executing 
./libndi-get.sh install
By default the script does not install the lib, just uncompress them.

**Comment by imCruxi** [comment]
> @imCruxi : please try executing ./libndi-get.sh install By default the script does not install the lib, just uncompress them.

thanks a lot! this this works for me

**Comment by imCruxi** [comment]
> We haven't tested on Ubuntu 24.04 since it was just released, please provide a obs log, most likely it's missing the libs linking that obs needs to work.
> 
> And to add, have you ran the script that is provided on the link ?? ` sudo ./libndi-get.sh`

i finally fix the problem, now mi new issues is a black screen, when i put the NDI Output Setting on mi OBS ubuntu, the Obs on mi Windows 10 recognize the source but only show a black screen

Windows 10:
![image](https://github.com/obs-ndi/obs-ndi/assets/99058402/660f7ef0-5eb0-4696-beb9-854944aa10fb)

**Comment by RayneYoruka** [comment]
Firewall in the windows machine.

https://github.com/obs-ndi/obs-ndi/wiki/2.-Troubleshooting

**Comment by imCruxi** [comment]
> Firewall in the windows machine.
> 
> https://github.com/obs-ndi/obs-ndi/wiki/2.-Troubleshooting

i set my Network on private, i given to NDI permissions on my Firewall but nothing happening.
otherwise if im turn ON the NDI Output Setting on my windows, ubuntu can receive the signal

**Comment by Trouffman** [comment]
@imCruxi - glad your original issue is resolved. this will be closed.
Regardint your black screen : please check the troubleshootign steps. and open a new issue if needed.
https://github.com/obs-ndi/obs-ndi/wiki/2.-Troubleshooting#troubleshooting
