### ISSUE TITLE
Question: Is it the OBS NDI Plugin or the NDI Runtime?

### ISSUE THREAD

**Issue by youcangetme** [obs-ndi/obs-ndi#1012]
There is a long running problem that I was hoping would get resolved in NDI v6 but doesn't seem to have changed.

I am not sure to file a bug here or with NDI (but I can't find a bug reporter for them which is why you are the unlucky lottery winner).

This issue is when using PowerPoint on Windows and the NDI Tools Screen Capture utility. If the PP does not have transitions between slides and you wait a while with one slide up and then you change slides, the OBS NDI source doesn't seem to be reliably updated. Sometime it will not update at all.

See this forum posting I just replied to about this issue over on the OBS Forums; https://obsproject.com/forum/threads/ndi-5-lag-in-obs-not-in-ndi-studio-monitor.175310/

I would love to file the bug report in the right place so if you could help out, it would be a huge win for all of us.

Thank you!

**Comment by Trouffman** [comment]
At first glance this looks like the NDI screen capture issue.

Do you have the same symptom when watching that NDI feed in NDI studio monitor?
If yes >> NDI screen capture issue
If no >> maybe mismatched framerate

Also make sure the the transition is happening on the source PPT PC as well.

**Comment by youcangetme** [comment]
Let me confirm if the slides are not updating or slow updating via the NDI Monitor, not just OBS.

I can confirm it isn't PP or the clicker not working. Adding a transition between the slides makes it work as long as the source is visible in the either the preview or live. If it isn't visible in OBS it doesn't update either.

I will do this Saturday as I will be running a presentation and live stream then. I will make a note to update this ticket with the results.
