### ISSUE TITLE
[Bug]: Long running issue with minimizing to system Tray

### ISSUE THREAD

**Issue by TechNoobFGC** [obs-ndi/obs-ndi#1037]
### Operating System Version

Win 10 latest build up to date as of 6/20/24

### CPU

2700

### GPU

4060

### NDI Devices

Input Overlay, mainly

### OBS Version

This has happened at least since 29, up to the most recent Beta 30.0.4

### OBS Installation Method

Non Portable method

### OBS-NDI Version

Latest 5

### OBS-NDI Installation Method

From this Git

### NDI Version

5

### Describe the bug

So for the longest time I've been wondering when I minimize my OBS, it won't minimize to the system tray, even though I have the option enabled. Buried on the internet, I chanced upon this link: https://obsproject.com/forum/threads/cant-minimize-to-system-tray.111991/

Out of chance I decided to try just installing that plugin alone. Lo and behold, it works. I love this plugin, and would rather use NDI over something that has more recent support, but is there a fix for this somewhere in the pipeline? Would also love to see an update on this soon, as I still believe NDI 5 is the way to go! Keep making great things :)

### Steps to reproduce the problem

1. install NDI plugin for OBS here
2. make sure everything is checked for minimizing to sys tray.
3. try to minimize.
4. If it fails, uninstalling the OBS NDI 4.1 plugin resolves the issue immediately

### Expected behavior

I should be able to minimize to sys tray without a plugin interfering

### Screenshots

N/A, can be pretty easily reporduced

### Additional context

N/a

**Comment by paulpv** [comment]
Known issue.
https://github.com/obs-ndi/obs-ndi/issues?q=minimize

Main bug that mentions the fix is https://github.com/obs-ndi/obs-ndi/issues/587

Closing this one; will fix in https://github.com/obs-ndi/obs-ndi/issues/587

**Comment by TechNoobFGC** [comment]
Hey Paul, thanks for the quick response. How do I go ahead and make the fix myself until the next update? Not too familiar with coding, but if I can like remove the lines, recompile and do a custom install that would be great. There is no Settings.ui I could find associated with OBS

**Comment by paulpv** [comment]
I think just removing the lines https://github.com/obs-ndi/obs-ndi/blob/04ec2ca44202fd7b884f95d81829ba1c616c9dc9/src/forms/output-settings.ui#L5-L7 and recompiling would be all that needs to be done.
https://github.com/obs-ndi/obs-ndi/wiki/3.-Development#building

PatTheMav is an OBS God, and I 99% trust his finding on this.
I'm not 100% because there might be side-effects of removing those lines and making that dialog non-modal, which is the main reason I am not willing to rush out a fix until I take a little time to test and handle any side-effects.

I am very surprised [and confused by] that...
```
  <property name="windowModality">
   <enum>Qt::WindowModal</enum>
  </property>
```
...on the src/forms/output-settings.ui **that isn't even showing** is causing this problem.

**Comment by TechNoobFGC** [comment]
Thanks, I'll give it a shot and see if that works. I'm not a programmer fully (yet), but If it's any consolation, Twitch docks were having an issue with QT stuff if OBS was maximized with the minimize to tray option enabled. It wouldn't minimize to system tray properly and the docks were just all over. Bizarre indeed, and the consensus, I think, is that QT may be the culprit. OBS's answer was that the other option was to either have OBS crash all the time or this, and they chose the lesser of the two evils haha
