### ISSUE TITLE
ESET NOD 32 Firewall Issue (Black Screen)

### ISSUE THREAD

**Issue by adir6** [obs-ndi/obs-ndi#324]
Hello! I'm having two systems connected to each other using ASUS Router. (Gigabit)

I've ESET NOD 32 installed on the Main PC (on which I play Games).

So, If the ESET NOD 32's Firewall is active, it doesn't let my streaming PC see the video. Though, It shows the black screen.

Yes, Both the computers are able to communicate with each other.

But, As soon as the firewall is deactivated, I get the video and black screen goes away.

If someone could help me with this?

@Palakis if you could help.

Exact Same Issue: https://github.com/Palakis/obs-ndi/issues/273

**Comment by Trouffman** [comment]
Closing this issue as it is old/not been updated/expired and most- likely fixed in more recent version.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.
> especially the part with the firewall requirements. (there are special port NDI uses)
