### ISSUE TITLE
Frames missed due to rendering lag

### ISSUE THREAD

**Issue by ZeroTwoNineInc** [obs-ndi/obs-ndi#350]
I have the problem, that with the latest update the rendering interrupts and OBS stats show:
Frames missed due to rendering lag 36%
What am I missing?

**Comment by Palakis** [comment]
@ZeroTwoNineInc Does the same happens with the NDI plugin uninstalled?

**Comment by paulpv** [comment]
Is this still and issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by Trouffman** [comment]
Closing this issue as it is old/not been updated/expired and most- likely fixed in more recent version.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.
