### ISSUE TITLE
OBS crashes when NDI is started.

### ISSUE THREAD

**Issue by DrakeekarD** [obs-ndi/obs-ndi#351]
I can't seem to get this program to work correctly. As soon as I activate NDI, obs crashes. Here is the crash log if that helps. 

[crashlog.txt](https://github.com/Palakis/obs-ndi/files/3629306/crashlog.txt)

**Comment by revbigD** [comment]
@Palakis when would we expect 4.8.0?

**Comment by led78** [comment]
Same here, OBS crashes as soon as the NDI source is activated. I'm on MacOS High Sierra (10.13.6).

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by paulpv** [comment]
Closing this with the obs-ndi 4.12.0 release and OBS 30 release.
Please comment here if this is still happening and we can reopen.
