### ISSUE TITLE
OBS NDI to OBS NDI laggy as hell...

### ISSUE THREAD

**Issue by serv01** [obs-ndi/obs-ndi#355]
I have been using OBS NDI plugin to send video from laptop to desktop computer. It was working great until it didn't. Sudently after upgrading NDI OBS plugin, Video and audio became laggy a lot (sending 1920x1080p, 60FPS at only arround 30Mb/s instead previously 140Mb/s). Laggyness started when updated to latest version NDI plugin.

What I have tried and still laggy:
- NDI Scan Converter from laptop to desktop PC with OBS Studio
- OBS Studio from laptop to desktop PC with OBS Studio
- I went over your documentation with what to do and I already did that.
- Disabled all power saving and green setting arround network
- Tried with another USB 3.0 Gigabyte network card and even over WiFi 5G
- Replaced network cables and even network gigabyte switch
- Several different versions of OBS Studio and OBS NDI plugin (always fresh install)
- (probably even more but I do not remember...)

What I have tried and working normally:
- NDI Scan Converter (NDI Tools) to OBS Studio LOCALY on same laptop
- NDI Scan Converter to XSplit LOCALY on same laptop to OBS and to desktop PC OBS
- OBS Studio on laptop to XSplit on desktop PC
- OBS Studio on desktop PC to OBS Studio on laptop and another laptop
- XSplit on laptop to XSplit on desktop PC
- Android NDI app from smartphone to OBS Studio on desktop PC and laptop
- (probably even more but I do not remember...)

So it looks like, it is not working from the laptop with OBS studio+OBS NDI plugin and NDI tools (from newtek website) to any computer with OBS studio+NDI plugin! 

Laptop is ASUS ROG G752VL on Windows 10 pro x64 version 1809 and 1903.
Desktop PC on Windows 7 x64 Ultimate
Second laptop regular i5 laptop, 4GB ram on Windows 7 x64 Ultimate
Android phone Huawei P20 Lite

**Comment by jimthesfn** [comment]
I have also noticed this now that I've been using it since it was released. I get a lot of stuttering and you can really hear it with the sound.
It also happens that the video stutters and even had it freeze up. Something seems to be messing it up with the new NDI 4 Runtime I assume. I had to go back to 4.6.2 and 3.8 Runtime for it to run smoothly again.

**Comment by serv01** [comment]
Thank you, I will try today and I will report the results. =)

**Comment by jimthesfn** [comment]
> 
> 
> Thank you, I will try today and I will report the results. =)
> 
> UPDATE: Yeeej, it is working, thank you very much =)

Glad to hear it! Seems like it is something in the NDI 4 Runtime from Newtek that is messing up things.

**Comment by serv01** [comment]
So I made an video tutorial, who does not know or not sure, how to uninstall previous versions, download and install working versions. If this is not allowed just delete this post =).

Video tutorial: https://www.youtube.com/watch?v=c1zzPE2oIfE

**Comment by gavalierm** [comment]
Same here.

Two different pc, two systems same problem. NDI cam lag every 1 second AND whole audio is damaged..

When you "hide" NDI source, audio works good, when show NDI audio get broken.

It get fixed when i install older 4.6.2 and you can use lates NDI runtime.

I was exited when 4.8 came out. But still no fix.

So roll back to 4.6.2 without problem.

**Comment by reesericci** [comment]
Will anyone fix this? @Palakis

**Comment by serv01** [comment]
So I am using NDI SDK version 4.5.1.0 (OBS window - Tools - NDI) on both OBS computers and it works normally :)

**Comment by reesericci** [comment]
i found that 3.8 works

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by Trouffman** [comment]
Closing this issue as it is old/not been updated/expired and most- likely fixed in more recent version.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.
