### ISSUE TITLE
Cannot see any source on second PC

### ISSUE THREAD

**Issue by EpicTeddy101** [obs-ndi/obs-ndi#371]
Hey everyone,

I am struggling to get a source from my Gaming PC (PC1) to my second PC (PC2).
This is what I have done:

I have both OBS and obs-ndi installed on both PC's (Both updated as well).
I have made both OBS on PC1 and PC2 Public and Private in the Firewall.
I set my network on both to Private.
I turn on Main Output on PC1, add an NDI Source on PC2, and nothing comes under the source name dropdown box.

Both PC's are connected via Ethernet. One is to the router and the other is to a switch as we don't have enough ethernet ports. This switch is connected to the same router however.

Please help.

**Comment by WestieGG** [comment]
I made an account for this exact issue. I can see my OBS feed when I open studio monitor, but I cannot see the name of the feed or select it in the source name drop down inside OBS.

**Comment by secstu** [comment]
I can confirm that this is the case.

I'm myself in a bit of a pickle since I want to stream into my ubuntu box. What seems to happen is that there is no source anywhere. Even after loads of restarts to the system, disabling the firewall, and making sure that the machines and bi-conenct to eachother.

Also worth mentioning is i'm running a home firewall(pfsense) and i can clearly see that the machines can communicate to each other (i can ssh/rdp/vnc/smb) but i cannot see the NDI connected devices

I also tried following the TCP stream on wireshark but to no avail or informative results..

**Comment by Palakis** [comment]
@secstu On Windows you can use the Group Access Manager tool to add specific lookup IP addresses for NDI discovery. The tool is available in the NDI Tools.

**Comment by samwzlim** [comment]
> @secstu On Windows you can use the Group Access Manager tool to add specific lookup IP addresses for NDI discovery. The tool is available in the NDI Tools.

This should be pinned as the top solution for this problem! I myself have been facing this same issue and tried every possible solution but only this worked. I had to specify my other computer's IP address in order for it to be detected.

![image](https://user-images.githubusercontent.com/74489037/113228393-5d83d480-92c7-11eb-87bb-9e71c8fa3840.png)

**Comment by samwzlim** [comment]
> @secstu On Windows you can use the Group Access Manager tool to add specific lookup IP addresses for NDI discovery. The tool is available in the NDI Tools.

This should be pinned as the top comment! I myself had the same issue, and tried every possible solution, but only this worked. I had to manually from NDI Access Manager which can be installed from NDI tools. 

![InkedShareX_WiQUFnntA2_LI](https://user-images.githubusercontent.com/74489037/113228566-b8b5c700-92c7-11eb-8273-902967c141a9.jpg)

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by paulpv** [comment]
Closing due to no response and release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
