### ISSUE TITLE
Random crashes of OBS on the receiving side

### ISSUE THREAD

**Issue by IceFlom** [obs-ndi/obs-ndi#374]
Hi,
I wanted to use obs-ndi for the first time. I installed the latest version of the plugin (4.7.1) on both PCs and I'm using the NDI runtime which is downloaded by the installer.
I can send the video from my gaming pc to the streaming pc without any problem. But I get random crashes of OBS on the streaming pc (the OBS which is receiving the video signal). I'm not able to reproduce this failure, it seems to be completely random. Sometimes it works for more than 10 minutes, but it's also possible that I get a crash after seconds.
Unfortunately I'm not able to read the cause of the crash from the crash log.

If I don't use obs-ndi I don't have any problems or crashes.

Does anyone have an idea why OBS is crashing with obs-ndi? I've attached the crash log. Please tell me if you need some more logs or informations.

[Crash 2019-11-26 12-55-56.txt](https://github.com/Palakis/obs-ndi/files/3896839/Crash.2019-11-26.12-55-56.txt)

**Comment by Popnhand** [comment]
I'm having this same exact problem right now. Did you find a solution yet Ice?

**Comment by IceFlom** [comment]
No, I was not able to find a solution for this problem. I'm using a capture card now.

**Comment by IceFlom** [comment]
Tried it again with the latest version, but nothing changed.

**Comment by IceFlom** [comment]
It's working for me now. The problem was the PC which is sending the signal. It caused a crash of OBS on the receiving side on different systems. After switching to an external USB3 Network card on the sending system, it works without any problem. It's very weird, I don't know why it does not work with the interal network chip because I have no other problems with it.

PC which is sending the NDI signal ->
Problems (receiving OBS crashes): Intel I211 Gigabit Network Adapter
No problems: ASIX AX88179 USB 3.0 to Gigabit Ethernet Adapter

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by paulpv** [comment]
Closing this with the obs-ndi 4.12.0 release and OBS 30 release.
Please comment here if this is still happening and we can reopen.
