### ISSUE TITLE
obs crashes when ndi is installed

### ISSUE THREAD

**Issue by Shmookoff** [obs-ndi/obs-ndi#377]
I can't even open obs when ndi is installed, but if I delete it, obs works correctly. There is a log:
[2019-12-09 16-06-19.txt](https://github.com/Palakis/obs-ndi/files/3939351/2019-12-09.16-06-19.txt)

**Comment by alastairweller** [comment]
I am also experiencing this issue on a new Mac mini. I'm running OBS 25.0.6 and OBS-NDI 4.8.0; I have tried both the NDI runtime auto downloaded from Newtek, the v4.5.1 downloaded from palakis.fr and also the 4.0 version from https://github.com/nariakiiwatani/ofxNDI

OBS crash scenarios include when adding or amending an image, and changing the audio of a VLC source to monitor and output from just output; these occur whether NDI sources or scenes containing NDI sources are present or not. 

Logs at https://obsproject.com/logs/HdNEBmaucqeRPnlE if that is of any help

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by paulpv** [comment]
Closing due to no response and the release of 4.12.0
