### ISSUE TITLE
Ndi won't load (OBS exe name change)

### ISSUE THREAD

**Issue by lcatlas** [obs-ndi/obs-ndi#384]
Hello, thanks alot for a help.

The problem is, when i change obs exe file (it's needed for instagram start/restart, so it won't close all other obses) ndi plugin is loading with OBS, but won't load a source.

Anyway to fix it by myself? Or try to use obs32 for instagram?

**Comment by Palakis** [comment]
@lcatlas What is this instagram stuff you're talking about?

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?
