### ISSUE TITLE
OBS crashing on boot even on fresh install

### ISSUE THREAD

**Issue by lonseidman** [obs-ndi/obs-ndi#392]
I am unable to get OBS to run with the NDI Plugin installed on any of my Windows 10 machines. This morning I tried setting it up on a fresh laptop and getting the same results. I installed and configured OBS for a recording profile (just running the wizard), closed OBS and installed the NDI plugin from its Windows installer making sure it was also installing the runtime. After installation OBS crashes on boot. I then tried to manually install the 4.0 runtime - same results.

This behavior is happening on three of my Windows PCs - all of them are running with Nvidia GPUs with the latest drivers installed. Crash log is attached. Given that not many others have this issue I'm clearly missing something obvious. Any help is appreciated!
[crashlog.txt (1).txt](https://github.com/Palakis/obs-ndi/files/4198879/crashlog.txt.1.txt)

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by paulpv** [comment]
Closing due to no response and release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
