### ISSUE TITLE
OBS Crashes when I click okay in Tools/NDI output setting/main output/

### ISSUE THREAD

**Issue by ghost** [obs-ndi/obs-ndi#398]
Please help me out.
my obs crashes when i click okay in Tools/NDI output setting/main output/
This happens to my Dual core E2180 Cpu computer.
When i go to tools in obs and click on NDI Output Setting and fill up my name and click okay then OBS creates a crashing report and crashes .

I had re installed all the plugin for 5 times and restarted my pc 10 times but i couldnot configure out the same problem please help me out.

**Comment by rcuijpers** [comment]
Having the same problem, trying to load my iPhone steam into the NDI setting (OBS Camera app https://obs.camera) and when I try to save that it just crashes. 

OBS version: 24.0.6 (64bit)
OSX version: 10.15.3

**Comment by barbro66** [comment]
Same here - I attached the crash log
[crash.txt](https://github.com/Palakis/obs-ndi/files/4386699/crash.txt)

**Comment by rmarkeson** [comment]
Same issue on my MAC. 24.0.6 (64 bit)
MacBook Pro (Retina, 13-inch, Mid 2014); 2.6 GHz Dual-Core Intel Core i5; macOS 10.15.4

When I choose the NDI source camera it does not show any preview, then when I select 'OK' it crashes the app.

**Comment by DREYONE1** [comment]
I have the same crashing issue, Now on OBS 24.0.6, OSX 10.15.4. Not sure if I should contact you as the plug in owner or OBS.

**Comment by kaii-tech** [comment]
same issue

**Comment by DREYONE1** [comment]
Actually this is the fix guys. Read through and find guy named Martin. Fixed mine right up. 

https://obsproject.com/forum/threads/obs-ndi-crashes-upon-selecting-source-mac-high-sierra.117404/page-2

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?
