### ISSUE TITLE
turning NDI on freezes OBS and makes a really weird color distortion 

### ISSUE THREAD

**Issue by nachocupoftea** [obs-ndi/obs-ndi#417]
Kinda new at all this but i thought i figured it out.
i have everything set up ,download ndi on both pc's, set my main pc obs ndi output setting on, i see it in my receiving pc but after 2 seconds my main pc obs freezes and makes a bright color distortion.
ive restarted both pc's after installing ndi. i was fooling around with the color settings but it did nothing.
please help

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by paulpv** [comment]
Closing due to no response and release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
