### ISSUE TITLE
NDI-Source and Virtual Audio Driver

### ISSUE THREAD

**Issue by aruggeri74** [obs-ndi/obs-ndi#420]
I'm on macOS Catalina. Using Last OBS studio and Last OBS-NDI.

I have an NDI source from another Mac in my network. Stream front cam and mic audio. And it works fine.

In the destination Mac in which in have this NDI-Source configured I need also to record a window audio. For that I've installed Blackhole 16ch (but tried also others, same result).

The problem is that NDI-Source audio is always included in my windows audio source and this create echo and delay problem.

I've tried yet to set NDI-Source to Monitor Only in Advanced audio Properties but NDI-Source audio is however input in my virtual audio driver.

There is way to have NDI-source ONLY monitored (so I can hear it in headset) but not passed to my blackhole virtual audio driver ?

Thanks

**Comment by Trouffman** [comment]
Closing this issue as it is old/not been updated/expired and most- likely not a plugin issue but a configuration or unsupported usage.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.
