### ISSUE TITLE
OBS does not remove itself from the taskbar when NDI plugin is used

### ISSUE THREAD

**Issue by Axel0689** [obs-ndi/obs-ndi#441]
## Platform

Notebook: Acer Aspire E15-573G-79UB
Processor: Intel i7-5500u 2.40 Ghz - Dual Core
Graphics: Intel Graphic 5500 and Nvidia Geforce 920M
RAM: 8 GB
Operating system and version: Windows 10 1909
OBS Studio version: 25.0.4
Plugin Installed: OBS VirtualCam, NDI Sources

## Expected Behavior

After starting it, I would like OBS to be displayed during recording and live are in the system tray and not in the taskbar.

## Current Behavior

Basically - if I set OBS to minimize to tray AND minimize to tray on start-up it goes to tray on start-up, but if I bring it out of there.. And try to minimize it again it just goes to the taskbar, not to the tray.. And the "Hide" option when you right click the OBS tray icon doesn't do anything at all.

## Verification of the problem

From practice, I proceeded as follows: uninstalled OBS and plugins and gradually check where the problem arises.

Then I installed OBS -> VirtualCAM -> NDI Plugin. Until virtual CAM, the hide taskbar function works. (as seen in the video: https://streamable.com/tmfxtz

Installing NDI Plugin, the problem arises. (all this on my notebook.) In fact, the different checkpoints and the "Hide" command (right click on the system tray) do not work.

**Comment by paulpv** [comment]
Known issue.
https://github.com/obs-ndi/obs-ndi/issues?q=minimize

Main bug that mentions the fix is https://github.com/obs-ndi/obs-ndi/issues/587

Closing this one; will fix in https://github.com/obs-ndi/obs-ndi/issues/587
