### ISSUE TITLE
cmake error at /usr/local/lib/cmake/LibObs/LibObsTarget.cmake:81

### ISSUE THREAD

**Issue by jcfrosty** [obs-ndi/obs-ndi#446]
/usr/local/lib/libobs.so.0 does not exist.. But it actually does exist. It exists under /usr/local/lib64/libobs.so.0 .

Gentoo library hierarchy is broke up like this
noarch - lib
32bit - lib32
64bit - lib64

I'm assuming this could be a trivial fix?

The next issue is looking for "/usr/local/include/obs", but gentoo stores this in /usr/include/obs . Also possibly trivial if you can add it as another optional path.

After adding symlinks to accommodate this, the package compiles fine, but installs incorrectly. It installs to /usr/lib/obs-plugins/obs-ndi.so and /usr/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so which is in the noarch folder. the correct folder is /usr/lib64/obs-plugins.

moving the file from /usr/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so to /usr/lib64/obs-plugins/obs-ndi.so fixes this issue.

Now when launching OBS studio, it fails to load the plugin with the ndi-sdk installed, because once again, it search /usr/lib and /usr/local/lib . It refuses to search /usr/lib64 and user/local/lib64.

creating a symlink fixes this, but these symlinks are all temporary hacks to prove the plugin works. the installer itself isn't aware enough to place the files in the correct areas.

**Comment by paulpv** [comment]
The build has changed a lot in over 3 years.
Closing.
