### ISSUE TITLE
Locating libobs-ndi.so and libndi.dylib

### ISSUE THREAD

**Issue by jjdeprisco** [obs-ndi/obs-ndi#447]
Unable to located these files to perform last two instructed steps for Mac OS:

# Copy libobs-ndi.so to the obs-plugins folder
# Copy libndi.dylib from the NDI SDK to the obs-plugins folder too

Unable to locate libobs-ndi.so and libndi.dylib

Runtime package is installed.
Mac OC High Sierra.

**Comment by paulpv** [comment]
Closing due to release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
