### ISSUE TITLE
Compatibility problems with Windows 10

### ISSUE THREAD

**Issue by joetaras** [obs-ndi/obs-ndi#449]
Hi,
I've installed on my PC (with Windows 10) the OBS Studio and NDI plugin.

When I try to add Source on my Scene, I add a NDI-Source to show Skype web cam output, but I see the NDI source black. If I try the same operation with Windwos 7 PC that's OK.

I try to install the Windows 4.8.1 installer (the exe file) and I try after to installa zip file and 4.5.1 installer (as adviced on the guide), but I have the same behaviour.

Have you another way to resolve this? Or I'm wrong about some installation step?

Thank you in advance

**Comment by richross** [comment]
Check issue #442 
Posted a response there on the skype version needed.

**Comment by paulpv** [comment]
Is this still an issue in 4.13.0?
The linked issue above was closed by the opener.
Closing this, but you can reopen if it is still happening.
