### ISSUE TITLE
Plugin does not appear in list of sources on OSX 10.15.4 + OBS 25.0.7

### ISSUE THREAD

**Issue by mydudechris** [obs-ndi/obs-ndi#453]
I've installed the plugin. No crashes, however, NDI does not appear in my list of available sources. I've tried installing a few times with no luck.

**Comment by mydudechris** [comment]
Just saw the text on the release page, so I have to use V24 of OBS on OSX in order to use this? When will support for 25 be available?

**Comment by Palakis** [comment]
@mydudechris obs-ndi 4.8 should work on OBS v25. Have you tested if it works only in v24 and not v25?

Otherwise I'll just make a bugfix release for macOS.

**Comment by DrConflict** [comment]
> @mydudechris obs-ndi 4.8 should work on OBS v25. Have you tested if it works only in v24 and not v25?
> 
> Otherwise I'll just make a bugfix release for macOS.

The plugin shows up fine for me with the exact same software versions.

**Comment by paulpv** [comment]
Closing due to release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
