### ISSUE TITLE
The "NDI Source" extension is not showing up.

### ISSUE THREAD

**Issue by Anden-sama** [obs-ndi/obs-ndi#456]
I've installed the runtime, the ndi binaries. ALL. But, in OBS Studio, It's only showing up the "NDI Output Settings" but not the extension in the '+' icon. Because of it I cannot put any NDI source input.
Oh, and I have the newest OBS version btw.

I just want to create a "postcast" via Skype. The NDI signal from Skype is on, but anyway OBS Studio don't allow me to catch it. :,,)

![1](https://user-images.githubusercontent.com/47400087/80266570-dec3f780-8672-11ea-94ba-eabd1458766d.PNG)

![2](https://user-images.githubusercontent.com/47400087/80266577-e2f01500-8672-11ea-9631-5186063e5e85.PNG)

Can anyone help me with this issue pls?

Thanks. 😊

**Comment by EmilJacobs** [comment]
I have the same issue on a fresh install of Ubuntu 20.04 with libndi4_4.5.1-1_amd64.1.deb and obs-ndi_4.8.0-1_amd64.deb installed using OBS 25.0.7

**Comment by EmilJacobs** [comment]
I have now replicated the issue on a fresh install of Ubuntu 18.04, just to rule out incompatibilities with 20.04. I have still OBS 25.0.7 installed. I tried now versions 4.8 and 4.7.1 of the plugin with the respective library. They install without issue. Still, no dice. What is going on here?

**Comment by ubivent-seuffert** [comment]
to make it work i had to copy: `sudo cp /usr/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so /usr/lib/obs-plugins/`
(Using ubuntu 19.10)

Release notes state: 

> Bugfix: the Ubuntu/Debian package now only installs the plugin into /usr/lib/x86_64-linux-gnu/obs-plugins (#460)

**Comment by dinamitrii** [comment]
Hello,
i have a similar problem - want to set-up broadcast with 2 pc and the newest pc everithing is ok but on the oldest the NDI section is not showing-up neither in source and tools.Both pc have the same Windows10 and the latest OBS and NDI plugin.
Thanks in advance.

**Comment by dinamitrii** [comment]
Hello again,
I think figured it out check your CPU is supporting the **SSSE3** instructions set!!!Or check your log files!!

**Comment by EmilJacobs** [comment]
> Hello,
> I think figured it out check your CPU is supporting the **SSSE3** instructions set!!!Or check your log files!! @EmilJacobs @Anden-sama @Palakis

How exactly would that impact the plugin showing up or not? I'm running both installs in a VM (Qemu/Boxes), but I kind of expect that to be a non-issue.

**Comment by dinamitrii** [comment]
> 
> 
> > Hello,
> > I think figured it out check your CPU is supporting the **SSSE3** instructions set!!!Or check your log files!! @EmilJacobs @Anden-sama @Palakis
> 
> How exactly would that impact the plugin showing up or not? I'm running both installs in a VM (Qemu/Boxes), but I kind of expect that to be a non-issue.

So it is a problem i have it too.Just chek your log file in OBS

**Comment by edscott001** [comment]
Is there an update to this issue? I'm running macOS 10.14.6 (Mojave), OBS 25.0.8, and downloaded the latest obs-ndi file, 4.9.0. I ran the installer, and it says it completed successfully, but when opening OBS, NDI Source does not appear in the list of sources to choose from. I have tried installing several times, restarting OBS and my Mac, but the issue persists. Can you let me know if this is a known issue in progress, or if I'm doing something wrong?

Thank you,

**Comment by GalanM-create** [comment]
L'extension "NDI Source Disparu, 
Moi j'avais tout installé, prêt a l'emploie , et aujourd’hui  OBS, NDI source n'apparaît pas dans la liste des sources à choisir. J'ai essayé d'installer plusieurs fois, en redémarrant OBS, j'ai même reinstalé OBS plus les plugins et aussi Skype mais rien n'est changé

**Comment by paulpv** [comment]
Closing due to release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
