### ISSUE TITLE
Smartphone running Newtek NDI doesn't show up as a Source in OBS

### ISSUE THREAD

**Issue by binuf** [obs-ndi/obs-ndi#458]
Have installed NDI SDK WIN64 Apr 1 2020 4.5.1.0 with OBS 25.0.4 64 Bit Windows. Newtek NDA v1.1 on my Android phone(running Android 10) was working just fine the first time I set everything up. However, the second day, it refused to show anything on the screen. Deleted the source and now smartphone doesn't show up in the list of sources while setting it up as a new source. Kept the app open on Phone and everything, still didn't work. Both PC and Phone on the same wifi network.

**Comment by SlavikCA** [comment]
I have same issue:
- I installed official NDI app on the iPad Pro 12.9
- Installed OBS 25.0.4 x64 on Windows
- Started NDI app on the iPad
Both iPad and Windows computer are on the same subnet.

And OBS shows no available NDI sources.

Then I started NDI Test Pattern on the same Windows computer and it was detected by OBS, as the source. But iPad is not recognized as source.

**Comment by SlavikCA** [comment]
hm, what a shame: my iPad started to work (seen by OBS as NDI source), when I disabled Firewall on the Windows system...

**Comment by binuf** [comment]
I did that, still didn't work! Just updated OBS on my PC for bugs today, no respite.
Running Windows 8.1, FYI. @Palakis what am I missing here?

**Comment by felixddi** [comment]
This problem also happened with me. Everything worked fine on the first day. after that, this problem occurs

**Comment by binuf** [comment]
I updated my Windows 8.1 and now it's working perfectly.

**Comment by binuf** [comment]
@felixddi try updating your OS and OBS to latest versions. Also make sure Newtek app on your phone is open while you're adding it as a source.

**Comment by WreckWren** [comment]
> 
> 
> @felixddi try updating your OS and OBS to latest versions. Also make sure Newtek app on your phone is open while you're adding it as a source.

This is not a solution, running up-to-date here on everything relevant and still no luck.

Since the Studio Monitor has no issues in this regard, I have to assume the issue is with the plugin or OBS. Since the plugin offers little to no user configuration, I am betting it's the plugin at fault.

**Comment by PbALpi7xEX** [comment]
I should have looked up the issues before dropping $30 on the NDI HX app on my iPhone!!!!! I have the same issue. NDI source doesnt show up in the list.

I thought my issue was related to Linux... but i guess seems it happens in other OSs. I've tried alot of things, disabled firewall, uninstalled the firewall, reinstalled OBS and the NDI plugins multiple times, but to no avail.

I have 2 PTZOptics NDI HX cameras I'm also trying to use but can't. Disapointed. :-(

**Comment by PbALpi7xEX** [comment]
for whats it worth, here's my OBS log in Linux:

[obs-ndi] hello ! (version 4.9.1)
08:06:26 AM.835: [obs-ndi] Trying ''
08:06:26 AM.835: [obs-ndi] Trying '/usr/lib'
08:06:26 AM.835: [obs-ndi] Found NDI library at '/usr/lib/libndi.so.4'
08:06:26 AM.845: [obs-ndi] NDI runtime loaded successfully
08:06:26 AM.845: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 00:05:02 Apr  1 2020 4.5.1)
08:06:26 AM.971: VLC found, VLC video source enabled
08:06:26 AM.971: ---------------------------------
08:06:26 AM.971:   Loaded Modules:
08:06:26 AM.971:     vlc-video.so
08:06:26 AM.971:     text-freetype2.so
08:06:26 AM.971:     rtmp-services.so
08:06:26 AM.971:     obs-x264.so
08:06:26 AM.971:     obs-transitions.so
08:06:26 AM.971:     obs-outputs.so
08:06:26 AM.971:     obs-ndi.so
08:06:26 AM.971:     obs-libfdk.so
08:06:26 AM.971:     obs-filters.so
08:06:26 AM.971:     obs-ffmpeg.so
08:06:26 AM.971:     linux-v4l2.so
08:06:26 AM.971:     linux-pulseaudio.so
08:06:26 AM.971:     linux-jack.so
08:06:26 AM.971:     linux-decklink.so
08:06:26 AM.971:     linux-capture.so
08:06:26 AM.971:     linux-alsa.so
08:06:26 AM.971:     image-source.so
08:06:26 AM.971:     frontend-tools.so
08:06:26 AM.971:     decklink-ouput-ui.so
08:06:26 AM.971: ---------------------------------
08:06:26 AM.971: ==== Startup complete ===============================================
08:06:26 AM.986: All scene data cleared
08:06:26 AM.986: ------------------------------------------------
08:06:26 AM.992: [obs-ndi] started A/V threads for source ''
08:06:26 AM.992: [obs-ndi] A/V thread for 'NDI™ Source' started
08:06:26 AM.993: Switched to scene 'cam 5'
08:06:26 AM.993: ------------------------------------------------
08:06:26 AM.993: Loaded scenes:
08:06:26 AM.993: - scene 'cam 5':
08:06:26 AM.993:     - source: 'NDI™ Source' (ndi_source)
08:06:26 AM.993: ------------------------------------------------
08:06:27 AM.141: Switched to Preview/Program mode
08:06:27 AM.141: ------------------------------------------------
08:06:32 AM.993: User Removed source 'NDI™ Source' (ndi_source) from scene 'cam 5'
08:06:41 AM.025: [obs-ndi] started A/V threads for source ''
08:06:41 AM.025: [obs-ndi] started A/V threads for source ''

**Comment by stefankoehne** [comment]
May this be the solution for you?
https://github.com/Palakis/obs-ndi/issues/629#issuecomment-854609882

**Comment by paulpv** [comment]
Does `NDI Studio Monitor` have a similar problem?
