### ISSUE TITLE
Applying filter: 'Video Delay (Async)' (async_delay_filter) causes Black screen

### ISSUE THREAD

**Issue by wynnr** [obs-ndi/obs-ndi#469]
NDI HX iPhone App to OBS NDI source works until a Video Delay filter of 240 ms is applied. If filter is disabled video feed shows up again in OBS. NDI Monitor continues to show the video feed when delay filter is applied (which is to be expected) but the video feed goes black in OBS.

10:17:46.435: CoInitializeEx succeeded: 0x00000001
10:17:46.435: CPU Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
10:17:46.435: CPU Speed: 2592MHz
10:17:46.435: Physical Cores: 6, Logical Cores: 12
10:17:46.435: Physical Memory: 16303MB Total, 11636MB Free
10:17:46.435: Windows Version: 10.0 Build 18363 (release: 1909; revision: 815; 64-bit)
10:17:46.435: Running as administrator: false
10:17:46.435: Aero is Enabled (Aero is always on for windows 8 and above)
10:17:46.435: Windows 10 Gaming Features:
10:17:46.435: 	Game DVR: On
10:17:46.436: Sec. Software Status:
10:17:46.438: 	Windows Defender Antivirus: disabled (AV)
10:17:46.438: 	McAfee VirusScan: enabled (AV)
10:17:46.438: 	McAfee Firewall: enabled (FW)
10:17:46.439: 	Windows Firewall: disabled (FW)
10:17:46.439: Current Date/Time: 2020-05-03, 10:17:46
10:17:46.439: Browser Hardware Acceleration: true
10:17:46.439: Portable mode: false
10:17:46.675: OBS 25.0.8 (64-bit, windows)
10:17:46.675: ---------------------------------
10:17:46.676: ---------------------------------
10:17:46.676: audio settings reset:
10:17:46.676: 	samples per sec: 48000
10:17:46.676: 	speakers:        2
10:17:46.678: ---------------------------------
10:17:46.678: Initializing D3D11...
10:17:46.678: Available Video Adapters: 
10:17:46.680: 	Adapter 0: NVIDIA GeForce RTX 2080 with Max-Q Design
10:17:46.680: 	  Dedicated VRAM: 4104126464
10:17:46.680: 	  Shared VRAM:    4252657664
10:17:46.680: 	  PCI ID:         10de:1ed0
10:17:46.680: 	  Driver Version: 26.21.14.4587
10:17:46.681: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=144, name=
10:17:46.681: 	  output 1: pos={-894, -2160}, size={3840, 2160}, attached=true, refresh=60, name=LU28R55
10:17:46.683: Loading up D3D11 on adapter NVIDIA GeForce RTX 2080 with Max-Q Design (0)
10:17:46.795: D3D11 loaded successfully, feature level used: b000
10:17:46.795: DXGI increase maximum frame latency success
10:17:46.795: D3D11 GPU priority setup failed (not admin?)
10:17:47.220: ---------------------------------
10:17:47.220: video settings reset:
10:17:47.220: 	base resolution:   1920x1080
10:17:47.220: 	output resolution: 1280x720
10:17:47.220: 	downscale filter:  Lanczos
10:17:47.220: 	fps:               60/1
10:17:47.220: 	format:            NV12
10:17:47.220: 	YUV mode:          601/Partial
10:17:47.221: NV12 texture support enabled
10:17:47.223: Audio monitoring device:
10:17:47.223: 	name: Default
10:17:47.223: 	id: default
10:17:47.223: ---------------------------------
10:17:47.390: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
10:17:47.391: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
10:17:47.429: [AMF] Unable to load 'amfrt64.dll', error code 126.
10:17:47.432: [AMF] AMF Test failed due to one or more errors.
10:17:47.432: Failed to initialize module 'enc-amf.dll'
10:17:48.458: Failed to initialize module 'logi_obs_plugin_x64.dll'
10:17:48.483: [obs-browser]: Version 2.8.6
10:17:48.495: obs-browser: StreamElementsDecryptCefCookiesFile: 'C:\Users\Devo\AppData\Roaming\obs-studio\plugin_config\obs-browser\/Cookies': 0 succeeded, 0 failed
10:17:48.754: obs-browser: StreamElementsLocalWebFilesServer: folder does not exist: 
10:17:48.754: obs-browser: created request context and cookie manager with storage at 'C:\Users\Devo\AppData\Roaming\obs-studio\plugin_config\obs-browser\cef.74.0.chrome.0.1946.74.0'
10:17:48.771: obs-browser: StreamElementsExternalSceneDataProviderSlobsClient: path does not exist: C:/Users/Devo/AppData/Roaming/slobs-client/SceneCollections
10:17:48.773: obs-browser: init: set on-boarding mode due to start-up flags
10:17:48.874: obs-browser: central widget: loading url: https://obs.streamelements.com/welcome
10:17:48.885: obs-browser[1]: StreamElementsCefClient: initialized
10:17:48.964: NVENC supported
10:17:50.445: [obs-ndi] hello ! (version 4.9.0)
10:17:50.445: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
10:17:50.446: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
10:17:50.969: [obs-ndi] NDI runtime loaded successfully
10:17:50.980: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0)
10:17:51.115: Failed to load 'en-US' text for module: 'StreamDeckPlugin.dll'
10:17:51.133: Couldn't find VLC installation, VLC video source disabled
10:17:51.148: Decklink API Compiled version 10.11.4
10:17:51.148: Decklink API Installed version 11.5
10:17:51.164: ---------------------------------
10:17:51.164:   Loaded Modules:
10:17:51.164:     win-wasapi.dll
10:17:51.164:     win-mf.dll
10:17:51.164:     win-ivcam.dll
10:17:51.164:     win-dshow.dll
10:17:51.164:     win-decklink.dll
10:17:51.164:     win-capture.dll
10:17:51.164:     vlc-video.dll
10:17:51.164:     text-freetype2.dll
10:17:51.164:     StreamDeckPlugin.dll
10:17:51.164:     rtmp-services.dll
10:17:51.164:     obs-x264.dll
10:17:51.164:     obs-vst.dll
10:17:51.164:     obs-transitions.dll
10:17:51.164:     obs-text.dll
10:17:51.165:     obs-streamelements.dll
10:17:51.165:     obs-qsv11.dll
10:17:51.165:     obs-outputs.dll
10:17:51.165:     obs-ndi.dll
10:17:51.165:     obs-filters.dll
10:17:51.165:     obs-ffmpeg.dll
10:17:51.165:     obs-browser.dll
10:17:51.165:     logi_obs_plugin_x64.dll
10:17:51.165:     image-source.dll
10:17:51.165:     frontend-tools.dll
10:17:51.165:     enc-amf.dll
10:17:51.165:     decklink-ouput-ui.dll
10:17:51.165:     coreaudio-encoder.dll
10:17:51.165: ---------------------------------
10:17:51.165: ==== Startup complete ===============================================
10:17:51.170: All scene data cleared
10:17:51.170: ------------------------------------------------
10:17:51.177: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.177: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.177: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.178: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.178: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.178: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.180: [obs-ndi] started A/V threads for source 'THES-IMAC.LOCAL (StreamLyrics)'
10:17:51.180: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.181: [obs-ndi] A/V thread for 'Lyrics' started
10:17:51.181: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.187: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.188: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.188: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.188: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.189: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.189: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.189: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.191: [obs-ndi] started A/V threads for source 'THES-IMAC.LOCAL (StreamAudience)'
10:17:51.191: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.191: [obs-ndi] A/V thread for 'Slides' started
10:17:51.191: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.211: WASAPI: Device 'ZOOM Recording Mixer (H6)' [48000 Hz] initialized
10:17:51.211: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.213: [obs-ndi] started A/V threads for source 'HANDHELD (NDI HX Camera)'
10:17:51.213: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.213: [obs-ndi] A/V thread for 'Drum Camera' started
10:17:51.214: [obs-ndi] started A/V threads for source 'IPHONE (NDI HX Camera)'
10:17:51.214: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.215: [obs-ndi] A/V thread for 'Singers SR Camera' started
10:17:51.216: [obs-ndi] started A/V threads for source 'SOCRATES (NDI HX Camera)'
10:17:51.216: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.216: [obs-ndi] A/V thread for 'Singers SL Camera' started
10:17:51.217: [obs-ndi] started A/V threads for source 'PEARL (NDI HX Camera)'
10:17:51.217: signal_handler_connect: signal 'streamelements_update_settings' not found
10:17:51.218: [obs-ndi] A/V thread for 'Band SL Camera' started
10:17:51.264: Switched to scene 'Drum Scene'
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: signal_handler_connect: signal 'item_visible' not found
10:17:51.267: ------------------------------------------------
10:17:51.267: Loaded scenes:
10:17:51.267: - scene 'Drum Scene':
10:17:51.267:     - source: 'Drum Camera' (ndi_source)
10:17:51.268:         - filter: 'Video Delay (Async)' (async_delay_filter)
10:17:51.268:     - source: 'Graphics Scene' (scene)
10:17:51.268: - scene 'Singers SR':
10:17:51.268:     - source: 'Singers SR Camera' (ndi_source)
10:17:51.268:         - filter: 'Video Delay (Async)' (async_delay_filter)
10:17:51.268:     - source: 'Graphics Scene' (scene)
10:17:51.268: - scene 'Singers SL':
10:17:51.268:     - source: 'Singers SL Camera' (ndi_source)
10:17:51.268:         - filter: 'Video Delay (Async)' (async_delay_filter)
10:17:51.268:     - source: 'Graphics Scene' (scene)
10:17:51.268: - scene 'Band SL':
10:17:51.268:     - source: 'Band SL Camera' (ndi_source)
10:17:51.268:         - filter: 'Video Delay (Async)' (async_delay_filter)
10:17:51.268:     - source: 'Graphics Scene' (scene)
10:17:51.268: - scene 'Main':
10:17:51.268:     - source: 'AverMedia' (dshow_input)
10:17:51.268:         - filter: 'Color Correction' (color_filter)
10:17:51.268:         - filter: 'Video Delay (Async)' (async_delay_filter)
10:17:51.268:     - source: 'Graphics Scene' (scene)
10:17:51.268: - scene 'Song Worship':
10:17:51.268:     - source: 'AverMedia' (dshow_input)
10:17:51.268:         - filter: 'Color Correction' (color_filter)
10:17:51.268:         - filter: 'Video Delay (Async)' (async_delay_filter)
10:17:51.268:     - source: 'Graphics Scene' (scene)
10:17:51.268: - scene 'Graphics Scene':
10:17:51.268:     - source: 'Pointe Church Logo Tag' (image_source)
10:17:51.268:         - filter: 'Color Correction' (color_filter)
10:17:51.268:     - source: 'Lyric Scene' (scene)
10:17:51.268:     - source: 'Zoom H6' (wasapi_input_capture)
10:17:51.268:         - filter: 'Limiter' (limiter_filter)
10:17:51.268: - scene 'SlidesScene':
10:17:51.268:     - source: 'Graphics Scene' (scene)
10:17:51.268:     - source: 'Slides' (ndi_source)
10:17:51.268:         - filter: 'obs-ndi - Fix alpha blending' (premultiplied_alpha_filter)
10:17:51.268: - scene 'Lyric Scene':
10:17:51.268:     - source: 'Lyrics' (ndi_source)
10:17:51.268:         - filter: 'obs-ndi - Fix alpha blending' (premultiplied_alpha_filter)
10:17:51.268: - scene 'Church Logo':
10:17:51.268:     - source: 'Pointe Church Logo Full' (image_source)
10:17:51.268: - scene 'Switcher':
10:17:51.268:     - source: 'Switcher Source' (decklink-input)
10:17:51.268:     - source: 'Graphics Scene' (scene)
10:17:51.268: ------------------------------------------------
10:17:51.273: [Media Source 'Stinger (2) (Stinger)']: settings:
10:17:51.273: 	input:                   
10:17:51.273: 	input_format:            (null)
10:17:51.273: 	speed:                   100
10:17:51.273: 	is_looping:              no
10:17:51.273: 	is_hw_decoding:          no
10:17:51.273: 	is_clear_on_media_end:   yes
10:17:51.273: 	restart_on_activate:     yes
10:17:51.273: 	close_when_inactive:     no
10:17:51.274: [Media Source 'Stinger (Stinger)']: settings:
10:17:51.274: 	input:                   
10:17:51.274: 	input_format:            (null)
10:17:51.274: 	speed:                   100
10:17:51.274: 	is_looping:              no
10:17:51.274: 	is_hw_decoding:          no
10:17:51.274: 	is_clear_on_media_end:   yes
10:17:51.274: 	restart_on_activate:     yes
10:17:51.274: 	close_when_inactive:     no
10:17:51.369: Switched to Preview/Program mode
10:17:51.369: ------------------------------------------------
10:17:51.479: obs-browser[1]: start loading main frame url 'data:HIDDEN' (transition_type: 1)
10:17:51.484: obs-browser[1]: completed loading main frame url 'data:HIDDEN' (HTTP status code: 200)
10:17:52.251: warning: deprecated pixel format used, make sure you did set range correctly
10:17:52.252: warning: Warning: data is not aligned! This can lead to a speed loss
10:17:52.586: ---------------------------------
10:17:52.586: [DShow Device: 'AverMedia'] settings updated: 
10:17:52.586: 	video device: Live Gamer ULTRA Stream_Engine - 1
10:17:52.586: 	video path: 
10:17:52.586: 	resolution: 1920x1080
10:17:52.586: 	flip: 0
10:17:52.586: 	fps: 60.00 (interval: 166666)
10:17:52.586: 	format: YUY2
10:17:52.758: obs-browser[1]: start loading main frame url 'https://obs.streamelements.com/welcome' (transition_type: 40000000)
10:17:52.843: obs-browser[1]: CONSOLE: OBSLive: getUserData: no user token available (source: https://d33wubrfki0l68.cloudfront.net/js/3a157794cc2df40e3727eb56d937f753be00be71/yoink/static/obs-live.bundle.c31af00a.js:1)
10:17:52.870: obs-browser[1]: API: posting call to 'getHostProperties', callback id 1, args: []
10:17:52.870: obs-browser[1]: API: performing call to 'getHostProperties', callback id 1
10:17:52.871: obs-browser[1]: API: completed call to 'getHostProperties', callback id 1
10:17:52.872: obs-browser[1]: API: posting call to 'getHostProperties', callback id 2, args: []
10:17:52.872: obs-browser[1]: API: performing call to 'getHostProperties', callback id 2
10:17:52.872: obs-browser[1]: API: completed call to 'getHostProperties', callback id 2
10:17:52.910: obs-browser[1]: CONSOLE: checkMinimumMajorVersion:  (source: https://d33wubrfki0l68.cloudfront.net/js/3a157794cc2df40e3727eb56d937f753be00be71/yoink/static/obs-live.bundle.c31af00a.js:1)
10:17:52.910: obs-browser[1]: API: posting call to 'getHostReleaseGroupProperties', callback id 3, args: []
10:17:52.910: obs-browser[1]: API: performing call to 'getHostReleaseGroupProperties', callback id 3
10:17:52.910: obs-browser[1]: API: completed call to 'getHostReleaseGroupProperties', callback id 3
10:17:52.927: obs-browser[1]: API: posting call to 'getHostProperties', callback id 4, args: []
10:17:52.928: obs-browser[1]: API: performing call to 'getHostProperties', callback id 4
10:17:52.928: obs-browser[1]: API: completed call to 'getHostProperties', callback id 4
10:17:52.948: obs-browser[1]: CONSOLE: checkMinimumMinorVersion:  (source: https://d33wubrfki0l68.cloudfront.net/js/3a157794cc2df40e3727eb56d937f753be00be71/yoink/static/obs-live.bundle.c31af00a.js:1)
10:17:53.167: obs-browser[1]: completed loading main frame url 'https://obs.streamelements.com/welcome' (HTTP status code: 200)
10:17:53.306: A sprite cannot be drawn without a width/height
...
10:17:53.806: A sprite cannot be drawn without a width/height
10:17:54.239: Last log entry repeated for 25 more lines
10:17:54.240: obs-browser[1]: API: posting call to 'hideCentralWidget', callback id 5, args: []
10:17:54.240: A sprite cannot be drawn without a width/height
10:17:54.240: obs-browser[1]: API: performing call to 'hideCentralWidget', callback id 5
10:17:54.256: A sprite cannot be drawn without a width/height
10:17:54.273: A sprite cannot be drawn without a width/height
10:17:54.278: obs-browser[1]: API: completed call to 'hideCentralWidget', callback id 5
10:17:54.279: obs-browser[1]: CONSOLE: Continuing to use OBS without logging in (source: https://d33wubrfki0l68.cloudfront.net/js/3a157794cc2df40e3727eb56d937f753be00be71/yoink/static/obs-live.bundle.c31af00a.js:1)
10:17:54.290: A sprite cannot be drawn without a width/height
...
10:17:54.540: A sprite cannot be drawn without a width/height
10:17:57.525: Last log entry repeated for 359 more lines
10:17:57.525: User switched to scene 'Main'
10:17:57.540: A sprite cannot be drawn without a width/height
...
10:17:57.790: A sprite cannot be drawn without a width/height
10:17:58.885: Last log entry repeated for 70 more lines
10:17:58.885: User switched to scene 'Drum Scene'
10:17:58.890: A sprite cannot be drawn without a width/height
10:17:58.891: A sprite cannot be drawn without a width/height
...
10:17:59.140: A sprite cannot be drawn without a width/height
10:17:59.786: Last log entry repeated for 77 more lines
10:17:59.787: User switched to scene 'Singers SR'
10:17:59.790: A sprite cannot be drawn without a width/height
...
10:18:00.040: A sprite cannot be drawn without a width/height
10:18:00.144: Last log entry repeated for 13 more lines
10:18:00.144: User switched to scene 'Singers SL'
10:18:00.156: A sprite cannot be drawn without a width/height
10:18:00.157: A sprite cannot be drawn without a width/height
...
10:18:00.390: A sprite cannot be drawn without a width/height
10:18:00.391: A sprite cannot be drawn without a width/height
10:18:00.406: A sprite cannot be drawn without a width/height
10:18:00.408: Last log entry repeated for 1 more lines
10:18:00.408: User switched to scene 'Band SL'
10:18:00.423: A sprite cannot be drawn without a width/height
...
10:18:00.673: A sprite cannot be drawn without a width/height
10:18:00.896: Last log entry repeated for 27 more lines
10:18:00.896: User switched to scene 'Main'
10:18:00.906: A sprite cannot be drawn without a width/height
...
10:18:01.390: A sprite cannot be drawn without a width/height
10:18:01.400: User switched to scene 'Band SL'
10:18:01.406: A sprite cannot be drawn without a width/height
...
10:18:01.656: A sprite cannot be drawn without a width/height
10:18:01.844: Last log entry repeated for 23 more lines
10:18:01.844: User switched to scene 'Singers SL'
10:18:01.856: A sprite cannot be drawn without a width/height
...
10:18:02.006: A sprite cannot be drawn without a width/height
10:18:02.020: User switched to scene 'Singers SR'
10:18:02.023: A sprite cannot be drawn without a width/height
10:18:02.024: A sprite cannot be drawn without a width/height
...
10:18:02.223: A sprite cannot be drawn without a width/height
10:18:02.224: User switched to scene 'Drum Scene'
10:18:02.224: A sprite cannot be drawn without a width/height
...
10:18:02.474: A sprite cannot be drawn without a width/height
10:19:02.092: Last log entry repeated for 7154 more lines
10:19:02.092: User switched to scene 'Singers SR'
10:19:02.106: A sprite cannot be drawn without a width/height
10:19:02.106: A sprite cannot be drawn without a width/height
...
10:19:02.356: A sprite cannot be drawn without a width/height
10:19:03.451: Last log entry repeated for 131 more lines
10:19:03.451: User switched to scene 'Singers SL'
10:19:03.456: A sprite cannot be drawn without a width/height
...
10:19:03.706: A sprite cannot be drawn without a width/height
10:19:04.741: Last log entry repeated for 125 more lines
10:19:04.742: User switched to scene 'Band SL'
10:19:04.756: A sprite cannot be drawn without a width/height
10:19:04.756: A sprite cannot be drawn without a width/height
...
10:19:05.006: A sprite cannot be drawn without a width/height
10:19:08.492: Last log entry repeated for 419 more lines
10:19:08.492: User switched to scene 'Main'
10:19:08.506: A sprite cannot be drawn without a width/height
10:19:08.523: A sprite cannot be drawn without a width/height
...
10:19:08.990: A sprite cannot be drawn without a width/height
10:19:09.006: A sprite cannot be drawn without a width/height
10:19:10.347: Last log entry repeated for 80 more lines
10:19:10.347: User switched to scene 'Band SL'
10:19:10.356: A sprite cannot be drawn without a width/height
10:19:10.357: A sprite cannot be drawn without a width/height
...
10:19:10.591: A sprite cannot be drawn without a width/height
10:19:10.606: A sprite cannot be drawn without a width/height
10:19:11.428: Last log entry repeated for 99 more lines
10:19:11.428: User switched to scene 'Drum Scene'
10:19:11.440: A sprite cannot be drawn without a width/height
10:19:11.440: A sprite cannot be drawn without a width/height
...
10:19:11.690: A sprite cannot be drawn without a width/height
10:19:19.554: Last log entry repeated for 1118 more lines
10:19:19.554: User removed filter 'Video Delay (Async)' (async_delay_filter) from source 'Drum Camera'
10:19:23.518: User switched to scene 'Singers SR'
10:19:23.525: A sprite cannot be drawn without a width/height
10:19:23.540: A sprite cannot be drawn without a width/height
...
10:19:24.025: A sprite cannot be drawn without a width/height
10:19:34.661: Last log entry repeated for 1003 more lines
10:19:34.661: User removed filter 'Video Delay (Async)' (async_delay_filter) from source 'Singers SR Camera'
10:19:34.673: A sprite cannot be drawn without a width/height
...
10:19:34.741: A sprite cannot be drawn without a width/height
10:19:34.742: A sprite cannot be drawn without a width/height
10:19:37.960: User switched to scene 'Singers SL'
10:19:37.973: A sprite cannot be drawn without a width/height
...
10:19:38.473: A sprite cannot be drawn without a width/height
10:19:44.882: Last log entry repeated for 589 more lines
10:19:44.882: User removed filter 'Video Delay (Async)' (async_delay_filter) from source 'Singers SL Camera'
10:19:44.891: A sprite cannot be drawn without a width/height
10:19:44.891: A sprite cannot be drawn without a width/height
10:19:50.379: User switched to scene 'Band SL'
10:19:50.390: A sprite cannot be drawn without a width/height
10:19:50.406: A sprite cannot be drawn without a width/height
...
10:19:50.890: A sprite cannot be drawn without a width/height
10:20:01.178: Last log entry repeated for 567 more lines
10:20:01.178: User switched to scene 'Singers SL'
10:20:10.558: User added filter 'Video Delay (Async)' (async_delay_filter) to source 'Singers SL Camera'
10:20:17.119: User switched to scene 'Singers SR'
10:20:18.234: User switched to scene 'Singers SL'
10:20:27.512: User switched to scene 'Singers SR'
10:20:30.052: User switched to scene 'Drum Scene'
10:20:39.717: User added filter 'Video Delay (Async)' (async_delay_filter) to source 'Drum Camera'
10:20:47.981: User switched to scene 'Singers SR'
10:20:58.352: User added filter 'Video Delay (Async)' (async_delay_filter) to source 'Singers SR Camera'
10:21:05.337: User switched to scene 'Drum Scene'
10:21:12.686: User switched to scene 'Singers SR'
10:21:19.513: User switched to scene 'Singers SL'
10:21:27.706: User switched to scene 'Band SL'
10:21:38.103: User switched to scene 'Main'
10:21:39.582: User switched to scene 'Band SL'
10:21:49.165: User switched to scene 'Singers SL'
10:21:56.256: User switched to scene 'Singers SR'
10:22:03.710: User switched to scene 'Drum Scene'
10:22:19.095: User switched to scene 'Main'
10:22:33.664: User switched to scene 'SlidesScene'
10:22:33.694: A sprite cannot be drawn without a width/height
10:23:17.956: User switched to scene 'Drum Scene'
10:23:19.494: User switched to scene 'Singers SR'
10:23:20.784: User switched to scene 'Singers SL'
10:23:22.061: User switched to scene 'Band SL'
10:23:23.416: User switched to scene 'Main'
10:23:25.075: User switched to scene 'Graphics Scene'
10:23:26.379: User switched to scene 'Singers SR'
10:23:50.730: User switched to scene 'SlidesScene'
10:23:54.968: User switched to scene 'Drum Scene'
10:23:59.441: obs-browser: streaming start requested by UI control
10:24:02.307: [jim-nvenc: 'streaming_h264'] settings:
10:24:02.307: 	rate_control: CBR
10:24:02.307: 	bitrate:      5000
10:24:02.307: 	cqp:          20
10:24:02.307: 	keyint:       120
10:24:02.307: 	preset:       mq
10:24:02.307: 	profile:      high
10:24:02.307: 	width:        1280
10:24:02.307: 	height:       720
10:24:02.307: 	2-pass:       true
10:24:02.307: 	b-frames:     2
10:24:02.307: 	lookahead:    false
10:24:02.307: 	psycho_aq:    true
10:24:02.307: 
10:24:02.357: ---------------------------------
10:24:02.360: [FFmpeg aac encoder: 'avc_aac_stream'] bitrate: 128, channels: 2, channel_layout: 3
10:24:02.360: 
10:24:02.369: [rtmp stream: 'adv_stream'] Dynamic bitrate enabled.  Dropped frames begone!
10:24:02.369: [rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmp://mi.castr.io/static...
10:24:02.428: [rtmp stream: 'adv_stream'] Interface: Realtek PCIe GbE Family Controller (ethernet, 1000 mbps)
10:24:02.492: [jim-nvenc: 'recording_h264'] settings:
10:24:02.492: 	rate_control: CQP
10:24:02.492: 	bitrate:      0
10:24:02.492: 	cqp:          15
10:24:02.492: 	keyint:       120
10:24:02.492: 	preset:       mq
10:24:02.492: 	profile:      high
10:24:02.492: 	width:        1280
10:24:02.492: 	height:       720
10:24:02.492: 	2-pass:       true
10:24:02.492: 	b-frames:     2
10:24:02.492: 	lookahead:    true
10:24:02.492: 	psycho_aq:    true
10:24:02.492: 
10:24:02.557: ---------------------------------
10:24:02.558: [FFmpeg aac encoder: 'Track1'] bitrate: 128, channels: 2, channel_layout: 3
10:24:02.558: 
10:24:02.617: ==== Recording Start ===============================================
10:24:02.617: [ffmpeg muxer: 'adv_file_output'] Writing file 'C:/Users/Devo/Videos/2020-05-03 10-24-02.mkv'...
10:24:03.223: [rtmp stream: 'adv_stream'] Connection to rtmp://mi.castr.io/static successful
10:24:03.226: ==== Streaming Start ===============================================

**Comment by Cows2Computers** [comment]
We got a crash as well when applying the 'Video Delay (Async)' (async_delay_filter) to an NDI feed coming from ProPresentor running on a another computer, but only when a video is sent over the feed (it does not crash when just sending a text overlay with an alpha background). 

Crash dump available if helpful.

**Comment by nottooloud** [comment]
I see this black screen or a frozen screen after adding the async delay if I have Sync set to the new default of Source.  If I switch Sync to Network, I get the picture back.

**Comment by Trouffman** [comment]
Closing this issue as it is old/not been updated/expired and most- likely fixed in more recent version.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.
