### ISSUE TITLE
"NDI Output Settings" Not showing up on main rig

### ISSUE THREAD

**Issue by porkyqkr** [obs-ndi/obs-ndi#471]
Running an AMD FX-8350 which according to CPUworld, has SSSE3. 

OBS v25.0.8
Downloaded the most recent NDI v4.9.0 and followed the exact same steps that I did on my second computer, which has no problems and shows the dropdown option in OBS. 

I'll attach the log files from OBS but I don't see anything for NDI in there. 

[2020-05-04 14-33-53.txt](https://github.com/Palakis/obs-ndi/files/4576996/2020-05-04.14-33-53.txt)

**Comment by dinizmauricio** [comment]
The same happens to me.
I'm using:
Windows 10
obs-ndi 4.9.0
OBS 25.0.8

**Comment by paulpv** [comment]
Closing due release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
