### ISSUE TITLE
PopOS obs-ndi build ... "cannot find -lobs-frontend-api"

### ISSUE THREAD

**Issue by PaulsTek** [obs-ndi/obs-ndi#475]
??? almost completed build, but cannot find "-lobs-frontend-api" ... is there a typo (should be -libs)?

 ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/af5bv/obs-ndi/build
af5bv@pop-os:~/obs-ndi/build$ make -j4
[  8%] Automatic MOC and UIC for target obs-ndi
[  8%] Built target obs-ndi_autogen
Scanning dependencies of target obs-ndi
[ 16%] Building CXX object CMakeFiles/obs-ndi.dir/obs-ndi_autogen/mocs_compilation.cpp.o
[ 33%] Building CXX object CMakeFiles/obs-ndi.dir/src/obs-ndi-output.cpp.o
[ 33%] Building CXX object CMakeFiles/obs-ndi.dir/src/obs-ndi-source.cpp.o
[ 41%] Building CXX object CMakeFiles/obs-ndi.dir/src/obs-ndi.cpp.o
[ 50%] Building CXX object CMakeFiles/obs-ndi.dir/src/obs-ndi-filter.cpp.o
[ 58%] Building CXX object CMakeFiles/obs-ndi.dir/src/premultiplied-alpha-filter.cpp.o
[ 66%] Building CXX object CMakeFiles/obs-ndi.dir/src/main-output.cpp.o
[ 75%] Building CXX object CMakeFiles/obs-ndi.dir/src/preview-output.cpp.o
[ 83%] Building CXX object CMakeFiles/obs-ndi.dir/src/Config.cpp.o
[ 91%] Building CXX object CMakeFiles/obs-ndi.dir/src/forms/output-settings.cpp.o
[100%] Linking CXX shared module obs-ndi.so
/usr/bin/ld: cannot find -lobs-frontend-api
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/obs-ndi.dir/build.make:223: obs-ndi.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/obs-ndi.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by walterav1984** [comment]
Does this help #115, and are you sure you use a recent obs-studio lib source to satify `-DLIBOBS_INCLUDE_DIR=`?

**Comment by tt2468** [comment]
This likely means that the installed version of OBS differs from the version you linked to with cmake. Is your OBS install built or installed with a package maintainer?

**Comment by paulpv** [comment]
The build has changed a lot in over 3 years.
Closing, but you can reopen if it is still a problem.
