### ISSUE TITLE
obs-ndi ver 4.9.1 ver check incorrect

### ISSUE THREAD

**Issue by like-magic** [obs-ndi/obs-ndi#497]
Ubuntu 20.04

sudo apt install ./Downloads/obs-ndi_4.9.1-1_amd64.deb 
[sudo] password for administrator: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'obs-ndi' instead of './Downloads/obs-ndi_4.9.1-1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 obs-ndi : Depends: obs-studio (>= 25.0.7) but 25.0.3+dfsg1-2 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by like-magic** [comment]
from the about
![image](https://user-images.githubusercontent.com/65107924/82110664-0ac72a00-9794-11ea-9ff3-546f5b6faae5.png)

**Comment by walterav1984** [comment]
Remove prior "obs-ndi" packages and "obs-studio" from the ubuntu apt repository:
`sudo apt -y remove obs-ndi obs-studio obs-plugins libobs0`

Install [PPA](https://obsproject.com/wiki/install-instructions#linux) version of obs-studio so the version will be higher than 25.07, this will only work if you have "libobs0" removed.

Install Palakis deb packages:
`sudo dpkg -i ~/Downloads/libndi4_4.5.1-1_amd64.deb`
`sudo dpkg -i ~/Downloads/obs-ndi_4.9.1-1_amd64.deb`

**Comment by like-magic** [comment]
this appeared to work but I still don't appear to have ndi.
OBS log file:
21:57:19.007: CPU Name: AMD Athlon(tm) II X4 645 Processor
21:57:19.007: CPU Speed: 3100.000MHz
21:57:19.007: Physical Cores: 4, Logical Cores: 4
21:57:19.007: Physical Memory: 16011MB Total, 11366MB Free
21:57:19.007: Kernel Version: Linux 5.4.0-29-generic
21:57:19.007: Distribution: "Ubuntu Core" "18"
21:57:19.008: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
21:57:19.011: Portable mode: false
21:57:19.078: OBS 25.0.8-modified (linux)
21:57:19.078: ---------------------------------
21:57:19.079: ---------------------------------
21:57:19.079: audio settings reset:
21:57:19.079: 	samples per sec: 44100
21:57:19.079: 	speakers:        2
21:57:19.094: ---------------------------------
21:57:19.094: Initializing OpenGL...
21:57:19.265: Loading up OpenGL on adapter X.Org AMD NAVI10 (DRM 3.35.0, 5.4.0-29-generic, LLVM 9.0.0)
21:57:19.265: OpenGL loaded successfully, version 4.5 (Core Profile) Mesa 19.2.8, shading language 4.50
21:57:19.285: ---------------------------------
21:57:19.285: video settings reset:
21:57:19.285: 	base resolution:   1920x1080
21:57:19.285: 	output resolution: 1280x720
21:57:19.285: 	downscale filter:  Bicubic
21:57:19.285: 	fps:               30/1
21:57:19.285: 	format:            NV12
21:57:19.285: 	YUV mode:          601/Partial
21:57:19.285: NV12 texture support not available
21:57:19.291: Audio monitoring device:
21:57:19.291: 	name: Default
21:57:19.291: 	id: default
21:57:19.292: ---------------------------------
21:57:19.302: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
21:57:19.507: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
21:57:19.507: No blackmagic support
21:57:19.517: [obs-browser]: Version 2.8.6
21:57:19.525: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory
21:57:19.525: 
21:57:19.526: FFMPEG VAAPI supported
21:57:19.541: [obs-websocket] you can haz websockets (version 4.7.0)
21:57:19.541: [obs-websocket] qt version (compile-time): 5.9.5 ; qt version (run-time): 5.9.5
21:57:19.568: [obs-websocket] module loaded!
21:57:19.580: VLC found, VLC video source enabled
21:57:19.580: ---------------------------------
21:57:19.580:   Loaded Modules:
21:57:19.580:     vlc-video.so
21:57:19.580:     v4l2sink.so
21:57:19.580:     text-freetype2.so
21:57:19.580:     rtmp-services.so
21:57:19.580:     obs-x264.so
21:57:19.580:     obs-websocket.so
21:57:19.580:     obs-transitions.so
21:57:19.580:     obs-outputs.so
21:57:19.580:     obs-libfdk.so
21:57:19.580:     obs-filters.so
21:57:19.580:     obs-ffmpeg.so
21:57:19.581:     obs-browser.so
21:57:19.581:     linux-v4l2.so
21:57:19.581:     linux-pulseaudio.so
21:57:19.581:     linux-jack.so
21:57:19.581:     linux-decklink.so
21:57:19.581:     linux-capture.so
21:57:19.581:     linux-alsa.so
21:57:19.581:     image-source.so
21:57:19.581:     frontend-tools.so
21:57:19.581:     decklink-ouput-ui.so
21:57:19.581:     advanced-scene-switcher.so
21:57:19.581: ---------------------------------
21:57:19.581: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): ../obs-plugins/obs-browser.so: cannot open shared object file: No such file or directory
21:57:19.581: 
21:57:19.581: ==== Startup complete ===============================================
21:57:19.583: Service '' not found
21:57:19.586: All scene data cleared
21:57:19.586: ------------------------------------------------
21:57:19.591: pulse-input: Server name: 'pulseaudio 13.99.1'
21:57:19.591: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
21:57:19.592: pulse-input: Started recording from 'alsa_output.usb-Logitech_Logitech_H360_Headset-00.analog-stereo.monitor'
21:57:19.594: [Loaded global audio device]: 'Desktop Audio'
21:57:19.595: pulse-input: Server name: 'pulseaudio 13.99.1'
21:57:19.598: pulse-input: Audio format: s16le, 44100 Hz, 1 channels
21:57:19.599: pulse-input: Started recording from 'alsa_input.usb-Logitech_Logitech_H360_Headset-00.mono-fallback'
21:57:19.605: pulse-am: Server name: 'pulseaudio 13.99.1'
21:57:19.605: pulse-am: Audio format: s16le, 44100 Hz, 2 channels
21:57:19.606: pulse-am: Started Monitoring in 'alsa_output.usb-Logitech_Logitech_H360_Headset-00.analog-stereo.monitor'
21:57:19.606: [Loaded global audio device]: 'Mic/Aux'
21:57:19.608: [Media Source 'Axis213PTZ']: settings:
21:57:19.608: 	input:                   rtsp://192.168.0.10/mpeg4/media.amp
21:57:19.608: 	input_format:            
21:57:19.608: 	speed:                   100
21:57:19.608: 	is_looping:              no
21:57:19.608: 	is_hw_decoding:          yes
21:57:19.608: 	is_clear_on_media_end:   yes
21:57:19.608: 	restart_on_activate:     yes
21:57:19.608: 	close_when_inactive:     yes
21:57:19.610: Switched to scene 'Scene'
21:57:19.611: ------------------------------------------------
21:57:19.611: Loaded scenes:
21:57:19.611: - scene 'Scene':
21:57:19.611:     - source: 'Axis213PTZ' (ffmpeg_source)
21:57:19.611: - scene 'default':
21:57:19.611:     - source: 'Axis213PTZ' (ffmpeg_source)
21:57:19.611: ------------------------------------------------
21:57:19.854: Switched to Preview/Program mode
21:57:19.854: ------------------------------------------------
21:57:19.860: [obs-websocket] server started successfully on port 4444
21:57:19.860: [obs-websocket] io thread started
21:57:22.144: adding 0 milliseconds of audio buffering, total audio buffering is now 0 milliseconds (source: Desktop Audio)
21:57:22.144: 
21:57:22.168: adding 23 milliseconds of audio buffering, total audio buffering is now 23 milliseconds (source: Desktop Audio)

**Comment by like-magic** [comment]
Found it , two icons on start menu, **obs** does not have plug in, **obs studio** does have plug in

**Comment by like-magic** [comment]
playing with ndi and obs studio crashed and would not restart. Uninstalled everything. reinstalled still crashing. 
Uninstalled everything obs-studio, obs-ndi, libndi
Manually remove remnants in the /usr directories of obs, obs-studio, obs-ndi and libndi. files and links.
reinstalled obs-studio and test ok
reinstalled libndi then obs-ndi
run obs-studio - complained it could not find ndi 

from the obs-studio log
17:14:13.380: [obs-ndi] hello ! (version 4.9.1)
17:14:13.380: [obs-ndi] Trying ''
17:14:13.380: [obs-ndi] Trying '/usr/lib'
17:14:13.380: [obs-ndi] Trying '/usr/local/lib'
17:14:13.380: [obs-ndi] Can't find the NDI library
17:14:25.302: Failed to initialize module 'obs-ndi.so'

**Comment by paulpv** [comment]
Closing due release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
