### ISSUE TITLE
OBS NDI Plugin Not Showing Up in OBS Tools Menu

### ISSUE THREAD

**Issue by hbfc** [obs-ndi/obs-ndi#500]
Hello and thank you in advance for your help!

I have installed OBS NDI Plugin on my HP Omen Obelisk desktop computer and used it successfully with OBS. I built a new computer specifically for video production and when I tried to install OBS NDI, it installs successfully but doesn't appear in the OBS Tools menu. I have done a few uninstall/reinstalls and have had no luck. When researching the problem, I read that a few years ago people were having issues with older AMD processors that did not have SSSE3 compatibility. I found that my processor has that compatibility, but I still cannot figure out how to make it work.

AMD Ryzen 9 3950X
Aorus 570X Master Motherboard
Ripjaws V 32GB (2 x 16GB)
Windows 10 Pro
OBS Studio 25.0.8
NDI Plugin 4.9.0

Does anyone know how to fix this? Will I have to rebuild my computer and use an Intel chip? I need NDI for my video productions, so I will do what I must. Let me know if there is any other information that I did not include that may help you diagnose the problem.

Thank you so much!

**Comment by dioleev** [comment]
Same issue.
OBS 26.1
NDI 4.9
Help.

**Comment by paulpv** [comment]
Is this still an issue in 4.13.0?

**Comment by paulpv** [comment]
Closing due to no response
