### ISSUE TITLE
Increasing latency until I-frames start dropping (4.9+)

### ISSUE THREAD

**Issue by omegahacker** [obs-ndi/obs-ndi#502]
I've been fighting with 4.9.x for a while now, and somebody in the forums said they had the same problem that was solved by backing off to 4.8.0, which I verified does resolve the issue.

The problem is when I try to bring a PTZOptics NDI-HX camera into OBS (nothing else).  If I view the camera feed with the NDI Tools Monitor, it works exactly as intended.  However, as soon as I start OBS (Win 10, OBS 25.something), the video is already about 500ms or more delayed, rather than the (guessing) 50-100ms that's inherent to the protocol.  Within about 30 seconds that delay progressively grows to almost 2 seconds, at which point the video starts dropping I-frames.  This can manifest as just black flashes in the video, or it can actually hold those black frames as reference and show motion compensation differences against them for ~500ms until the next I-frame.

The *really* strange part is that this would happen 100% of the time when the gear was at church where it's supposed to be, but wouldn't happen at home, until yesterday for no obvious reason.  That part I'm still very puzzled by.

It feels like there's a core issue with clock synchronization introduced into 4.9.x, but I don't know how the code is structured so until/unless I have a chance to look at it and the diffs I can't be sure.

**Comment by omegahacker** [comment]
I took a quick look at the diff between 4.8.0 and 4.9.1, and the only code change is the removal of "Internal" sync mode vs. NDI source-timecode.  My assumption then is that there's something wrong with the source-timecode sync that causes this problem.  Is there a verbose flag or debug build I can run on my configuration that would provide the necessary frame sync and timing information to help track down this issue?

**Comment by omegahacker** [comment]
I tried to set up the kit today, and even with 4.8.0 I'm getting the steadily increasing latency.  I started to suspect the camera settings (PTZoptics 30x-NDI) and did some further tests.

With the NewTek NDI camera app on my iphone, and both the NDI Monitor and the OBS screen showing at the same time, I get slightly delayed but consistent video.  If I switch both programs over to the PTZoptics camera, I get realtime display on the NDI Monitor, but a massively delayed output from OBS.

I'm going to poke around more at the settings in the PTZoptics camera, and also email them specifically, to see if I can figure out what's going on here....

**Comment by jgwhitebeard** [comment]
Thanks omega hacker for starting to work this through. I am seeing the same increasing latency issue with 4.8.0 and 4.9.0 using NDI-HX iOS app cameras.

Disabling and re-enabling the feed using the blue NDI button resets the latency to its minimum. Alternatively you can open the NDI source options menu and close it without changing anything. Both cause a break in the feed - so I do this when I cut away to another source.

The issue appears to get much worse when the graphics card memory is used up and it starts offloading to RAM. With 4GB, I can run 5 cameras, 2 at 4k and 3 at 1080 with memory to spare but do still get the increased latency sometimes. You can use the "unload file when not in use" option to save video card memory. I can see no perceptible difference in playback startup time with this checked.

I think I've managed to reduce the latency creep too by switching to a dedicated Intel NIC and have turned off flow control, interrupt moderation and all off-loading. Some of my iOS devices are on wifi others on wired NICs. Creeping latency happens to both, the only thing that varies is the minimum, with wifi a little longer.

It looks like the NDI spec allows for timecode in the audio feed. I've tried with the NDI HX audio enabled and disabled (I don't need it) but it makes no difference as far as I can tell. Does anyone know a way of syncing all my NDI HX iOS app cameras? I don't care what the latency is, as long is it stays the same!

Happy to run test on my rig if anyone can suggest something to get to the bottom of this.

**Comment by paulpv** [comment]
Is this still an issue in 4.13.0?

Try using "A/V Sync: Network" instead of the default "Source".

**Comment by paulpv** [comment]
Closing due to no response
