### ISSUE TITLE
Can't open NDI plugin on MacOS - where is it?

### ISSUE THREAD

**Issue by funktype** [obs-ndi/obs-ndi#503]
Read through other issues but can't seem to find the exact one.
Running Mac OS 10.14.5
OBS 25.0.6
Installed NDI 4.5.1 (so I thought), and it appeared to install correctly,

yet when I go to OBS and try to add source, NDI is not an option.
NDI is running on iPhone, and I can see myself. 
Both phone and computer are on the same wifi network.

Computer has been restarted. 
What else needs to be done?
Is there a file I manually need to drag into the contents or Plugins folder for OBS?

**Comment by 360disrupt** [comment]
The installation description is a bit confusing. I managed to install it by:

1. Download and run obs-ndi-4.8.0-macOS.pkg (provided below)
2. Install the NDI 4.5.1 macOS runtime using the installer provided here: https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg
3. Install the package below: https://github.com/Palakis/obs-ndi/releases/download/4.8.0/obs-ndi-4.8.0-macOS.pkg

**Comment by amigasteve** [comment]
@360disrupt, thank you for that. That last package was the missing piece I was looking for!

**Comment by surajmanittt** [comment]
I have installed   
https://github.com/Palakis/obs-ndi/releases/download/4.8.0/obs-ndi-4.8.0-macOS.pkg
&
https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg

both installed successfully. but i can find the ndi source on obs 25.0.8

pls help

**Comment by surajmanittt** [comment]
it started working. i think it was the simple step of switching off obs after the installs. and then suddenly, it was in the source

**Comment by ifuchs** [comment]
Trying to do the installs but this link: https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg no longer works. Is there another source for this file?

**Comment by devsparkles** [comment]
Where is this file

**Comment by 360disrupt** [comment]
Haven't checked for the exact files, but I found both here with the last release:
https://github.com/Palakis/obs-ndi/releases

**Comment by Brayyy** [comment]
Despite installing ndi-runtime-5.0.10.1-macOS.pkg and obs-ndi-4.9.0-macOS.pkg, I had a similar issue, with OBS failing with "NDI™ Runtime not found", logs showing:

```
21:13:24.032: [obs-ndi] hello ! (version 4.9.0)
21:13:24.032: [obs-ndi] Trying ''
21:13:24.032: [obs-ndi] Trying '/usr/lib'
21:13:24.032: [obs-ndi] Trying '/usr/local/lib'
21:13:24.032: [obs-ndi] Can't find the NDI library
21:13:25.625: Failed to initialize module 'obs-ndi.so'
```

I was able to resolve my problems by copying the dylib file to the file OBS is seeking.

```
cp /usr/local/lib/libndi.dylib /usr/local/lib/libndi.4.dylib
```

**Comment by linkwithjoydeep** [comment]
A little late but the solution here worked for me: https://obsproject.com/forum/threads/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.69240/page-41

**Comment by paulpv** [comment]
Closing due to release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
