### ISSUE TITLE
Wont install in 25.0.8, cause it requieres >=25.0.7?

### ISSUE THREAD

**Issue by jzayas7** [obs-ndi/obs-ndi#504]
Just downloaded OBS (from Pop OS! shop) on its 25.0.8 version, and tried to install NDI package, but in wont complete because its asking for 25.0.7 or higher, which i suposse to have. What can i do?

**Comment by PatrickLohan** [comment]
Try the OBS PPA from their website. Installed fine but no signal on streaming pc's obs. 

If you got it running do you mind sharing the steps you took please?

**Comment by jamievander73** [comment]
bump  (why would installing from a ppa give you an older version?) ndi peeps need to upgrade to the upgrade I guess. I couldn't find any older versions of obs for download.

**Comment by jzayas7** [comment]
I actually upgraded the SO and that fixed the issue, thanks.
