### ISSUE TITLE
Virus alert for installer

### ISSUE THREAD

**Issue by bkrajendra** [obs-ndi/obs-ndi#507]
VirusTotal shows infection report by 4 engines for windows installer: obs-ndi-4.9.0-Windows-Installer.msi

https://www.virustotal.com/gui/file/b024f933dc1e5298543ca06e443b5d37231e204affae7fb520155e0933801630/detection

Please check whats the issue.

**Comment by walterav1984** [comment]
Duplicate #455

**Comment by paulpv** [comment]
4 engines, 3 engines, or 2? :)
![image](https://user-images.githubusercontent.com/1393897/224405635-c73d9a71-b25b-45ed-bae0-0d62800271c2.png)

No real idea why they are complaining.

Still closing this to be tracked by #455
