### ISSUE TITLE
After win 10 is updated to version 2004, two computers cannot use NDI to capture the display of another computer

### ISSUE THREAD

**Issue by qzcaoyou** [obs-ndi/obs-ndi#513]
After win 10 is updated to version 2004, two computers cannot use NDI to capture the display of another computer

**Comment by matt78373** [comment]
I had this problem also. 

Two PCs and one was Win 10 1909 using scan convertor and a streaming PC Win 10 1909 as well. Everything was working then the streaming PC upgraded to Win 10 2004 and it no longer received NDI signal from the other PC, although I could stream to it from an NDI iOS app. 

I wound up reverting the streaming PC back to Windows 10 1909 to resolve the issue.

**Comment by kleini14** [comment]
oh thats why my OBS-NDI doesnt work anymore. I was watching for 4 hours straight for a fix and here is the reason why.... unfortunatly i cant roll back that easily anymore so im really hoping for a fix either on NDIs site or with Windows itself

**Comment by datacenterdude** [comment]
Can confirm.  Have alerted Palakis via OBS Discord.

**Comment by Aaronstephen** [comment]
Resinstall latest version of this plugin for OBS 26 and reinstall NDI plugins. Open the screen capture NDI tool on the computer you want to capture, the source can now be read from the network on another computer with OBS. Note on the captured computer it is not required to run OBS.

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by paulpv** [comment]
Closing due to no response
