### ISSUE TITLE
NDI-OBS Doesn't work anymore after OS update Mac Catalina 10.15.5

### ISSUE THREAD

**Issue by Tony-Menda** [obs-ndi/obs-ndi#514]
Dear Palakis,

Yesterday I did an OS-update in my Mac mini and after that my NDI input or output didn't work anymore in OBS. I'd tried everything, but no result at all. Is this a bug?

Kind regards,
Tony

**Comment by DJTROUBLE** [comment]
I purchase a new MacBook Pro and I cannot used OBS due to the NDI plugin install is failing. Is there a fix in place for this issue?
Or what do we need to do in order to resolve this issue

**Comment by Orlegi** [comment]
Hi, I'm in the same case. No way to do OBS works with my MacBook with Catalina.
Are there any plan to solve this issue?

**Comment by consciousimages** [comment]
You guys followed the release note instructions and installed NDI manually?

[(https://github.com/Palakis/obs-ndi/releases/tag/4.9.0)]

**Comment by paulpv** [comment]
Closing due to release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
