### ISSUE TITLE
Internal Sync Option missing one one system (available on others)

### ISSUE THREAD

**Issue by versluis** [obs-ndi/obs-ndi#516]
Hello team! I've observed an interesting issue on one of my Z600 workstations: when I pull in a feed from my gaming rig, the internal sync option is missing from the drop down menu in the NDI source. I have two of those as encoding PCs. One system is showing the internal sync, alongside network and source, the other one is only showing network and source but no internal.

Thing is, internal sync appears to be the only way to keep my audio and video in sync. I've tried a complete un-install and re-install of OBS and the plugin, but it's still the same. Hardware wise the systems are identical, except for the GPU (the first one with internal sync showing as a GTX 970, the other one with the missing internal option has two Quadro K4000 cards). 

Let me know if you need any further information. I'm using the Windows 64-bit installer of the 4.9.1 plugin, with OBS 25.0.8.

**Comment by WiredUK** [comment]
Internal sync was removed in a more recent version.

**Comment by paulpv** [comment]
To be precise, Internal sync was removed in https://github.com/obs-ndi/obs-ndi/commit/ccbdf30f4929969fe58ede691b3030d1fc5ef590 on 2020/04/28 and released in 4.9.0.

@versluis must have just had the old version installed.

Closing
