### ISSUE TITLE
Can this output each obs audio track to a different ndi audio channel?

### ISSUE THREAD

**Issue by MiloMindbender** [obs-ndi/obs-ndi#519]
I have several streams of audio/video coming in from different locations.  I put these together into a 4 way split screen like an interview show, then send that video back to each participant so they can hear and see everyone.  Problem is they can hear themselves (As a delayed Echo) too.

I thought the solution would be to put the audio from each incoming feed on a separate track, then send all 4 tracks on the ndi channel along with the video.   Then a participant could listen to just the audio tracks from the other 3 people and Not their own, so they would not hear themselves.

Problem is, it seems like the ndi output only sends obs track 1 and not the others.  Is there a way to get it to send all the tracks?

**Comment by Trouffman** [comment]
On your audio source : Use the filter : "Dedicated NDI® output (Audio Only)"
