### ISSUE TITLE
[MAC] NDI source has been shown on OBS studio, but cannot found the source of game capture device from the NDI source 

### ISSUE THREAD

**Issue by aumaim555** [obs-ndi/obs-ndi#520]
MAC OS Mojave
10.14.6

My OBS studio (streamlab and OBS)
The NDI source has been shown up in the OBS studio, BUT cannot see the OBS link as the option.
![image](https://user-images.githubusercontent.com/67161884/85156883-e378e680-b284-11ea-9167-ca1c7d0ef532.png)

My OBS link preference. also found that the icon does not show as the blue color when compare with the other
![image](https://user-images.githubusercontent.com/67161884/85158244-9b5ac380-b286-11ea-864a-0ae23754bff2.png)

![image](https://user-images.githubusercontent.com/67161884/85157189-58e4b700-b285-11ea-9183-49d262eea03a.png)

game capture device: Elgato

I have installed the NDI below (all shown as install completed)
1. https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg
2. https://github.com/Palakis/obs-ndi/releases/download/4.9.1/obs-ndi-4.9.0-macOS.pkg

I try to do completely install the ndi, BUT CANNOT see the ndi pkg installed here `~/Library/Application Support/obs-studio/plugins/obs-ndi`
Is this possible to be the root cause of this issue?
![image](https://user-images.githubusercontent.com/67161884/85157968-63ec1700-b286-11ea-9485-7dd13f061c04.png)

Can you help check this? Thanks! @Palakis

**Comment by felipemelo86** [comment]
same problem

**Comment by Trouffman** [comment]
This has been assumed to be an issue within OBS link. OBS link is no longer supported by Elgato.
See the official statement at : https://help.elgato.com/hc/en-us/articles/360031363132-OBS-Link-Setup
