### ISSUE TITLE
making nd output settings this causes obs to close v 4.9.0

### ISSUE THREAD

**Issue by Newles** [obs-ndi/obs-ndi#522]
when installing the ndi in obs studio it worked well and everything but when you want to configure to stream with 2 pc at the same time the pc where I am going to broadcast closes the obs and then when you want to open it it goes in a loop and keeps closing it if I remove the libraries from ndi this error is removed, I take day and I CANNOT FIND A SOLUTION TO THIS PROBELAM SO I REPORT IT AS A BUG IS BEING TESTED ON A TEAM WITH WINDOWS 10 OF 64BITS COMP 2004

**Comment by rafaelholeva** [comment]
The same thing happens to me, my friend! However I use windows 7 (x64) here it seems that this problem extends to all versions of windows (x64). You can follow the problem on the OBS forum. I hope someone solves this problem. The problem appears to be with the NDI plugin or the NDI SDK.


Link:  https://obsproject.com/forum/threads/ndi-plugin-error-in-obs-studio-25-0-8-x64.125341/

LINK 2: https://github.com/Palakis/obs-ndi/issues/526

**Comment by paulpv** [comment]
Closing due to release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
