### ISSUE TITLE
Unable to get video/audio through NDI Source

### ISSUE THREAD

**Issue by RianaWolfy** [obs-ndi/obs-ndi#523]
Hello,

I recently re-installed windows 10 on my main desktop and had to re-install OBS and NDI.
I have done the same on my laptop as well, meaning both my laptop and desktop have the same version of NDI and OBS.

Now i use NDI so my gaming laptop can stream whilst my main desktop doesn't have to both game and handle encoding at the same time.

For some reason however I can barely get NDI working if it goes:
Desktop --- > Laptop
However it will work if I go
Laptop ---> Desktop 
(however it will still stutter to HELL)

Now it will work...1% of the time from Desktop to laptop, but the other times it won't and it will stutter the living crap out of both my desktop and laptop, plus stutter the audio on both devices.

From what I can see from the logs on both machines, the NDI plugin loads fine..
But idk what the hell is happening for this not to work.. i had it working before hand.... for many months

**Comment by paulpv** [comment]
Does this issue still happen with 4.13.0?

Is the firewall setup identical on your PCs?

**Comment by RianaWolfy** [comment]
I no longer use NDI, its being 3 years lol
