### ISSUE TITLE
After restart, OBS NDI Output is not published in the network

### ISSUE THREAD

**Issue by ichdertobi** [obs-ndi/obs-ndi#524]
## The Problem
I probably have a problem and assume that it is the plugin itself. 
So far, the plugin works perfectly except when the network is down for a moment or OBS Studio has to be restarted. OBS then immediately finds a stored NDI source from a scene but does not seem to publish its main or preview via NDI anymore. I can no longer find the NDI source (from OBS) on another PC

## Systemparameters
Windows 10 1909
OBS Studio 25.0.8
OBS-NDI 4.9.1

**Comment by paulpv** [comment]
Does this still happen using 4.13.0?

**Comment by paulpv** [comment]
Closing due to no response
