### ISSUE TITLE
Audio de-sync issues with 4.9 and 4.8 (3 PC setup)

### ISSUE THREAD

**Issue by Xciles** [obs-ndi/obs-ndi#534]
Issue: 
- Audio de-sync using either OBS-NDI 4.8 or 4.9
- Worse audio de-sync when using the 4.9 version

Setup:
```
PC - v (NDI)
  Server (Encoding -> Twitch)
PC - ^ (NDI)
```

Both PCs have 4 NDI sources: 2 Video (Main Display capture 1080p (rendered down from 1440p native), Webcam capture 720p) and 2 Audio (Desktop Audio and Microphone). All sources are sent to the server which does the rest and combines additional shared scenes. We get no (or almost no) rendering issues or other dropped frames using this setup.

Splitting everything into different sources should have, as other topics described, resulted into everything being synced properly, however for some reason, this is not the case using our setup.

All 3 PCs are rather beefy and (should) have no issues regarding CPU or GPU limitations and are connected with a proper router on a gigabit network. Both source PCs are using 10%-ish CPU and 15/20% GPU and are sending roughly 120/160mbits of data. The server receives roughly 250/350mbits of data, uses 20%-ish CPU and 25/30%-ish GPU. We connect to the server using remote desktop with hardware graphics adapter enabled for remote sessions (which should resolve other rendering issues), however connecting without Remote Desktop and using a monitor with mouse and keyboard does result in the same issues. The server also has no (or almost no) rendering issues or other dropped frames.

In the below scenarios we tried all different sync methods, Internal, Network and Source Timing, which still results into the audio being de-synced. Some scenarios de-sync more and faster than others and when using 4.9 this de-sync happens a lot faster and makes 4.9 not usable. 

What we tried so far (and resulted in audio being de-synced (after a while >1 hour and faster <1 hour)):

- 4 NDI Sources per PC and using different sync methods.
  - The above scenario, 4 sources: 2 vid, 2 audio.
  - We tried this setup using OBS 25.* and NDI 4.8 or 4.9.
  - In this scenario all sources have a different delay. OBS NDI 4.9 makes the problem worse and increases the delay at a faster rate.
- 2 NDI Sources per PC and using different sync methods.
  - The above scenario, using 2 sources instead of 4. We combined the audio-only sources into the corresponding video sources:
    - Desktop capture with desktop audio source.
    - Webcam with microphone source.
  - This results in a -somewhat- workable solution. The audio and video within the combination source are synced correctly, but there is still a delay between the two combination sources (i.e. (webcam+mic) is a full second ahead of (desktop+audio)).
  - Using OBS NDI 4.9 results into the audio streams, within 1 NDI Source, being delayed again as well. (we do not have this issue with the 4.8 version)
    - We also tried to decrease the desktop video size (from 1440p to 1080p), because we thought the server could not handle this amount of data. This had no noticeable impact. We could reduce the encoded size even more (from 1440p to 720p for example) however I do not think this will make a difference. I could try if suggested.

Testing with one PC (sending data to the server using NDI) will result in the same issue.

We tried a lot of setups and a lot of potential fixes, but currently ran into a dead end with no idea what to do next or how we can fix this issue.

Demo of issue: https://clips.twitch.tv/SmokyLovelyPotUWot
Link to logs on gist: https://gist.github.com/Xciles/e7d5c03b68f7cc30c2008d0636eecf21

I've also posted this issue on the OBS forums, but thought that we might just ask directly and create an issue for this, since we think this clearly isn't working properly.

**Comment by digitalis99** [comment]
I posted about a similar issue with 4.8 and 4.9.  The video latency drifts over time with both, resulting in an inability to sync audio with video.

**Comment by unknowndomain** [comment]
Presumably related to #375 ?

**Comment by m0nji** [comment]
i have nearly the same problem. i have a dual pc setup and a elgato 4k 60 mk2. just audio goes from the game pc through OBS NDI to the stream pc. for this i use the "Dedicated NDI Output" filter on the audio mixer.
after around 20-30 i recognize first delays of 100-200ms. after that i grows up to 1-1,5sec.
normally i used the sync type "network" and everything was fine. now i try it with "source timing". but i don't think it will solve the problem when i read this thread :(

**Comment by paulpv** [comment]
Is this still an issue in 4.13.0?
