### ISSUE TITLE
NDI Plugin Causing Extreme Network Lag

### ISSUE THREAD

**Issue by crambosho** [obs-ndi/obs-ndi#536]
So I have an issue where it seems that after streaming for a while with a dual PC NDI set up, my internet ping in-game jumps for 16 -> 600. I've tested several scenarios where I would change settings, even turn off OBS. After playing with it, it seems as though disabling the NDI plugin from OBS completely fixes the lag issue, and once turned back on, everything goes back to extreme lag.

I have a gigabit ethernet set up that honestly has worked for the past year with NDI, so running into this issue with no changes is very surprising.

Edit: it might be important to mention that once I start lagging, I turn off OBS then turn it back on without even streaming and it still lags.

16:17:22.890: CoInitializeEx succeeded: 0x00000001
16:17:22.890: CPU Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
16:17:22.890: CPU Speed: 3600MHz
16:17:22.890: Physical Cores: 8, Logical Cores: 16
16:17:22.890: Physical Memory: 32681MB Total, 22738MB Free
16:17:22.890: Windows Version: 10.0 Build 18363 (release: 1909; revision: 959; 64-bit)
16:17:22.890: Running as administrator: false
16:17:22.890: Aero is Enabled (Aero is always on for windows 8 and above)
16:17:22.891: Windows 10 Gaming Features:
16:17:22.891: 	Game Bar: Off
16:17:22.891: 	Game DVR: Off
16:17:22.891: 	Game DVR Background Recording: Off
16:17:22.892: 	Game Mode: Off
16:17:22.894: Sec. Software Status:
16:17:22.895: 	Windows Defender Antivirus: enabled (AV)
16:17:22.895: 	Windows Firewall: disabled (FW)
16:17:22.895: Current Date/Time: 2020-07-23, 16:17:22
16:17:22.895: Browser Hardware Acceleration: true
16:17:22.895: Portable mode: false
16:17:23.089: OBS 25.0.8 (64-bit, windows)
16:17:23.089: ---------------------------------
16:17:23.089: ---------------------------------
16:17:23.089: audio settings reset:
16:17:23.089: 	samples per sec: 44100
16:17:23.089: 	speakers:        2
16:17:23.091: ---------------------------------
16:17:23.091: Initializing D3D11...
16:17:23.091: Available Video Adapters: 
16:17:23.092: 	Adapter 0: NVIDIA GeForce RTX 2080 Ti
16:17:23.092: 	  Dedicated VRAM: 2994733056
16:17:23.092: 	  Shared VRAM:    4249681920
16:17:23.092: 	  PCI ID:         10de:1e07
16:17:23.093: 	  Driver Version: 27.21.14.5148
16:17:23.093: 	  output 0: pos={0, 0}, size={2560, 1440}, attached=true, refresh=165, name=AG271QG
16:17:23.093: 	  output 1: pos={-1280, -2160}, size={3840, 2160}, attached=true, refresh=60, name=LG Ultra HD
16:17:23.094: Loading up D3D11 on adapter NVIDIA GeForce RTX 2080 Ti (0)
16:17:23.132: D3D11 loaded successfully, feature level used: b000
16:17:23.132: DXGI increase maximum frame latency success
16:17:23.132: D3D11 GPU priority setup failed (not admin?)
16:17:23.483: ---------------------------------
16:17:23.483: video settings reset:
16:17:23.483: 	base resolution:   2560x1440
16:17:23.483: 	output resolution: 1920x1080
16:17:23.483: 	downscale filter:  Lanczos
16:17:23.483: 	fps:               60/1
16:17:23.483: 	format:            NV12
16:17:23.483: 	YUV mode:          601/Partial
16:17:23.483: NV12 texture support enabled
16:17:23.484: Audio monitoring device:
16:17:23.484: 	name: Default
16:17:23.484: 	id: default
16:17:23.484: ---------------------------------
16:17:23.487: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
16:17:23.487: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
16:17:23.527: [AMF] Unable to load 'amfrt64.dll', error code 126.
16:17:23.528: [AMF] AMF Test failed due to one or more errors.
16:17:23.529: Failed to initialize module 'enc-amf.dll'
16:17:23.544: [obs-browser]: Version 2.8.6
16:17:23.547: NVENC supported
16:17:23.549: [obs-ndi] hello ! (version 4.9.0)
16:17:23.549: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
16:17:23.549: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
16:17:23.551: [obs-ndi] NDI runtime loaded successfully
16:17:23.554: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0)
16:17:23.681: Failed to load 'en-US' text for module: 'StreamDeckPlugin.dll'
16:17:23.688: Couldn't find VLC installation, VLC video source disabled
16:17:23.693: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
16:17:23.693: No blackmagic support
16:17:23.697: ---------------------------------
16:17:23.697:   Loaded Modules:
16:17:23.697:     win-wasapi.dll
16:17:23.697:     win-mf.dll
16:17:23.697:     win-dshow.dll
16:17:23.697:     win-decklink.dll
16:17:23.697:     win-capture.dll
16:17:23.697:     vlc-video.dll
16:17:23.697:     text-freetype2.dll
16:17:23.697:     StreamDeckPlugin.dll
16:17:23.697:     rtmp-services.dll
16:17:23.697:     obs-x264.dll
16:17:23.697:     obs-vst.dll
16:17:23.697:     obs-transitions.dll
16:17:23.697:     obs-text.dll
16:17:23.697:     obs-qsv11.dll
16:17:23.697:     obs-outputs.dll
16:17:23.697:     obs-ndi.dll
16:17:23.697:     obs-filters.dll
16:17:23.697:     obs-ffmpeg.dll
16:17:23.697:     obs-browser.dll
16:17:23.697:     image-source.dll
16:17:23.697:     frontend-tools.dll
16:17:23.697:     enc-amf.dll
16:17:23.697:     decklink-ouput-ui.dll
16:17:23.697:     coreaudio-encoder.dll
16:17:23.697: ---------------------------------
16:17:23.697: ==== Startup complete ===============================================
16:17:23.700: All scene data cleared
16:17:23.700: ------------------------------------------------
16:17:23.725: WASAPI: Device 'Speakers (HyperX Cloud Flight S Game)' [48000 Hz] initialized
16:17:23.728: [Loaded global audio device]: 'Desktop Audio'
16:17:23.728:     - filter: 'Dedicated NDI™ output (Audio Only)' (ndi_audiofilter)
16:17:23.743: WASAPI: Device 'Microphone (Scarlett Solo USB)' [44100 Hz] initialized
16:17:23.744: [Loaded global audio device]: 'Mic/Aux'
16:17:23.744:     - filter: 'Mic Volume' (ndi_audiofilter)
16:17:23.754: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Desktop Audio)
16:17:23.754: 
16:17:24.464: Switched to scene 'Scene'
16:17:24.464: [game-capture: 'Full Screen Cap'] attempting to hook fullscreen process: VALORANT-Win64-Shipping.exe
16:17:24.467: ------------------------------------------------
16:17:24.467: Loaded scenes:
16:17:24.467: - scene 'Scene':
16:17:24.467:     - source: 'Full Screen Cap' (game_capture)
16:17:24.467:     - source: 'alerts2' (browser_source)
16:17:24.467: ------------------------------------------------
16:17:24.469: [game-capture: 'Full Screen Cap'] d3d11 shared texture capture successful
16:17:24.484: [game-capture: 'Full Screen Cap'] shared texture capture successful
16:17:24.587: [obs-ndi] starting NDI main output with name 'crambosho'
16:17:24.587: [obs-ndi] 'crambosho': ndi output started
16:17:32.880: ==== Shutting down ==================================================
16:17:32.893: [obs-ndi] stopping NDI main output
16:17:32.893: Output 'NDI Main Output': stopping
16:17:32.893: Output 'NDI Main Output': Total frames output: 497
16:17:32.893: Output 'NDI Main Output': Total drawn frames: 498
16:17:33.675: Switched to scene '(null)'
16:17:33.675: [game-capture: 'Full Screen Cap'] capture stopped
16:17:33.685: WASAPI: Device 'Speakers (HyperX Cloud Flight S Game)' Terminated
16:17:33.695: WASAPI: Device 'Microphone (Scarlett Solo USB)' Terminated
16:17:33.696: All scene data cleared
16:17:33.696: ------------------------------------------------
16:17:33.771: Freeing OBS context data
16:17:33.786: [obs-ndi] goodbye !
16:17:33.812: [Scripting] Total detached callbacks: 0
16:17:33.816: == Profiler Results =============================
16:17:33.816: run_program_init: 2385.31 ms
16:17:33.816:  ┣OBSApp::AppInit: 9.528 ms
16:17:33.816:  ┃ ┗OBSApp::InitLocale: 1.009 ms
16:17:33.816:  ┗OBSApp::OBSInit: 1934.44 ms
16:17:33.816:    ┣obs_startup: 4.822 ms
16:17:33.816:    ┗OBSBasic::OBSInit: 1736.02 ms
16:17:33.816:      ┣OBSBasic::InitBasicConfig: 0.342 ms
16:17:33.816:      ┣OBSBasic::ResetAudio: 0.149 ms
16:17:33.816:      ┣OBSBasic::ResetVideo: 394.75 ms
16:17:33.816:      ┣OBSBasic::InitOBSCallbacks: 0.005 ms
16:17:33.816:      ┣OBSBasic::InitHotkeys: 0.037 ms
16:17:33.816:      ┣obs_load_all_modules: 213.22 ms
16:17:33.816:      ┃ ┣obs_init_module(coreaudio-encoder.dll): 0.397 ms
16:17:33.816:      ┃ ┣obs_init_module(decklink-ouput-ui.dll): 0.415 ms
16:17:33.816:      ┃ ┣obs_init_module(enc-amf.dll): 40.038 ms
16:17:33.816:      ┃ ┣obs_init_module(frontend-tools.dll): 3.088 ms
16:17:33.816:      ┃ ┣obs_init_module(image-source.dll): 0.005 ms
16:17:33.816:      ┃ ┣obs_init_module(obs-browser.dll): 0.268 ms
16:17:33.816:      ┃ ┣obs_init_module(obs-ffmpeg.dll): 1.021 ms
16:17:33.816:      ┃ ┃ ┗nvenc_check: 0.978 ms
16:17:33.816:      ┃ ┣obs_init_module(obs-filters.dll): 0.012 ms
16:17:33.816:      ┃ ┣obs_init_module(obs-ndi.dll): 9.295 ms
16:17:33.816:      ┃ ┣obs_init_module(obs-outputs.dll): 0.006 ms
16:17:33.816:      ┃ ┣obs_init_module(obs-qsv11.dll): 114.671 ms
16:17:33.816:      ┃ ┣obs_init_module(obs-text.dll): 0.226 ms
16:17:33.816:      ┃ ┣obs_init_module(obs-transitions.dll): 0.005 ms
16:17:33.816:      ┃ ┣obs_init_module(obs-vst.dll): 0.002 ms
16:17:33.816:      ┃ ┣obs_init_module(obs-x264.dll): 0.002 ms
16:17:33.816:      ┃ ┣obs_init_module(rtmp-services.dll): 0.697 ms
16:17:33.816:      ┃ ┣obs_init_module(StreamDeckPlugin.dll): 2.562 ms
16:17:33.816:      ┃ ┣obs_init_module(text-freetype2.dll): 0.04 ms
16:17:33.816:      ┃ ┣obs_init_module(vlc-video.dll): 0.039 ms
16:17:33.816:      ┃ ┣obs_init_module(win-capture.dll): 1.085 ms
16:17:33.816:      ┃ ┣obs_init_module(win-decklink.dll): 3.091 ms
16:17:33.816:      ┃ ┣obs_init_module(win-dshow.dll): 1.663 ms
16:17:33.816:      ┃ ┣obs_init_module(win-mf.dll): 0 ms
16:17:33.816:      ┃ ┣obs_init_module(win-wasapi.dll): 0.006 ms
16:17:33.816:      ┃ ┗reset_win32_symbol_paths: 0.082 ms
16:17:33.816:      ┣OBSBasic::ResetOutputs: 0.2 ms
16:17:33.816:      ┣OBSBasic::CreateHotkeys: 0.023 ms
16:17:33.816:      ┣OBSBasic::InitService: 1.296 ms
16:17:33.816:      ┣OBSBasic::InitPrimitives: 0.084 ms
16:17:33.816:      ┗OBSBasic::Load: 771.195 ms
16:17:33.816: obs_hotkey_thread(25 ms): min=0.003 ms, median=0.007 ms, max=0.222 ms, 99th percentile=0.122 ms, 100% below 25 ms
16:17:33.816: audio_thread(Audio): min=0 ms, median=0.058 ms, max=0.193 ms, 99th percentile=0.162 ms
16:17:33.817: obs_graphics_thread(16.6667 ms): min=0.066 ms, median=0.475 ms, max=713.017 ms, 99th percentile=1.916 ms, 99.8261% below 16.667 ms
16:17:33.817:  ┣tick_sources: min=0.001 ms, median=0.015 ms, max=712.889 ms, 99th percentile=0.262 ms
16:17:33.817:  ┣output_frame: min=0.059 ms, median=0.453 ms, max=1.936 ms, 99th percentile=1.381 ms
16:17:33.817:  ┃ ┣gs_context(video->graphics): min=0.059 ms, median=0.145 ms, max=0.392 ms, 99th percentile=0.273 ms
16:17:33.817:  ┃ ┃ ┣render_video: min=0.005 ms, median=0.052 ms, max=0.193 ms, 99th percentile=0.122 ms
16:17:33.817:  ┃ ┃ ┃ ┣render_main_texture: min=0.004 ms, median=0.019 ms, max=0.159 ms, 99th percentile=0.047 ms
16:17:33.817:  ┃ ┃ ┃ ┣render_output_texture: min=0.005 ms, median=0.006 ms, max=0.058 ms, 99th percentile=0.02 ms, 0.866087 calls per parent call
16:17:33.817:  ┃ ┃ ┃ ┣render_convert_texture: min=0.005 ms, median=0.006 ms, max=0.066 ms, 99th percentile=0.025 ms, 0.866087 calls per parent call
16:17:33.817:  ┃ ┃ ┃ ┗stage_output_texture: min=0.001 ms, median=0.012 ms, max=0.082 ms, 99th percentile=0.057 ms, 0.866087 calls per parent call
16:17:33.817:  ┃ ┃ ┣gs_flush: min=0.028 ms, median=0.044 ms, max=0.242 ms, 99th percentile=0.162 ms
16:17:33.817:  ┃ ┃ ┗download_frame: min=0 ms, median=0.041 ms, max=0.244 ms, 99th percentile=0.105 ms, 0.866087 calls per parent call
16:17:33.817:  ┃ ┗output_video_data: min=0.247 ms, median=0.312 ms, max=1.761 ms, 99th percentile=1.348 ms, 0.864348 calls per parent call
16:17:33.817:  ┗render_displays: min=0 ms, median=0 ms, max=0.002 ms, 99th percentile=0.001 ms
16:17:33.817: video_thread(video): min=2.543 ms, median=2.842 ms, max=5.594 ms, 99th percentile=4.21 ms
16:17:33.817: =================================================
16:17:33.817: == Profiler Time Between Calls ==================
16:17:33.817: obs_hotkey_thread(25 ms): min=24.97 ms, median=25.93 ms, max=26.351 ms, 4.30622% within ±2% of 25 ms (0% lower, 95.6938% higher)
16:17:33.817: obs_graphics_thread(16.6667 ms): min=3.664 ms, median=16.667 ms, max=713.022 ms, 99.6516% within ±2% of 16.667 ms (0.174216% lower, 0.174216% higher)
16:17:33.817: =================================================
16:17:33.827: Number of memory leaks: 0

**Comment by chenister** [comment]
I have the same issue, my setup was find until I updated NDI runtime 2 days ago.  I have been using NDI SDK 3.8 for the longest time and decided to update.  But after about 20 mins of using my setup the ping in my games are like 300+ usually under 15.  I tried a new network switch, new network adapter, nothing worked.  The throttling is from my Gaming PC.  I am assuming it's the update, so I tried to look for an older version of NDI runtime but no luck finding it.  I ended up doing a windows restore before the update and my setup works fine.

**Comment by Trouffman** [comment]
@crambosho Looks like you have 3 output over NDI on that computer : 
Desktop Audio - Audio ndi out via a  'Dedicated NDI™ output (Audio Only)' (ndi_audiofilter)
Mic/Aux - 'Mic Volume' (ndi_audiofilter)

And everything output to Main Output over NDI under the name : crambosho

@crambosho  "I turn off OBS then turn it back on without even streaming and it still lags."
> Go into Tools > NDI Output Settings >Disable both Main and Preview output.

Please confirm if this fixed the issue or not.

If not :
- Try with a clean scene collection. > still the same problem ?
if not again : 
- add one by one the sources until this pause the issue and this will help narrow the problem.

**Comment by Trouffman** [comment]
Closing this issue as it is old/not been updated/expired and most- likely fixed in more recent version.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.
