### ISSUE TITLE
NDI out hangs when switching scene collections

### ISSUE THREAD

**Issue by thedug** [obs-ndi/obs-ndi#542]
When I hit a key on my stream deck for a scene that is in a different scene collection, it toggles fine in OBS but the output of NDI freezes.

I have to restart OBS or I have to uncheck NDI main out and save, and then check NDI main out again.

**Comment by nettings** [comment]
I don't think switching scene collections during  a live session is something that you should do. On my setup, not just NDI hangs, also some USB cameras get really irritated.

**Comment by tt2468** [comment]
What OS are you on? I can't seem to reproduce in OBS v26.0.0 on Windows 10.

**Comment by thedug** [comment]
Windows 10
  

  
I just upgraded OBS. I’ll test it again.
  

  
Someone did mention that it might be because I have a bunch of sources.   
  
  
  
  
Sent from my iPhone; forgive my typos!
  

 --
 Douglas Ferguson
  
      
  

  
  
>

**Comment by paulpv** [comment]
Closing due to age/no-update
