### ISSUE TITLE
Install issues Mac 

### ISSUE THREAD

**Issue by NterJC** [obs-ndi/obs-ndi#552]
Hi I'm trying to install OBS-ndi 4.7.1 into OBS Web-RTC 23.2.1-151-gf149320e ( ie the millicast webrtc version )  onto a Mac Pro running Mojave 10.14.6 

OB is installed fin and running well.
ndi-runtime-4.5.1-macOS is insalled fine
When i run the installer for obs-ndi 4.7.1 it failes at validating!

any help appreciated

**Comment by paulpv** [comment]
Closing due to release of 4.13.0.
If this is still happening someone can reopen this or open a new issue.
