### ISSUE TITLE
Dual Mac OBS NDI Stutter/Lag A/V Issue

### ISSUE THREAD

**Issue by hugohayes93** [obs-ndi/obs-ndi#555]
Hey there,

I tried the OBS project forums for this issue first but after a lot of testing and not a lot of luck, I believe it may be an NDI issue. 

Getting random and intermittent audio skips, where it'll skip a little bit further into the song when monitoring on second computer, but fine when monitoring main computer. Similarly, will get random visual freezes from feed coming from main computer via NDI. No sign of too much load on CPU, GPU, RAM or connection... Tried a lot of things to rectify and was even getting the same issue after simplifying the hell out of both set ups, but it did appear to improve slightly.

I concluded, but potentially incorrectly as I haven't been able to officially diagnose if it is the issue, that overuse across all scenes of the same NDI source leads to some sort of jamming up which leads to freezes/stuttering, but doesn't appear to actually affect CPU, GPU, RAM or the connection if doing so. Having each NDI source in it's own scene then adding the scene to other scene's as needed seems to be a "temp" fix that leaves me with minimal, but still some, issues.

The full details are here: https://obsproject.com/forum/threads/dual-mac-obs-ndi-stutter-lag-audio-visual-issue.129377/#post-479352

Thanks!

**Comment by Trouffman** [comment]
After reading both here and the OBS forum : 
Do you have any Network analyzer like NMAP, Fiddler, wireshark  on any of the 2 PC?
> This can create "drop" or increased latency for the NDI feed.

On your first system (sending) > Confirm that this problem is NOT there locally (Listen to the local NDI feed)
On your second system (receiveing) > do the same thing
> If the problem is only on One system - this is the one you digg for solution.

**Comment by Trouffman** [comment]
Closing this issue as it is old/not been updated/expired and most- likely fixed in more recent version.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.
