### ISSUE TITLE
obs-ndi prevents OBS Studio from minimizing to tray

### ISSUE THREAD

**Issue by matoi974** [obs-ndi/obs-ndi#556]
OS & version: Windows 10 2004, obs-ndi 4.9.1, OBS Studio 26.0 RC2

STR:
Install the plugin.
In Settings > General > System Tray, verify that "always minimize to system tray instead of task bar" is ticked.
Click the OBS Studio icon in the notifications tray, or the Minimize button in the main window.

Expected results:
OBS Studio minimizes to tray.

Actual result:
If you clicked on the notifications tray, nothing happens. If you minimized the window, it minimizes (not to tray).

**Comment by Seamas73** [comment]
I confirm that Issue. OS: Win 10 Pro 2004? obs ndi 4.9.0 OBS Studio 25.0.8 64-bit

**Comment by SgtBreadStick** [comment]
I can also confirm that this issue occurs.    Windows 10 Pro 20H2 (19042) x64 - OBS NDI 4.9.1 - OBS Studio 26.1.1

**Comment by paulpv** [comment]
Known issue.
https://github.com/obs-ndi/obs-ndi/issues?q=minimize

Main bug that mentions the fix is https://github.com/obs-ndi/obs-ndi/issues/587

Closing this one; will fix in https://github.com/obs-ndi/obs-ndi/issues/587
