### ISSUE TITLE
NDI OBS! NDI record sound problem 

### ISSUE THREAD

**Issue by Topsn** [obs-ndi/obs-ndi#565]
Hey togehter.

I use OBS and NDI for livestreaming via iphone5se.
I worked on Mac an everything worked really well.

Last week i bought a pc because i needed more power.
So i installed OBS and the newest NDI plugin, everything worked great.

BUT: 
i get the Video Signal in OBS via NDI
i get the sound signal perfect from NDI (iphone)

BUT WHEN I STREAM OR RECORD THERE IS NO SOUND!!!
And really Strange:
 wenn i send the same signal from my mac to my new PC via NDI >  i get everything and when i stream or record there is a sound too!!!

In the other direction > i send a NDI signal vom PC to Mac > i get no sound anyway > even in the Mixer there is no signal!

i tried everything and now i´m at a loss.

My Setup:
AMD Ryzen 9 3950x 16-Core
64 gb RAM 
NVIDIA GeForce GTX 1080 TI

OBS: 25.0.8
NDI Plugin: 4.9.0

i´m looking forward for any help and information.
Because this is really importand for me 

thank you

**Comment by bufanda** [comment]
I think thisis related to this issue: https://github.com/Palakis/obs-ndi/issues/429
I recommend downgrading to 4.7.1 for the timebeing. For me it worked with that version again.

**Comment by bufanda** [comment]
Ok now I had the issue again with 4.7 and tried 4.9 again too. It worked then until a restart. I then change the configuration of the source and changed it back and it finally recorded again. I am not sure yet, but it seems you have to cahnge configuration for the soruce each time to kinda reset it. But this would actually suck.

**Comment by Topsn** [comment]
thank you for you information. i just fixed it with 4.7.1. but since i update on obs 26. i have the same problems.
It is really strange because everything works perfect on my mac computers.

**Comment by Topsn** [comment]
got it: we still know it´s a plugin problem but where exactly?
 the problem is the "SYNC" mode in the ndi source settings. i only get a sound singal in streaming and record when i´m in "INTERNAL" mode.
In NDI 4.9 there is no INTERNAL mode anymore. 
Thats why you can`t record the sound!! 

i don`t know why but is the status quo.
we have to work with that settings until the bug is

**Comment by asergeant01** [comment]
I can confirm @Topsn work around allows audio to be recorded.

**Comment by Trouffman** [comment]
@Topsn COuld you confirm your NDI Source settings on both your windows and your Mac configuration? 

Especially the bandwidth and sync options.

**Comment by multiflexi** [comment]
I have the same issue with NDI Android app and Windows OBS. When the SYNC is set to Network, the audio is streamed and recorded, if it is set to Source Timing, then I get no audio in the stream and the recording as well. Got the latest version of all SW.

**Comment by Trouffman** [comment]
Closing this issue as it is old/not been updated/expired and most- likely fixed in more recent version.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.
