### ISSUE TITLE
OBS NDI Source Audio Crackling

### ISSUE THREAD

**Issue by HaoTao95** [obs-ndi/obs-ndi#574]
When I used the obs NDI plugin with Release version(4.9.1), the audio was fine.

But when I updated it with the latest from github source,  buzz sound is inserted to obs ndi audio, like crackling.
I noticed that the github source was updated with something related to audio.
Is there any problem in updated code?

Can you explain it?

**Comment by mkdryden** [comment]
I have the same issue, compiling on Ubuntu 20.10. It's a sort of crackling, though only in the right channel, when using an NDI Source (doesn't affect NDI Output), and affects both monitoring and stream/recording output. As far as I can tell, it was introduced in 7b04e64.

**Comment by nixinator** [comment]
we have been playing around with two linux system, arch and NixOS with ndi-obs Seems that the latest obs-ndi of the tip of master has the problem. We reverted both the systems to the obs-ndi 4.9.1 tagged release and everything worked well.  22c7f7c https://github.com/Palakis/obs-ndi/releases/tag/4.9.1  . I hope this helps.

**Comment by Trouffman** [comment]
Closing, as this is outdated. Please use latest version.
