### ISSUE TITLE
NDI audio source starts without sound

### ISSUE THREAD

**Issue by filippsudanov** [obs-ndi/obs-ndi#578]
I am using NDIntercom iphone app to generate NDI audio stream. Iphone is connected to fast router, my PC is connected to that router via Ethernet, no slow network here, the audio stream is about 0.8 Mbps.
In OBS corresponding NDI Source sometimes becomes silent. This often happens right after the source is created. Quite often it happens on OBS start, then audio starts to work after some time. Restarting the app on the phone also helps. 
While the input is silent, I see the same 0.8 Mbps network traffic from the phone, which stops when I stop OBS, so obs-ndi actually receives the stream, but audio gets lost somewhere. 

Creating several sources pointing to the same NDI source could help to replicate the issue - it often happens that one of these sources produces audio and another is silent. 

OBS 26.0.2
obs-ndi 4.9.0
ndi-runtime 4.5.1
Windows 10 x64 with all available updates installed. 

Please inform if you need any debugging information from my system. I can also provide remote access to my system if you need.

**Comment by Trouffman** [comment]
Is the VU Meter in the Audio mixer moving?
Is the audio missing on recording as well?
> How is configured your NDI input ? (list all the option of that input)

**Comment by sylphid8** [comment]
I have found with the NDI HX Camera app that source sync does not work and I must use network sync. I'm betting that the same is here. It seems that the timecode field is set to zero in my tests, which I believe, is causing audio syncing issues.

**Comment by paulpv** [comment]
I suspect it is, but can you confirm if this is still an issue in 4.13.0?
