### ISSUE TITLE
Cannot find NDI source from IOS NDI HX Capture

### ISSUE THREAD

**Issue by Tennsoku** [obs-ndi/obs-ndi#581]
Hi, I'm trying to capture my iPad screen via NDI HX Capture app, but there's no source shown under obs-ndi plugin when broadcasting. 

My iPad is connected to WiFi 5GHz but the receiving desktop is wired connected to the same router. 

Is it required for both of the two sides need to be under the same **WIFI**? Can I manually set the IP for the source?

**Comment by burgoyn1** [comment]
@Tennsoku Did you ever find a solution to this? I am having a similar problem. I can get the NDI source on the Studio Monitor, but it won't show on the list in OBS. The only piece of software I was able to get working was JustWifiCam that showed up in both.

**Comment by fcanenguez** [comment]
I also am experiencing the same issue. The version of NDI HX Camera I have installed is version 2.4. Looks like the application was last updated 1 month ago according to my iOS device.

**Comment by JuiceBox7535** [comment]
Any progress with this? Trying to have my iPad as a source in OBS v26.1.0. Sometimes my iPad will show up under the NDI Source Name and work for a while, and then it no longer shows up (NDI source dropdown is blank). Have to reset computer and then it will show up about 30% of the time. 

22:29:42.050: [obs-ndi] hello ! (version 4.9.0)
22:29:42.050: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
22:29:42.050: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
22:29:42.106: [obs-ndi] NDI runtime loaded successfully
22:29:42.372: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0)

On my iPad the screen is broadcasting using NDI HX Capture v1.6. Thanks in advance, would really like to get this resolved!

**Comment by stefankoehne** [comment]
May this be the solution for you?
https://github.com/Palakis/obs-ndi/issues/629#issuecomment-854609882

**Comment by Tennsoku** [comment]
> May this be the solution for you?
> [#629 (comment)](https://github.com/Palakis/obs-ndi/issues/629#issuecomment-854609882)

I cannot find the OBS rule under WDF so I manually set up one. Still doesn't work though.

**Comment by rijalkash91** [comment]
i may just found a solution. try to install the NDI Tools from their website.
Link : https://ndi.tv/tools/#download-tools

and open Webcam Input application before running obs.

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by paulpv** [comment]
Closing due to no response
