### ISSUE TITLE
mac wont install OBS-NDI 

### ISSUE THREAD

**Issue by CSSjoy** [obs-ndi/obs-ndi#586]
obs-ndi-4.7.1-macOS.pkg

opening the software - error msg:
“obs-ndi-4.7.1-macOS.pkg” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

Trying to download the manual link page says Not found

Please advise. 
Thanks

**Comment by kellemar** [comment]
Right click, and click Open

**Comment by yns1137** [comment]
I don't know for what you want to install it, but for mirroring the screen on OBS to ZOOM, there's no need to install 'obs-ndi-4.7.1-macOS' and 'NewTekNDIToolsForMacOS'. Just click the "start virtual camera" button on the first page of OBS app at the right bottom. Then you can select "obs virtual camera" as one of the optional cameras on ZOOM.

**Comment by paulpv** [comment]
Closing due to release of 4.13.0
