### ISSUE TITLE
NDI connection immediately crashes my app

### ISSUE THREAD

**Issue by jrlopez24** [obs-ndi/obs-ndi#589]
my HD camera App for OBS crashes immediately when I try to connect with wifi NDI.
NDI runtime 4.5.1
obs-ndi 4.9.0
Mac OS Catalina 10.15.7
Iphone XR running iOS 14.2

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by paulpv** [comment]
Closing due to no response
