### ISSUE TITLE
OBS Studio not hiding in system tray after installing obs-ndi v.4.9.0 and earlier

### ISSUE THREAD

**Issue by Seamas73** [obs-ndi/obs-ndi#599]
After I've installed obs-ndi v.4.9.0 and earlier I couldn't hide OBS Studio in Windows 10 system tray by clicking on system-tray OBS icon or by right click on icon and choosing "hide" item of the context menu. When I click on icon I just turn off the preview mode In OBS Studio. So I had to delete your plugin to use "hide" option
Same bug I observed also when I used StreamFX plugin v.0.9.0. This bug was fixed by Xaymar in later releases [https://github.com/obsproject/obs-studio/issues/3518](url)

**Comment by paulpv** [comment]
Known issue.
https://github.com/obs-ndi/obs-ndi/issues?q=minimize

Main bug that mentions the fix is https://github.com/obs-ndi/obs-ndi/issues/587

Closing this one; will fix in https://github.com/obs-ndi/obs-ndi/issues/587
