### ISSUE TITLE
OBS-NDI & NDI Analysis "Video connection closed" when i start streaming

### ISSUE THREAD

**Issue by Mattchiew** [obs-ndi/obs-ndi#601]
Sorry for my english

I use the same version of NDI-OBS plugin between my MAC and my WINDOWS

On my windows, in OBS, i had "Source NDI", and it's working, i see the screen of my mac. It's working very well, but when i start the streaming, the source freeze, i try to delete it, and re-add, but it's not working.

**I run NDI Analysis (when stream OFFLINE):**

16:09:42.225: Video data rate (MBps). Avg=12.24
16:09:42.225: Video size (kB). Min=45.63 Avg=47.25 +/- 0.32 Max=48.04
16:09:42.262: Video recv (mS). Min=4.41 Avg=33.55 +/- 7.66 Max=74.78
16:09:42.270: Video send (mS). Min=8.09 Avg=33.33 +/- 6.92 Max=93.10
16:09:42.274: Audio data rate (MBps). Avg=2.49
16:09:42.275: Audio size (kB). Min=0.00 Avg=0.00 +/- 0.00 Max=0.00
16:09:42.275: Audio recv (mS). Min=0.00 Avg=21.43 +/- 9.76 Max=73.36
16:09:42.275: Audio send (mS). Min=0.04 Avg=21.40 +/- 7.38 Max=33.96

**I run NDI Analysis (when stream ONLINE):**

16:15:17.588: Video connection closed
16:15:19.611: Video connection opened
16:15:38.558: Video connection closed

I start stream, the video freeze (but i have the image, it's not black screen, just a permanent freeze). And when i stopped the stream, suddenly the video connection reopened, and on OBS the video was not freeze, i can see my image.

Thanks :)

**Comment by Trouffman** [comment]
Could you provide the log output when this is happenning ?

The freeze on the last received frame  is usually when a NDI feed is not available anymore, only the last frame is displayed.

Is this happening when you click "start streaming" ?

Using the NDI Tools > Studio Monitor, is the video feed still coming / working ?

**Comment by Mattchiew** [comment]
Thanks for your answer, i will test it tonight or tomorrow 😀

**Comment by Mattchiew** [comment]
I have to install Video Monitor on my STREAM PC or Gaming PC or Both ? Thanks

**Comment by Mattchiew** [comment]
I test on my stream PC, sometimes i see an another image, i force actualisation with Studio Monitor ... but it's juste 1 frame :/

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by paulpv** [comment]
Closing due to no response
