### ISSUE TITLE
OBS the new version total crash on Mac.

### ISSUE THREAD

**Issue by tocan** [obs-ndi/obs-ndi#602]
I got with the newest release of OBS a total crash on my Mac. I can not instal anymore any obs version now.

Can you provide a uninstalled or point any file I can delete by hand.

I am new on a Mac and never I got so much problems. I use Mojave. No upgrade idea for Catalina and Big Sur.

Inside the Forums or on discord server no one answer since 2 days.

Thanks

**Comment by dstessel** [comment]
Having the same issue here. OBS crashes on launch on Big Sur -- issue started following the installation of NDI plugin + runtime. Reinstall of OBS did not resolve the issue.

**Comment by Ruben-C** [comment]
Try going into /Library/Application Support/obs-studio/plugins and remove the NDI plugin.

**Comment by Malstrom** [comment]
And deleting Ndi plugin will solve this issue? @Ruben-C

**Comment by tocan** [comment]
IT did solve it for me.

Igor Mironenko <notifications@github.com> schrieb am Di., 29. Dez. 2020,
12:50:
