### ISSUE TITLE
NDI Doesn't display video source with Linux

### ISSUE THREAD

**Issue by settermjd** [obs-ndi/obs-ndi#605]
I've been trying unsuccessfully to get NDI working in OBS on Linux. I've had a number of issues with OBS, but for the most part, after building it from source, it now works. After doing so, I then installed the two .deb files, but there was no NDI source available in the Sources list. To correct that, I found the plugins directory using find and copied obs-ndi.so to that directory. 

After restarting OBS, an NDI source is now available. However, despite having an NDI source available on the local network, and the name being available in the Source name list, no video is displayed. All that's visible, as you can see in the screenshot below is a grey box. Is this a known bug? If so, is there a workaround for it? 

I'm using OBS Studio 26.1.0-20g20fb235b8 64-bit on Ubuntu 20.04.1 LTS with a 5.8.0-33-lowlatency kernel.

![Screenshot from 2020-12-27 11-31-15](https://user-images.githubusercontent.com/196801/103168837-13f29c00-4837-11eb-95ab-5c1083bbe12a.png)

**Comment by mohataj** [comment]
same here
ubuntu bionic kernel 5.4.0-70
obs-ndi 4.9.1-1
libndi4_4.5.1-1
obs 26.1.1

ndi source present and selectable but no video, no sound on ndi source

![image](https://user-images.githubusercontent.com/879585/112692741-b561ac00-8e7f-11eb-9b95-71c5a795c637.png)

**Comment by lcluster** [comment]
I have the same issue on linux mint 20.2,   NDI sources are not seen in drop down list at all.  
Kernel Version: Linux 5.4.0-89-generic,
OBS 27.1.3 (linux)
[obs-ndi] hello ! (version 4.9.1)
10:11:11 AM.024: [obs-ndi] Trying ''
10:11:11 AM.024: [obs-ndi] Trying '/usr/lib'
10:11:11 AM.024: [obs-ndi] Found NDI library at '/usr/lib/libndi.so.4'
10:11:11 AM.024: [obs-ndi] NDI runtime loaded successfully
10:11:11 AM.024: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 00:05:02 Apr  1 2020 4.5.1)
