### ISSUE TITLE
NDI not showing up on Apple M1 Chip.

### ISSUE THREAD

**Issue by SafeerHafiz** [obs-ndi/obs-ndi#606]
When will there be an update to work with the new M1 MacBooks? I know that someone mentioned this issue on the 19 Nov 2020 but it hasn't been fixed yet.

**Comment by TheUselessKent** [comment]
Same for me, M1 MacBook Pro.
NDI Plugin and NDI Runtime both install and show no errors.

NDI is not visible in OBS.

**Comment by mdg4486** [comment]
I just posted this fix in the other post:

FIX INSTRUCTIONS
To fix this issue you'll need to download the OBS-NDI plugin and Newtek's NDI Studio Monitor program (https://ndi.tv/tools/). 

You'll need to move the libndi.4.dylib file from /Applications/NewTek NDI Video Monitor.app/Contents/Frameworks TO /usr/local/lib/. You may need to hold down the "cmd" key while dragging this file so that it moves the file instead of creating an alias. Then restart your computer and open OBS. You should now see the NDI plugin in the source list. 

If you are having troubles finding the correct folders just use the "Go To Folder" option in your Finder Window and search for the directories I posted above. 

Good Luck!

**Comment by TheUselessKent** [comment]
> Good Luck!

Mate, you're a bloody legend!
I just bought and Elgato HD60 S and this just fixed a show stopper of an issue.

**Comment by caruso99x** [comment]
I looked for the Studio Monitor on the NDI website but it seems to only be available with Windows so how was this the solution to the M1 chip? Is there another link where the studio monitor is available?

**Comment by mdg4486** [comment]
Studio Monitor = Video Monitor 

They just recently renamed it.

**Comment by mzitnamor** [comment]
I just downloaded and installed "NewTek NDI Video Monitor". 
I went inside the package to find file "libndi.4.dylib"
I then copied the actual file to "/usr/local/lib/"
Restarted everything, including mac.

NDI as a source still does not show up at OBS. 

Am I doing something wrong or is above solution not applicable anymore?

**Comment by Narkolepsie** [comment]
Nice, now i have the Source in OBS - but OBS Link  can not find the Gamecapture HD60 .... 
![image](https://user-images.githubusercontent.com/79161645/108098193-6015cc00-7083-11eb-92f1-21b1f667530a.jpg)

**Comment by PetitDevil** [comment]
> I just posted this fix in the other post:
> 
> FIX INSTRUCTIONS
> To fix this issue you'll need to download the OBS-NDI plugin and Newtek's NDI Studio Monitor program (https://ndi.tv/tools/).
> 
> You'll need to move the libndi.4.dylib file from /Applications/NewTek NDI Video Monitor.app/Contents/Frameworks TO /usr/local/lib/. You may need to hold down the "cmd" key while dragging this file so that it moves the file instead of creating an alias. Then restart your computer and open OBS. You should now see the NDI plugin in the source list.
> 
> If you are having troubles finding the correct folders just use the "Go To Folder" option in your Finder Window and search for the directories I posted above.
> 
> Good Luck!

Thx bro. It works on my MacBook pro m1.

**Comment by kingjojo54** [comment]
can I get a video on how u moved the files. plz having a hard time

**Comment by yass-** [comment]
Hi,
i still can't set it up :/ 
Hopefully somebody can help me. 

Device: MacBook Air M1 
OS: 11.2.3
OBS: 26.1.2

Installed: 
- NewTekNDIToolsForMacOS.dmg download from today (installed from that: Video Monitor & Virtual Input)
- NewTekNDIHXDriverForMacOS.dmg download from today
- obs-ndi-4.9.0-macOS.pkg 
- https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg

I have only in /usr/local/lib the file libndi.4.dylib. Not in /Applications/NewTek\ NDI\ Video\ Monitor.app/Contents/Frameworks. 

MD5 (libndi.4.dylib) = fce41127483ec9133c35eff53567ce80

I am a little confused about what I might be missing... 

Thanks a lot for any help! 
yass

**Comment by yass-** [comment]
It is working! 😀
I have no idea why...

**Comment by 3Haven3** [comment]
> It is working! 😀
> I have no idea why...

How were you able to get it to work? I’m having the same issue as you.

**Comment by Rachellotje** [comment]
> I just posted this fix in the other post:
> 
> FIX INSTRUCTIONS
> To fix this issue you'll need to download the OBS-NDI plugin and Newtek's NDI Studio Monitor program (https://ndi.tv/tools/).
> 
> You'll need to move the libndi.4.dylib file from /Applications/NewTek NDI Video Monitor.app/Contents/Frameworks TO /usr/local/lib/. You may need to hold down the "cmd" key while dragging this file so that it moves the file instead of creating an alias. Then restart your computer and open OBS. You should now see the NDI plugin in the source list.
> 
> If you are having troubles finding the correct folders just use the "Go To Folder" option in your Finder Window and search for the directories I posted above.
> 
> Good Luck!

Hi! I've a question for you about thelibndi.4.dylib file moving. I've installed the video monitor, but if I want to open it up to go to the files, I get the same installation screen. Do I something wrong? Does this file stand somewhere else or something like that?

**Comment by Rachellotje** [comment]
OMG wait I found it!!!

**Comment by KytraScript** [comment]
> I just posted this fix in the other post:
> 
> FIX INSTRUCTIONS
> To fix this issue you'll need to download the OBS-NDI plugin and Newtek's NDI Studio Monitor program (https://ndi.tv/tools/).
> 
> You'll need to move the libndi.4.dylib file from /Applications/NewTek NDI Video Monitor.app/Contents/Frameworks TO /usr/local/lib/. You may need to hold down the "cmd" key while dragging this file so that it moves the file instead of creating an alias. Then restart your computer and open OBS. You should now see the NDI plugin in the source list.
> 
> If you are having troubles finding the correct folders just use the "Go To Folder" option in your Finder Window and search for the directories I posted above.
> 
> Good Luck!

https://drive.google.com/file/d/1x6EZWoZ1MnB6ktluoLkFWLED2y9UFo29/view?usp=sharing
Here's a link to download the stupid libndi.dylib file. I hate websites that require harvesting your personal data to retrieve a driver download. I went through the trouble so you don't have to.

**Comment by johnathon-b** [comment]
> I just posted this fix in the other post:
> 
> FIX INSTRUCTIONS To fix this issue you'll need to download the OBS-NDI plugin and Newtek's NDI Studio Monitor program (https://ndi.tv/tools/).
> 
> You'll need to move the libndi.4.dylib file from /Applications/NewTek NDI Video Monitor.app/Contents/Frameworks TO /usr/local/lib/. You may need to hold down the "cmd" key while dragging this file so that it moves the file instead of creating an alias. Then restart your computer and open OBS. You should now see the NDI plugin in the source list.
> 
> If you are having troubles finding the correct folders just use the "Go To Folder" option in your Finder Window and search for the directories I posted above.
> 
> Good Luck!

Did not work for me.

Is there an updated fix?

**Comment by notbrain** [comment]
Also seeing this same issue with a new install of everything in the docs. I have `libndi.4.dylib` in `/usr/local/lib` and have installed both packages. On OBS 28.1.2. Looks like everything is where it should be, but still seeing initial modal warning "NDI Runtime not found. Download the installer here https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg"—have done multiple times and rebooted to no avail.

Is this a new issue with 5.0 and 28+ or the same thing? What else can I try?

**Comment by julietteabeyta** [comment]
> I just posted this fix in the other post:
> 
> FIX INSTRUCTIONS To fix this issue you'll need to download the OBS-NDI plugin and Newtek's NDI Studio Monitor program (https://ndi.tv/tools/).
> 
> You'll need to move the libndi.4.dylib file from /Applications/NewTek NDI Video Monitor.app/Contents/Frameworks TO /usr/local/lib/. You may need to hold down the "cmd" key while dragging this file so that it moves the file instead of creating an alias. Then restart your computer and open OBS. You should now see the NDI plugin in the source list.
> 
> If you are having troubles finding the correct folders just use the "Go To Folder" option in your Finder Window and search for the directories I posted above.
> 
> Good Luck!

THANK YOU! This worked perfectly

**Comment by paulpv** [comment]
Closing due to release of 4.13.0
