### ISSUE TITLE
macOS Big Sur NDI source found, input remains black

### ISSUE THREAD

**Issue by chrisz100** [obs-ndi/obs-ndi#612]
Hi, when installing the plugin I can find my NDI sources in OBS yet the input remains black. I could see the feed display on my Windows 10 machine so it must be my device. Is there any way to reinstall the runtime as I did try completely removing and reinstalling OBS already?

**Comment by Schultzy1310** [comment]
I was able to install it on my Mac Mini on 10.15.7, but not my iMac on 11.2.3
I even tried to manually install the package from the mac mini to the iMac by copying the plugin from this directory, to the same directory. /Library/Application Support/obs-studio/plugins/obs-ndi

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by paulpv** [comment]
Closing due to no response
