### ISSUE TITLE
 i can't see pc1

### ISSUE THREAD

**Issue by piero21435** [obs-ndi/obs-ndi#616]
Hi, I have a problem with the ndi plugin from PC2 I can't see pc1 but from pc 1 I can see pc 2 what does it depend on? It only worked one day, when I installed everything, the next day nothing no longer worked, I tried to disable firewall and antivirus, I tried on the contrary from pc 1 to see pc 2 and it works but on the contrary it doesn't. How can I solve thanks

**Comment by BigMike1978** [comment]
Same problem here pls help

**Comment by paulpv** [comment]
NDI source discovery is a bit of a mystery to me.
Wish I knew how to make it more reliable.

Does this still happen using 4.13.0?

**Comment by paulpv** [comment]
Closing due to no response
