### ISSUE TITLE
No audio from TriCaster MIX output

### ISSUE THREAD

**Issue by kanelp** [obs-ndi/obs-ndi#622]
When I select the TriCaster MIX output as a source into OBS, I get no audio.  I also notice that the number of audio channels in the OBS audio mixer is not correct, it shows mono for the NDI source, when my TriCaster has 8 channels of audio.

I'm not 100% if the multi-channel audio is the issue.  The audio output from the TriCaster is good in any other NDI application I've sent it to, only OBS w/ the plug-in is having issues.

**Comment by kanelp** [comment]
I should also add, that this issue appears to be when there are 8 or more channels of audio inside the NDI signal.

**Comment by paulpv** [comment]
Related to https://github.com/obs-ndi/obs-ndi/issues/723
@Trouffman Which to keep?
