### ISSUE TITLE
NDI game audio and video desync

### ISSUE THREAD

**Issue by KandiidGuy** [obs-ndi/obs-ndi#628]
I live stream my xbox with Streamlabs OBS. To do this, I had to instead the NDI plugin to use my capture card (el gato) to capture video and audio. So the path my audio and video takes is xbox -> el gato capture card -> Mac book (obs link -> Streamlabs obs). 

For some reason, somewhere along that path, game and audio become desync'd by about 2 seconds with the video happening and audio coming after. 

If I stream anywhere else this isn't an issue, so my troubleshooting has me thinking the NDI or obs link or Streamlabs (being the only extra thing in the process) is the issue. 

Has there been any desync issues from audio and video within the NDI Source that has been noted with a fix? 

If I am missing something please let me know and I can address it. I'm not too knowledgeable on everything so just informing on what I am seeing from my end

**Comment by orbanbalage** [comment]
See #564

**Comment by Trouffman** [comment]
Closing this issue as it is old and most- likely fixed in more recent version.
Please upgrade to the latest versions (OBS / plugin / runtime) and open a new issue if this is still a problem.
