### ISSUE TITLE
Shortcuts point to non-existent documentations folder

### ISSUE THREAD

**Issue by vahost** [obs-ndi/obs-ndi#633]
I just installed on Windows 10. Links to the pdf files from All Programs > NDI 4 Runtime include a "documentations" folder in the paths that is a non-existent folder. So I had to manually change the shortcuts to remove that documentations reference from the paths to those pdf files in order to open and read them.

The paths are: 

1. C:\Program Files\NewTek\NDI 4 Runtime\v4\documentation\Introduction to NDI.pdf, which I changed to C:\Program Files\NewTek\NDI 4 Runtime\v4\Introduction to NDI.pdf

2. C:\Program Files\NewTek\NDI 4 Runtime\v4\documentation\NDI License Agreement.pdf, which I changed to C:\Program Files\NewTek\NDI 4 Runtime\v4\NDI License Agreement.pdf

3. C:\Program Files\NewTek\NDI 4 Runtime\v4\documentation\Introduction to NDI.pdf, which I changed to C:\Program Files\NewTek\NDI 4 Runtime\v4\NDI Problem Solving.pdf

There is also a fourth shortcut that points to: "C:\Program Files\NewTek\NDI 4 Runtime\v4\NDI Information.url", which is labeled ndi.tv but refers to a file that does not exist.

**Comment by paulpv** [comment]
Old bug in old NDI installers; closing
