### ISSUE TITLE
ndi stops working on obs studio

### ISSUE THREAD

**Issue by lustygenius** [obs-ndi/obs-ndi#638]
latest windows 10, obs stops connecting to 4k capture utility. i always run the el gato app first and it was fine, now it randomly stops working. i have to remove and then reinstall both to make it work again. please update this app or make 4k work as a game capture like it does on the hd60...

**Comment by rudolfbyker** [comment]
Similar? https://github.com/Palakis/obs-ndi/issues/651#issuecomment-835491893
