### ISSUE TITLE
Stuttering on the streaming computer despite no dropped frames

### ISSUE THREAD

**Issue by solaa** [obs-ndi/obs-ndi#641]
Currently running a dual OBS setup with my Gaming PC streaming over NDI to a m1 MacBook Pro where I have this intermittent jittering, it doesn't hang but it gets really choppy for about 5 or so seconds despite no reports of dropped frames. Not trying to self-promo here is an example https://www.twitch.tv/videos/985448002

streaming 720p60 @4350 bitrate (which is what OBS recommended) and my internet is rated for 59.1MB/s down - 2.9MB/s Up

Log file for stream computer https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FRvQRyutv-8-_8q8N

Log file for gaming PC https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FweGFO6x0izWwEeJk

Things I've tried:

- Running both OBS' as admin and root respectively
- Capping the gaming pc's FPS so to leave some GPU for OBS
- NDI Scan Converter on the gaming pc
- Both are wired connections 
- Gaming PC is rated for 1 gig and ethernet adapter for streaming pc has 10/100/1000 support.

My best theory is that my network setup may not have enough bandwidth and it goes like this

Router (DPC3939) ---> Access Point (Tenda AC10U) -----> Streaming PC / Gaming PC

Would a proper switch in between the Router and access point alleviate these issues?

Sorry If there's a lot of bloat information, new to all the NDI stuff and networking so I tried to be thorough, thank you in advance to anyone that can help!

**Comment by Trouffman** [comment]
Closing, as this is outdated. Please use latest version
