### ISSUE TITLE
re-connect NDI source  if interrupted

### ISSUE THREAD

**Issue by ghost** [obs-ndi/obs-ndi#647]
OBS-NDI source (and output) works fine, but short network outages stop the transmission for a long time. Is it possible to reduce this time  without manually pressing the OK button in the ndi properties ?

Thank you (Win10, OBS 26.1.1 ,obs-ndi 4.9.0 on both PC)

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?
Mine heals pretty fast.

**Comment by paulpv** [comment]
Closing due to no response
