### ISSUE TITLE
NDI Screen Capture works between two PCs but OBS-NDI plugin stopped a week ago

### ISSUE THREAD

**Issue by darrylyong** [obs-ndi/obs-ndi#651]
Two Windows 10 x64 PCs on the same subnet have been sharing a video feed perfecting using OBS-NDI for months now. Something broke recently and I can't figure out what happened--now the receiving machine only sees a black screen.

Tested so far:
1) OBS with NDI Output plugin running on source computer cannot be viewed by NDI Studio Monitor on the destination computer: (Machine and output name is viewable, but only see black screen--this was working perfectly for months up to last week)
2) NDI Screen Capture on the source computer is able to capture any portion of the screen (including the OBS preview pane) and this can be viewed by NDI Studio Monitor on the destination computer
3) NDI Screen Capture using OBS Virtual Camera on the source computer cannot be viewed by NDI Studio Monitor on the destination computer: (Machine and output name is viewable, but only see black screen)
4) OBS with NDI Output plugin running on source computer can be viewed by NDI Studio Monitor running also on the source computer

I think I've ruled out that it is a network issue, since NDI Screen Capture is working. It's just the specific interaction between NDI and OBS that doesn't seem to work.

What is most puzzling is that (1) was working perfectly for months and then suddenly stopped working last week. I suspect maybe some Windows updates might have broken something?  I don't know. I've even tried updating to latest NDI Tools OBS 27RC3 but that doesn't do anything. OBS NDI plugin version is 4.9.0.

Has anyone else encountered a similar issue where the plugin was working fine but then stopped working just recently?

**Comment by rudolfbyker** [comment]
My setup also stopped working randomly... Source is detected, but just shows black video. I tested on 3 different windows PCs, and also on LinuxMint:

- PC1 Windows 10.0.19042: Black video
- PC2 Windows 10.0.19042: Black video
- PC3 Linux: Working
- PC3 Windows 10.0.18363: Working

**Comment by rudolfbyker** [comment]
I get the exact same results with NDI Studio Monitor:

- PC1 Windows 10.0.19042: Black video
- PC2 Windows 10.0.19042: Black video
- PC3 Windows 10.0.18363: Working

One more thing that I have noticed, is that the source starts as a single point (presumably 0x0 or 1x1 pixels) in OBS on PC1 and PC2, while it's the proper resolution (in my case 720p) on PC3. Even when pressing CTRL+F (make source full screen), it stays black.

**Comment by darrylyong** [comment]
If this really is a Windows 10 thing, then maybe I should add another detail that perhaps could be related.

When Microsoft issued KB5001330, I noticed that caused frame rates for OBS-NDI to plummet. I rolled back that update and that solved the problem. However, one can only hold back those updates for so long.  After some point, Windows issued a Known Issue Rollback and that solved the frame rate problem. However, that was also around the time when the black screen issue came up and I am unsure of whether those two things are related to each other or not.

More context: https://www.bleepingcomputer.com/news/microsoft/microsoft-pushes-emergency-fix-for-windows-10-kb5001330-gaming-issues/

**Comment by instinctualjealousy** [comment]
Is this certainly a thing for everyone running up-to-date Win10 as transmitter? Audio is working but I have the no video/"red dot" issue on streaming PC and everything mentioned so far on the various issue pages has not resolved it. This is a fresh setup.

Some information:
Game PC: OBS 27.1.3 64-bit on Windows 10 21H1 64-bit, latest libndi, latest obs-ndi
Stream PC: Debian Bullseye 64-bit, OBS 27.0.1 (deb-multimedia), latest libndi, latest obs-ndi, dependencies met

- obs64 has a private firewall exception already, and I've tried turning off the firewall outright as a sanity test
- did the voodoo magic trick "turn on media streaming" that no one has explained the basis of and restarted, no dice
- I am not running gigabit ethernet between the computers, only one computer is capable and router is not capable- I am doing one low res source and network is not congested- tried low bandwidth mode anyway, no dice
- I have only one network adapter, so I don't believe a conflict is happening
- not related to the Ubuntu 16.04 issue a long time ago- log doesn't report an error
- given the receiving device is Linux and NDI have not provided any tools for it, analysis or workarounds aren't really an option
- The computers communicate well with other services like RTMP, SMB, xrdp/x11vnc

@darrylyong, to clarify- were you getting audio in your black NDI source?

**Comment by nanowireUK** [comment]
Pretty sure that whatever update affected Windows 10 is actually baked into Windows 11. I have exactly this problem as described on a clean Windows 11 install with updates.

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by paulpv** [comment]
Closing due to no response
