### ISSUE TITLE
Frequent crashing due to NDI.

### ISSUE THREAD

**Issue by nacalai** [obs-ndi/obs-ndi#686]
Hi there. Recently, OBS keeps crashing due to NDI output. We are running latest 5.0.5.0 and latest OBS NDI version.

I have a hard time finding why it exactly crashes. Any help would be greatly appreciated as we rely heavily on NDI.

I run NDI in a much larger scale on other productions and it works flawlessly, using different computers and laptops to output NDI all over the place. While the only output we are doing at this production is sending a playback timer to another screen.

I was hoping Palakis or any other devs would be able to pinpoint the problem.

Crash log (excerpt) : https://pastebin.com/G4RwEkDY
Full regular log: https://obsproject.com/logs/FQFw4Ea8EsUB1wqu

**Comment by tt2468** [comment]
I suggest you use a version of the NDI SDK < 5.0.0, as the current release was not built with it.

**Comment by nacalai** [comment]
> I suggest you use a version of the NDI SDK < 5.0.0, as the current release was not built with it.

We reverted back to version 4, and it still will ocassionally crash, for no apparent reason. We only have one scene output as NDI, and we're not doing anything special before it crashes. Any ideas? Could it be hardware issues? I haven't experienced this with my own machines.

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by nacalai** [comment]
> Is this still an issue using 4.13.0?

I have since forgotten about it and I don't recall any crashes since then
