### ISSUE TITLE
OBS 27.1.3. crashed on Win10 when NDI Source accidentally got unplugged 

### ISSUE THREAD

**Issue by Fred-DTV** [obs-ndi/obs-ndi#713]
Hi everyone,

We hab a very unfortunate case during a show, in which we had a screen capture running over NDI into our OBS from a Macbook with a USB-hub. 
As it happens, the dongle got unplugged and we lost the connection for a short bit.

Sadly when this happend OBS as a whole started to lag and finally freeze completely and we had to kill the process and restart it.

Weirdly there is no crash log, but the regular log shows a lot of audio buffering before the crash
[2021-11-03 18-35-14.txt](https://github.com/Palakis/obs-ndi/files/7877425/2021-11-03.18-35-14.txt)

I hope this helps in improving the plugin.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
Closing due to no response and the release of 4.13.0
