### ISSUE TITLE
ndi output seting too small

### ISSUE THREAD

**Issue by amin007** [obs-ndi/obs-ndi#715]
![ndi for ubuntu studio 20 04 3lts](https://user-images.githubusercontent.com/875314/150614850-40c44719-b4c9-4ac8-9a9e-f494f1fe563c.png)

ndi output seting too small

i use ubuntu studio 20.04.3 LTS

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
Closing due to no response and the release of 4.13.0
