### ISSUE TITLE
OBS NDI makes second PC lose connection

### ISSUE THREAD

**Issue by Yeagorn** [obs-ndi/obs-ndi#718]
Hey! As the title says the second pc loses connection of the internet in like from 2 to 4 minutes after starting the stream. It just loses connection to the internet (both pcs are connected using LAN cable 1gbps)

**Comment by high-solutions** [comment]
in addition i also have a similiar bug with the 5.0.2 sdk. (5.0.10)
if i stream obs program or preview from one macbook and add it as source on another, all NDI streams on the network freeze.

I sadly don't have the time right now to trouble shoot.
I have all sort of bugs from SDK 4.5 upwards on different OSX machines so not sure whats causing it yet

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
Closing due to no response and the release of 4.13.0
