### ISSUE TITLE
Strange use case on OpenSUSE: obs-ndi rewrite does not work with OBS 28 that has been patched to continue using Qt5

### ISSUE THREAD

**Issue by RAMChYLD** [obs-ndi/obs-ndi#778]
##### Issue type
- Bug report

##### Description
Edge use case (probably relevant because I've been told that Fedora and Debian also does this): OBS Project 28 on OpenSuSE, Fedora and Debian were patched to continue using Qt5 instead of Qt6. On these platforms, it is necessary to compile obs-ndi rewrite in Qt5. However, obs-ndi rewrite is misbehaving on these platforms. It does not transmit a picture then causes OBS to segfault on exit. 

##### Steps to reproduce and other useful info
On the transmitting side:
1. Install Qt5 headers (this causes Qt6 headers to uninstall)
2. Use git to pull obs-ndi rewrite.
3. Follow instructions. Cmake will complain about missing Qt6 but will say that it will fall back to Qt5. 
4. Run the make command. Build will be successful.
5. Install obs-ndi into the obs plugin folders and the locale into the share folder.
6. Run OBS.
7. Configure transmission settings as usual. 

On the receiving side:
1. Launch OBS and create a new scene
2. Add the OBS source
3. Select the source from the list.

Expected result: Image transmitted from source.
Received result: Blank image, no sound, OBS on transmitting PC segfaults on exit. 

##### Technical information
- **Operating System:** OpenSuSE Tumbleweed
- **OBS Studio Version:** 28.0.3 
- **obs-ndi Version:** rewrite git81a1612

##### Development Environment
- LibNDI 5.5.1 x64 
- gcc 12.2.1
- OBS 28.0.3

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
Closing since v4.13.0 now requires OBS v30 which requires Qt6 and 64-bit
