### ISSUE TITLE
No 4.10 release listed

### ISSUE THREAD

**Issue by frob** [obs-ndi/obs-ndi#784]
Is there a release for v4.10?

According to https://obsproject.com/forum/resources/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.528/ 
There is a release for 4.10 that is supposed to support OBSv28+

Looking at the latest releases there is no listing for 4.10

![image](https://user-images.githubusercontent.com/316176/199806562-d563ccd3-55a7-4b7c-ac3d-0d7fd2d180e4.png)

I was able to find a dummy tag https://github.com/Palakis/obs-ndi/releases/tag/dummy-tag-4.10.0 but that is all. Is that the release. Lots of negative reviews about this indispensable plugin no longer working.

**Comment by dodgepong** [comment]
Yes, that link is the release. There was simply never an "update" post made for the resource, but the download link on the resource page is still correct.

**Comment by paulpv** [comment]
I'll fix this once 4.11.0 is released...soon...?

**Comment by paulpv** [comment]
Improved in 4.13.0.
This will be an ongoing issue until @Palakis transfers ownership of https://obsproject.com/forum/resources/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.528/ to me.
