### ISSUE TITLE
OBS crashes on launch  with 4 or more streams active on network 

### ISSUE THREAD

**Issue by KadeBehm** [obs-ndi/obs-ndi#801]
##### Issue type

Bug report

##### Description

OBS crashes on launch  with 4 or more streams active on network 

##### Steps to reproduce and other useful info

Have scenes set up with 4 or more NDI streams 
Quit OBS
Launch OBS- Crash 
Shut off one or more so that mess then 4  No crash on launch. 

##### Technical information
- **Operating System:** 
- MacOS 13.0.1
- **OBS Studio Version:** 
- 28.1.2
- **obs-ndi Version:** 
- 4.10.0

##### Development Environment

[2022-11-30 18-00-31.txt](https://github.com/Palakis/obs-ndi/files/10128435/2022-11-30.18-00-31.txt)
[2022-11-30 18-08-53.txt](https://github.com/Palakis/obs-ndi/files/10128436/2022-11-30.18-08-53.txt)
[no crash quit .txt](https://github.com/Palakis/obs-ndi/files/10128437/no.crash.quit.txt)

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
Closing due to no response and the release of 4.13.0
