### ISSUE TITLE
OBS-Websocket 4.9.1-compat and OBS-NDI Version 4.10.0 share the same Uninstall Registry Key location

### ISSUE THREAD

**Issue by MrMase** [obs-ndi/obs-ndi#812]
##### Issue type

- Bug report 

##### Description

OBS-Websocket 4.9.1-compat and OBS-NDI Version 4.10.0 share the same Uninstall Registry Key location as such when one is installed it overwrites the Windows uninstall registry information of the other.

##### Steps to reproduce and other useful info

1. Install Either OBS-NDI Version 4.10.0 or OBS Websocket 4.9.1 Compat
2. Use Nirsoft Uninstall View to get the expected Uninstall Registry location in this case HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall{CD703FE5-1F2C-4837-BD3D-DD840D83C3E3}_is1
3. Install the other program listed in Step 1
4. Refresh the registry entry to notice the DisplayName field and others have been updated.

##### Technical information
- **Operating System:**  Windows 10
- **OBS Studio Version:** 28.1.x
- **obs-ndi Version:** 4.10.0

**Comment by paulpv** [comment]
Linking this to https://github.com/obsproject/obs-websocket/issues/1083

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by MrMase** [comment]
@paulpv unfortunately this is still present in the recent release of 4.11.1, further details of the issue are that the registry key path used by obs-ndi is {CD703FE5-1F2C-4837-BD3D-DD840D83C3E3}_is1.
The uninstall file is "C:\Program Files\obs-studio\unins000.exe"

The details from obs-websocket 4.9.1 compat are also {CD703FE5-1F2C-4837-BD3D-DD840D83C3E3}_is1 with an uninstall file of "C:\Program Files\obs-studio\unins000.exe".

To resolve this issue either of the two projects would need to change their Registry name when compiling the installer with Inno Setup as well as one of them changing their Uninstaller files directory to another locations such as {app}\obs-ndi\unins*.* referenced at https://jrsoftware.org/ishelp/topic_setup_uninstallfilesdir.htm

The installers registry Name field in the installer is apparently changable based on the comments here.
https://github.com/obsproject/obs-plugintemplate/pull/41#issuecomment-1227542028

**Comment by paulpv** [comment]
@MrMase 

> The installers registry Name field in the installer is apparently changable based on the comments here.
> https://github.com/obsproject/obs-plugintemplate/pull/41#issuecomment-1227542028

Yes, but my understanding of that PR (that was created 2022/08/24 and is so close to being done) is that it should also fix this very issue, especially from this comment:
https://github.com/obsproject/obs-plugintemplate/pull/41#issuecomment-1253570029

BUUUUUUUT...that PR may also now be deprecated by https://github.com/obsproject/obs-plugintemplate/pull/76
Specifically this line that configures the AppId:
https://github.com/obsproject/obs-plugintemplate/pull/76/files#diff-7169d4bd4bd24da298da554eddbc679d4972df6c358eb11135825d2cbffc68c0R10

All obs plugins based on obs-plugintemplate have this issue.

We have 3 options:
1. Change obs-ndi's AppId at https://github.com/obs-ndi/obs-ndi/blob/master/cmake/bundle/windows/installer-Windows.iss.in#L10
2. Wait a tiny bit longer for obs-plugintemplate to be patched and then update to that patch (and pick up a few others along the way)
3. Do both

I prefer to just wait for the imminent obs-plugintemplate patch.

**Comment by qwertychouskie** [comment]
https://github.com/obsproject/obs-plugintemplate/pull/76 is merged now, so it'd be good to see the fix pulled here.

**Comment by paulpv** [comment]
Fixed in the upcoming 4.12.0 release by using the latest obs-plugintemplate.
Closing.
