### ISSUE TITLE
[Bug]: Failed to Create Directory on Install

### ISSUE THREAD

**Issue by GodSize** [obs-ndi/obs-ndi#838]
### Operating System Version

Unraid 6.11.5

### OBS Version

Latest

### NDI Tools Version

Latest

### Describe the bug

When I try start OBS in the WebUI, it gives an error message stating "Failed to create directory /root/.config/obs-studio/basic", and the program won't start.

### Steps to reproduce

1. Install unraid docker image as per the forum instructions
2. Open webUI for the docker, and login
3. Try to launch OBS

### Expected behavior

OBS to start

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by Weels92** [comment]
Hello,

Sorry, i'm a noob, i have pushed with portainer "daedilus1/docker-obs-ndi:latest" but I've the same problem than Godsize.
How can i push the delevop branch 4.11 ?

THanks a lot for your help 


(i ve made that stack on portainer )


version: "3.1"
services:
  docker-obs-ndi:
    image: daedilus1/docker-obs-ndi:latest
    ports:
      - 5901:5901
    volumes:
      - /docker/obsndi:/config
    restart: unless-stopped

**Comment by paulpv** [comment]
Closing this due to age and upcoming 4.12.0 release that uses the latest obs-plugintemplate official process of installing a plugin.
