### ISSUE TITLE
[GUIDE] Fixing black screen/"Video Decoder not found" on Linux [tested on Ubuntu 22.10]

### ISSUE THREAD

**Issue by qwertychouskie** [obs-ndi/obs-ndi#842]
To start, you'll need version 5 of the NDI Runtime.  ~~As of this writing, the deb included in the current release is still based on NDI 4, so get an NDI 5 Runtime deb from here: https://github.com/Palakis/obs-ndi/issues/841~~ NDI Runtime is now used as of version `4.11.0-RC`

After installing, test.  If it works, great!  If you get a codec error ("Video Decoder not found"), you need `libavcodec-extra58`.  If you are on Debian 11, Ubuntu 22.04 LTS, or a distro based on it, just run `sudo apt install libavcodec-extra58`.  If you are on a different version of Ubuntu/Debian/etc that doesn't have this version, download these packages:

https://packages.ubuntu.com/jammy/amd64/libavcodec-extra58/download
https://packages.ubuntu.com/jammy/amd64/libavutil56/download
https://packages.ubuntu.com/jammy/amd64/libx264-163/download
https://packages.ubuntu.com/jammy/amd64/libswresample3/download
https://packages.ubuntu.com/jammy/amd64/libdav1d5/download

Then, install them: `sudo apt install /path/to/package1.deb /path/to/package2.deb /path/to/package3.deb /path/to/package4.deb /path/to/package5.deb`

You should now be good to go!

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
@qwertychouskie Can you confirm is any or none of these steps are needed in the 4.11.0-RC build?

Thanks!

**Comment by qwertychouskie** [comment]
You'll probably still need `libavcodec-extra58` and friends.  In fact, I'd recommend making `libavcodec-extra58` a `Recommends` of the `libndi5` package, so at least systems that do ship the package will automatically install it, while systems that don't will still allow installing `libndi5`.

**Comment by paulpv** [comment]
@qwertychouskie Any chance you could test this out with the existing 4.11.0-RC on an Ubuntu 22.10 and let me know?
If not then I can flip my only Ubtunu PC from 22.04.1 to 22.10, but I'd prefer not to yet.

**Comment by paulpv** [comment]
Closing this due to no response and the release of 4.13.0.
