### ISSUE TITLE
[Clean-up]: Update all mention of ndi.newtek.com to ndi.tv + https

### ISSUE THREAD

**Issue by Trouffman** [obs-ndi/obs-ndi#855]
### Describe the bug

There are multiepl mentions of the Newtek site that could (should?) be redirected to the official ndi.tv domain.

This is mostly for : 
http://ndi.newtek.com

While at it, redirecting to https by defualt is a good practice!

To do :
- [ ] replace all mentions of http://ndi.newtek.com to https://ndi.tv

To check:
- Does it create a problem for the Ubuntu packaging ?

**Comment by paulpv** [comment]
> Update on this :
> 
> https://ndi.video/ is the new domain.
> 
> Short link using http://new.tk/ should be replaced by http://ndi.link/
> 
> This is mostly in the Language files to link to the download for the runtime. (under /data/locale) Maybe redirecting to somehting more manageable (aka not hardwcoded) > Redirect to : #831 Or redirect to a clean page where people can always get the latest / most up-to-date version.

I'm workin on a solution to clean this up...

**Comment by paulpv** [comment]
Closing this with the obs-ndi 4.12.0 release and OBS 30 release.
Please comment here if this is still happening and we can reopen.

**Comment by paulpv** [comment]
Need to double check the code...

**Comment by paulpv** [comment]
FYI: https://ndi.tv redirects to https://ndi.video

**Comment by paulpv** [comment]
Fixed in 4.13.0
