### ISSUE TITLE
[Bug]: No NDI filter in OBS-NDI-Plugin version 4.11.1

### ISSUE THREAD

**Issue by saschafoerster** [obs-ndi/obs-ndi#871]
### Operating System Version

MacOS Ventura 13.2.1 (22D68)

### OBS Version

29.0.2 (64bit)

### NDI Tools Version

5.5.3

### Describe the bug

NDI filter does not show up in filter options

### Steps to reproduce

1. Go to scene
2. Add filter
3. No option there

### Expected behavior

1. Go to scene 
2. Add NDI-filter
3. Change options

### Screenshots

<img width="414" alt="Bildschirm­foto 2023-03-26 um 15 17 55" src="https://user-images.githubusercontent.com/1153741/227778259-6e6c3d40-66a8-4447-b60f-298eb60157e5.png">

### Additional context

I am using version 4.11.1 of this plugin.

**Comment by paulpv** [comment]
@saschafoerster Please add an OBS log so that I can confirm the plugin is even loading.

**Comment by paulpv** [comment]
Closing this with the obs-ndi 4.12.0 release and OBS 30 release.
Please comment here if this is still happening and we can reopen.

**Comment by saschafoerster** [comment]
@paulpv Thank you, I will check with the newest release and re-open if needed. But I am pretty sure the new release will make NDI a breathe. Thank you for all the work!
