### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Mmakeb** [obs-ndi/obs-ndi#874]
### Operating System Version

Windows 10

### OBS Version

29.0.2

### NDI Tools Version

4.11.0

### Describe the bug

So i have issue with the audio. I have tried multiply audio captures (mic and desktop) and its working fine without any video capture on gaming pc. Since i add any videocapture (display or gamecapture) it will lose all audio in streaming pc.

**Comment by Trouffman** [comment]
Are you using any of the NDI Source? 
Please provide screenshot of your OBS configuration when /where it is happening.

**Comment by paulpv** [comment]
Closing due to age and no response from request for log.
@Mmakeb feel free to re-open if it is still happening.
