### ISSUE TITLE
(Linux) NDI Video decoder not found

### ISSUE THREAD

**Issue by martialgallorini** [obs-ndi/obs-ndi#879]
Hello,

I am facing a new issue where an NDI source is failing to display with error "Video decoder not found"
I am using different linux distributions all Debian or Debian based.

I guess the issue here is related to the NDI HX codec the camera is delivering (every other Full NDI sources are showing ok) but i have an old Ubuntu setup using older libs which is working find with full NDI or NDI HX. Everything is also working great under MacOs.

Anything changed in the latest libraries ?

Thanks

**Comment by ogmkp** [comment]
On my cameras, that was a weird GOP issue who Advanced SDK don't recognize. Changing this setting solve it.
Manufacturer hasn't released any new firmware yet (no response from the crappy support, like anywhere else suppliers).

**Comment by paulpv** [comment]
@martialgallorini is this still an issue?

**Comment by paulpv** [comment]
Closing this with the obs-ndi 4.12.0 release and OBS 30 release.
Please comment here if this is still happening and we can reopen.

**Comment by johnthq** [comment]
switched over to spiral debian plasma just to find im recieving this problem. went over everything thats been suggested, it definetly appears to be related to the decoding codec for NDI HX, as i can decode the standard NDI screen capture application without getting the "Decoder not Found"

**Comment by martialgallorini** [comment]
Hi,

I had the chance to try again under Ubuntu today with the latests versions of libndi, obs-ndi and OBS Studio and the issue is still showing.

Thanks

**Comment by benbaptist** [comment]
I'm still having this issue with Lubuntu 24.04 and Debian 12, with  OBS Studio 30.0.2.1-3build1, the last version of DistroAV to be called obs-ndi, and installing the latest NDI 6 library with the NDI script. 

Using my macOS laptop with NDI Output in OBS, my Ubuntu machines can pick up that NDI signal just fine and display it, but my actual NDI cameras are failing. They're AVKANS av-e20-n units, and switching between high/low bandwidth does nothing, and changing the codec between h264/h265 on the web interface for the cameras themselves results in no difference.

Same cameras work great under macOS as martial mentioned.

**Comment by martialgallorini** [comment]
Hi,

Any news on this issue ?

**Comment by martialgallorini** [comment]
This issue seems really dependant on which distribution OBS and NDI libraries are installed on.
Same install process but different results on 10 different .deb based distributions including different Debian or ubuntu versions and Debian or Ubuntu based distributions.
Seems like some distributions work slightly differently and causes the issue. Maybe different libraries, paths or symlinks...

**Comment by RayneYoruka** [comment]
These issues sterm from the wrong Ffmpeg version within the system. Its beeing looked up by NDI.

**Comment by martialgallorini** [comment]
thanks a lot for the heads up !
