### ISSUE TITLE
For scene or group use filters, only video without audio. 

### ISSUE THREAD

**Issue by ramyip** [obs-ndi/obs-ndi#881]
### Operating System Version

windows 11

### OBS Version

29.0.2

### NDI Tools Version

5.5.4

### Describe the bug

I need to combine subtitles and video, and use NDI output, but only video can be received, no audio. Audio only works when applying the filter directly to the source.

**Comment by FirstzeroOne** [comment]
#204 is the same error

**Comment by paulpv** [comment]
Yes, looks to be the same as #204.
I re-opened 204 since that should not have been closed and has more of a history.
Closing this issue.
