### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BillyBobJoe19** [obs-ndi/obs-ndi#886]
### Operating System Version

Ventura 13.2.1

### OBS Version

28.1.2

### NDI Tools Version

5.5.3

### Describe the bug

NDI options will not show up when adding a source on OBS 

### Expected behavior

There should be an option NDI. 

### Screenshots

![Screenshot 2023-05-10 at 11 54 33 AM](https://github.com/obs-ndi/obs-ndi/assets/86112736/119e229c-d3e7-416c-b4ec-3c47e063de60)

**Comment by Trouffman** [comment]
Please provide an OBS log : 

1. Close OBS
2. Open OBS
3. Upload Current log file
4. Reply tot his ticket with the link provided

Cheers

**Comment by paulpv** [comment]
Closing due to age and no log provided to investigate
