### ISSUE TITLE
Video Decoder not found

### ISSUE THREAD

**Issue by QuiqueSP** [obs-ndi/obs-ndi#888]
I have installed OBS, NDI-TOOLS and OBS-NDI pluggin. When I plug MEVO into OBS it says "Video decoder not found" Can anyone help me?

**Comment by Trouffman** [comment]
Hi there,
Not much help can be provided unlee you file the required field when opening a bug report.
![image](https://github.com/obs-ndi/obs-ndi/assets/2151317/298512df-a352-4d6b-a844-50b12567f585)

If using NDI to get your MEVO : Make sure to follow the instrauctions at : https://help.mevo.com/hc/en-us/articles/360046292851-Connecting-Mevo-Cameras-to-OBS

**Comment by paulpv** [comment]
@QuiqueSP Please provide more info and we can reopen this
