### ISSUE TITLE
OBS ndi source audio highly delayed

### ISSUE THREAD

**Issue by georgetdawson** [obs-ndi/obs-ndi#894]
I just updated my OBS studio to the latest version and now the audio is all delayed and messed up now. I've had this issue before so maybe I will have to recent back to the older update. But if there is a fix please let me know. Maybe offsetting the audio in advanced audio.

**Comment by magnuscodus** [comment]
Having the same issue. My Encoding machine is displaying no frame loss in the stats dock inside OBS, but the preview image is stuttering non stop and feeling like 10 fps. Changing the sync type, doesnt help. 
PS: I also have the latest updates on both machines.

**Comment by Trouffman** [comment]
Hey folks,
Please provide the fulli nformations to help follow / identify this.
OBS version
OS Version
OBS-NDI version
Runtime Version

Best is always to get a log out of OBS for identifying the issue.

**Comment by paulpv** [comment]
Closing due to age an not even being provided OS info.
