### ISSUE TITLE
[Bug]: No NDI Sources found

### ISSUE THREAD

**Issue by PedroCavaleiro** [obs-ndi/obs-ndi#896]
### Operating System Version

Windows 10

### OBS Version

29.1.2

### NDI Tools Version

5.5.3.20

### Describe the bug

When adding the NDI Source the dropdown is empty even when there are NDI Enabled cameras on the network

### Steps to reproduce

1. Add Sources
2. NDI 5 Source
3. NDI Source Name (pick a source name)

### Expected behavior

The dropdown is populated with NDI Sources found on the network

### Additional context

NDI Studio Monitor is able to "view" these cameras excluding any network issue
Windows Firewall is disabled for testing

**Comment by pantheis** [comment]
Same problem as the person above, here are my details:

**Operating System Version**
Windows 11

**OBS Version**
29.1.3

**NDI Tools Version**
5.5.4.0

**Describe the bug**
When adding the NDI Source the dropdown is empty even when there are NDI Enabled sources on the network

Steps to reproduce
Add Sources
NDI Source
NDI Source Name (pick a source name)
Expected behavior
The dropdown is populated with NDI Sources found on the network

Screenshots
No response

Additional context
NDI Studio Monitor is able to "view" these sources immediately.

**Comment by geman220** [comment]
Exact same issue.  Same information as @pantheis

**Comment by sskorol** [comment]
Same on Ubuntu 20.04 and latest OBS 29.1.3

**Comment by QuantuMonk** [comment]
I am also running into this exact same issue with the same exact tests and symptoms.

Is there a known workaround while we are waiting for a fix?  Does rolling back versions fix it?

**Comment by paulpv** [comment]
I also often struggle sometimes getting NDI to see my NDI sources.
Even NDI Studio Monitor sometimes does not see my Pixel 7 Pro running NDI HX Camera.
It is very frustrating.
All devices are on the same network and subnet.
I also see this happen with obs-ndi I just assume this is a normal occasional frustration.

Does NDI Studio Monitor (from NDI Tools) show any sources?
You could also try using a standalone test tool that I wrote for Windows at:
https://github.com/NightVsKnight/QtNdiMonitorCapture

I will soon release a 4.12.0 version w/ updated NDI lib that might help/avoid this.

You can try out 4.12.0 Release Candidate if you want.

The Pull Request https://github.com/obs-ndi/obs-ndi/pull/919 has been labeled with "Seeking Testers" and the build generates installer packages that you can download try out.

Steps:
1. Browse to https://github.com/obs-ndi/obs-ndi/pull/919
2. Click on "Show all checks"
3. Click on any of the "Details"
4. Click on "Summary"
5. Scroll down and see the "Artifacts"
6. Download the relevant Linux/MacOS/Windows artifact for your platform
7. Windows may complain that the download looks suspicious; you may safely ignore 
8. Unzip the download
9. Run the installer

**Comment by paulpv** [comment]
Closing this with the obs-ndi 4.12.0 release and OBS 30 release.
Please comment here if this is still happening and we can reopen.

**Comment by j4nty** [comment]
I'm having this same issue on flatpak with OBS 32.2.1 (flatpak) and DistroAV 6.2.1 (flatpak). Same symptoms and tests.

**Comment by RayneYoruka** [comment]
> I'm having this same issue on flatpak with OBS 32.2.1 (flatpak) and DistroAV 6.2.1 (flatpak). Same symptoms and tests.

Have you made sure to have Avahi enable and the rest of the flatpak commands needed for OBS as it's instructed on the wiki?
https://github.com/DistroAV/DistroAV/wiki/1.-Installation#flatpak
