### ISSUE TITLE
[Bug]: OBS runs in the background after installing NDI 5.5.4

### ISSUE THREAD

**Issue by jpejoves** [obs-ndi/obs-ndi#900]
### Operating System Version

Windows 11 Home 22H2

### OBS Version

29.1.3

### NDI Tools Version

5.5.4

### Describe the bug

I upgraded to NDI Tools 5.5.4 (from 5.5.3), reinstalled NDI 5.5.3 Runtime, and updated to obs-ndi v.4.11.1, and now OBS opens in the background. I tested removing 3rd-party plugins to make sure it was not conflicting with any other plugins, and still the same. When I uninstall the obs-ndi v.4.11.1, OBS runs fine, but of course without NDI. I am trying to go back to NDI 5.5.3 but link is no longer available. Also tried to install Runtime 5.5.4 but nothing, so I went back to Runtime 5.5.3.

### Steps to reproduce

Upgraded to NDI Tools 5.5.4 (from 5.5.3), installed NDI 5.5.3 Runtime, and obs-ndi v.4.11.1.

**Comment by paulpv** [comment]
Very odd.

I will soon release a 4.12.0 version w/ updated NDI lib that might help/avoid this issue.
This version uses the updated obs-plugintemplate that installs the plugin using OBS' officially recommended practice.
There is no reason that I can think of that obs-ndi should cause OBS to launch itself unsolicited in the background.

You can try out 4.12.0 Release Candidate if you want.

The Pull Request https://github.com/obs-ndi/obs-ndi/pull/919 has been labeled with "Seeking Testers" and the build generates installer packages that you can download try out.

Steps:
1. Browse to https://github.com/obs-ndi/obs-ndi/pull/919
2. Click on "Show all checks"
3. Click on any of the "Details"
4. Click on "Summary"
5. Scroll down and see the "Artifacts"
6. Download the relevant Linux/MacOS/Windows artifact for your platform
7. Windows may complain that the download looks suspicious; you may safely ignore 
8. Unzip the download
9. Run the installer

**Comment by paulpv** [comment]
@jpejoves is this still an issue using 4.13.0?

**Comment by paulpv** [comment]
Closing due to no response
