### ISSUE TITLE
[Feature Request]: Additional Bandwidth Options

### ISSUE THREAD

**Issue by rasamassen** [obs-ndi/obs-ndi#905]
Currently NDIlib_recv_bandwidth_e can only be set to HIGHEST (100) or LOWEST (0) in lib/ndi/Processing.NDI.Recv.h (and in the settings menu when in OBS).

The difference between these 2 settings is massive. On my PTZOptics camera, the resolution of HIGHEST is about 25x wider and 25x taller than the resolution of LOWEST (estimating by how massively the dimensions of the source change in OBS). And there's no middle ground. Nothing between the extremes. I have a camera, that due to factors I'm still testing, is lagging a little bit at HIGHEST. So until I figure out the cause of the lag, I thought I'd reduce bandwidth, but the only other option was LOWEST. At LOWEST, the lag completely disappears, but the resolution is far below what I'd desire.

Feature Request: Add the ability to choose additional bandwidth settings so that there are a range of options.

Additional: Possibly have the bandwidth options be more descriptive than "HIGH/LOW". My PTZOptics camera menu uses options of 2400 bps, 4800 bps, 9600 bps, etc. I know other cameras may be different, and I'm not sure how things work within the NDI Codec, but I'm certain there must be more setting options than "HIGHEST" and "LOWEST".

**Comment by paulpv** [comment]
Gonna have to close this "cantfix".
We are limited to the NDI API here.
From the NDI SDK documentation:
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/8f5b5ceb-30dc-4ccd-b39f-68dbd02b23c4)

The only supported choices seem to be `NDIlib_recv_bandwidth_highest`, `NDIlib_recv_bandwidth_lowest`, or `NDIlib_recv_bandwidth_audio_only`.
Nothing else is even defined in their API:
https://github.com/obs-ndi/obs-ndi/blob/79b2f80b645efebf276f4cd2567775384970e093/lib/ndi/Processing.NDI.Recv.h#L35-L43
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/20b372c2-49ae-4b19-8fcb-6f09c4333b37)

Those are some pretty unusual values, with `audio_only = 10` preventing us from logically using 0...100 as a sliding scale of quality.
If the docs say only use `NDIlib_recv_bandwidth_highest`, `NDIlib_recv_bandwidth_lowest`, or `NDIlib_recv_bandwidth_audio_only`, then we should probably only use those values [unless there is a known reliable working hack that reasonably won't break in the future].
