### ISSUE TITLE
[Bug]: OBS 29.1.3 Crashes with NDI plugin 

### ISSUE THREAD

**Issue by LoGicMoTion** [obs-ndi/obs-ndi#910]
### Operating System Version

Windows 11

### OBS Version

29.1.3

### NDI Tools Version

5.6.0.0

### Describe the bug

When using OBS NDI it instantly crashes and nothing i do can fix this.

### Steps to reproduce

Have OBS NDI plugin running
- OBS crashes

### Expected behavior

it should just not crash

### Additional context

[Crash 2023-09-27 18-40-42.txt](https://github.com/obs-ndi/obs-ndi/files/12775867/Crash.2023-09-27.18-40-42.txt)
[Crash 2023-09-27 19-44-32.txt](https://github.com/obs-ndi/obs-ndi/files/12775868/Crash.2023-09-27.19-44-32.txt)
[Crash 2023-09-30 18-29-59.txt](https://github.com/obs-ndi/obs-ndi/files/12775869/Crash.2023-09-30.18-29-59.txt)
[Crash 2023-09-30 20-00-01.txt](https://github.com/obs-ndi/obs-ndi/files/12775870/Crash.2023-09-30.20-00-01.txt)

**Comment by rkdunlop** [comment]
Same crashes and hangs when exiting. 

[Crash.2023-10-15.18-50-09.txt](https://github.com/obs-ndi/obs-ndi/files/12910979/Crash.2023-10-15.18-50-09.txt)

**Comment by paulpv** [comment]
@LoGicMoTion @rkdunlop

I run Windows 11 on a not yet released version of obs-ndi and do not see this problem.

In 4 of those 5 crash logs the stack is always:
```
Thread 52DC: (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
0000008A995CE738 00007FF961A3D517 00007FF92D7896B0 00007FF92D560000 000000007FFE0384 0000000000000000 shlwapi.dll!Ordinal631+0x6b7
0000008A995CE7A8 00007FF961A36382 00007FF92D560000 0000000000000001 0000023D1B49DC20 00007FF9639385F3 shlwapi.dll!Ordinal239+0x32
0000008A995CE7D8 00007FF92D60C211 0000000000000001 0000000000000000 0000000000000000 00007FF8BEC2FB99 explorerframe.dll!0x7ff92d60c211
0000008A995CE808 00007FF92D603775 00007FF92D560000 0000000000000000 0000000000000001 000000007FFE0385 explorerframe.dll!0x7ff92d603775
0000008A995CE868 00007FF96393868F 0000023D0439A130 00007FF92D560000 0000023D00000000 0000008A8EA6C000 ntdll.dll!0x7ff96393868f
0000008A995CE8D8 00007FF963961096 00000000FFFFFD66 0000023D2DFB00DD 0000008A995CEAE0 0000023D2DFB00DD ntdll.dll!0x7ff963961096
0000008A995CE9E8 00007FF963960C8D 0000000000000156 0000000000000002 0000000000000101 0000664400000000 ntdll.dll!0x7ff963960c8d
0000008A995CEA18 00007FF961AA7FAB 0000008A00400000 0000023D1B8F4A50 0000000000000000 0000000000000000 kernel32.dll!0x7ff961aa7fab
0000008A995CEA48 00007FF8E043726F 00007FF8E01DE76D 00007FF8DF8A164C 00007FF8E04384C8 0000000000007A14 processing.ndi.lib.x64.dll!0x7ff8e043726f
...
```

The 5th is at:
```
Thread 22EC: (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
000000418354F910 00007FFD9B8F3526 0000000000000000 0000000000000000 00000000FFFFFFFA 0000000000000040 ntdll.dll!0x7ffd9b8f3526
000000418354F9F0 00007FFD9B8BFCB4 000001E6C1470000 000001E6C1470000 000001E6AD456520 000001E680679380 ntdll.dll!0x7ffd9b8bfcb4
000000418354FA50 00007FFD9B8BFAE2 000001E680679380 000001E699AEB540 000001E680679380 00007FFD9B8B5BA1 ntdll.dll!0x7ffd9b8bfae2
000000418354FA80 00007FFD0562AADD 0000000200000000 00007FFD9B8B5BA1 000001E6AD4560F0 0000000000013E94 processing.ndi.lib.x64.dll!0x7ffd0562aadd
...
```

obs-ndi is not in any of those callstacks, so the crash may not be **directly** coming from obs-ndi (although it could be how obs-ndi uses the NDI sdk).

It is possible that the crash is directly in NDI's sdk and that they fixed it in a newer runtime and updating obs-ndi to use their latest sdk will stop crashing for you.

I will soon release a 4.12.0 version w/ updated NDI lib that might help/avoid this crash.

You can try out 4.12.0 Release Candidate if you want.

The Pull Request https://github.com/obs-ndi/obs-ndi/pull/919 has been labeled with "Seeking Testers" and the build generates installer packages that you can download try out.

Steps:
1. Browse to https://github.com/obs-ndi/obs-ndi/pull/919
2. Click on "Show all checks"
3. Click on any of the "Details"
4. Click on "Summary"
5. Scroll down and see the "Artifacts"
6. Download the relevant Linux/MacOS/Windows artifact for your platform
7. Windows may complain that the download looks suspicious; you may safely ignore 
8. Unzip the download
9. Run the installer

**Comment by paulpv** [comment]
Closing this with the obs-ndi 4.12.0 release and OBS 30 release.
Please comment here if this is still happening and we can reopen.
