### ISSUE TITLE
[Bug]: Shasum mismatch on libndi install

### ISSUE THREAD

**Issue by Penwy** [obs-ndi/obs-ndi#921]
### Operating System Version

Ubuntu 22.04

### OBS Version

29.1.3

### Describe the bug

Using the script provided to install libndi on linux results in `sha256sum: WARNING: 1 computed checksum did NOT match
`.
The sha256sum of the downloaded file (`7e5c54693d6aee6b6f1d6d49f48d4effd7281abd216d9ff601be2d55af12f7f5`) is indeed different from the one in the script

### Steps to reproduce

1. Use the bash script provided in the release section
2. Notice it fails

### Expected behavior

The script should install libndi as expected.

**Comment by paulpv** [comment]
Fixed in imminent 4.12.0 release
