### ISSUE TITLE
[Bug]: Plugin doesn't do anything

### ISSUE THREAD

**Issue by pc-bastler** [obs-ndi/obs-ndi#922]
### Operating System Version

macOS Sonoma 14.1

### OBS Version

29.1.3

### NDI Tools Version

5.6

### Describe the bug

After installing nothing shows up in OBS studio, there is no "NDI Output" in the Tools Menu, no "NDI Sources" in the "Add Sources Dialog", ...

I checked the installation folder, because there seemed to be an issue with the wrong folder. The plugin installed itself to ~/Library/Application Support/obs-studio/plugins which is, as I read, the folder where it supposed to go into. Unfortunally it seems as OBS does not load it.

I am using a M1-Mac and tried the obs-ndi-4.11.1-macos-arm64-version of the plugin.

### Steps to reproduce

1. Install the plugin
2. Go to Tools menu -> No NDI Output
3. Try to add a Source to a scene -> No NDI Source

### Expected behavior

Seeing NDI in the menus and be able to add sources or use OBS studio itself as a NDI-source for another Computer

**Comment by paulpv** [comment]
Fixed in imminent 4.12.0 release
