### ISSUE TITLE
[Bug]: obs segfault when adding ndi source

### ISSUE THREAD

**Issue by bunder2015** [obs-ndi/obs-ndi#925]
### Operating System Version

Gentoo

### OBS Version

media-video/obs-studio-29.1.3-r2

### NDI Tools Version

[media-video/ndi-sdk-bin-5.6.0](https://github.com/bunder2015/overlay/blob/master/media-video/ndi-sdk-bin/ndi-sdk-bin-5.6.0.ebuild)
[media-video/obs-ndi-4.12.0](https://github.com/bunder2015/overlay/blob/master/media-video/obs-ndi/obs-ndi-4.12.0.ebuild)

### Describe the bug

Trying to make gentoo ebuilds for the next version, I was able to build and install successfully, but when I try to add a ndi source to obs, it segfaults.

### Steps to reproduce

- Open obs
- Add ndi source
- ???
- not profit :smiling_face_with_tear: 

### Expected behavior

Obs adds the ndi source.

### Additional context

I understand that gentoo is not a supported platform, and given the lack of usable information this might not be easy to diagnose.

**Comment by bunder2015** [comment]
[2023-11-13 14-38-52.txt](https://github.com/obs-ndi/obs-ndi/files/13340640/2023-11-13.14-38-52.txt)

**Comment by bunder2015** [comment]
I rebuilt obs and obs-ndi with more debugging and I think I narrowed it down to obs-ndi-source.cpp:1018.  It's trying to create a source called `NDI™ Source` and I guess its having an issue with the TM symbol?

**Comment by paulpv** [comment]
The problem is:
```
14:38:52.741: Qt Version: 5.15.11 (runtime), 5.15.10 (compiled)
```
You are running on Qt5.
This plugin now requires OBS 30 which requires Qt6 which requires 64-bit.
```
