### ISSUE TITLE
Windows won't correctly download or install or claims virus [needs to be signed]

### ISSUE THREAD

**Issue by Jaybonaut** [obs-ndi/obs-ndi#930]
### Operating System Version

Windows 10

### OBS Version

N/A

### NDI Tools Version

N/A

### Describe the bug

Just try to download it to your desktop.  It immediately wipes it and you have to download it to a folder that you tell Windows Defender to avoid scanning.

### Steps to reproduce

See bug description

**Comment by paulpv** [comment]
@Jaybonaut Yeah, I was afraid of that.

I have 4 PCs, two of them literally identical, **but only one of them**, one of the twins, **reports the download as suspicious**.

Grrr.

(FYI: The code is open source for anyone to see that this plugin is not intentionally doing anything bad.)

What I do is go into Windows Virus whatever and add an Exclusion folder:
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/c1d9d349-dda6-40eb-9fdf-e3ff65bd8081)

Chrome still lets me download it with an extra step.
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/06e662e0-e167-4a10-844b-8e77b13b9ad1)
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/80a5ce64-a286-4d8c-8d4d-12282f30cdd8)

I either move the file into that folder, or directly download the file into that folder.
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/1431211b-64bd-42a3-bdbe-b35d23806810)

I can then run it.
Windows may still nag that it is an unknown/untrusted app.
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/eb71e550-da2c-4825-9459-63f966003e7d)

You can click on "More info" and then "Run anyway".
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/6bb2d8b4-70fa-4c10-b7aa-7baaa626d49e)

I am working w/ @Palakis and learning from @exeldro to get this signed.

I will keep this bug open as the main bug on this issue until it is fixed.

Thanks for reporting and reminding me.

**Comment by Jaybonaut** [comment]
Yeah that's what I mentioned in my post:

"you have to download it to a folder that you tell Windows Defender to avoid scanning."

No problem, I just noticed it wasn't mentioned and thought someone should say something in case.  I appreciate all your hard work everyone.

**Comment by paulpv** [comment]
Interesting comment related to signing:
https://github.com/sigstore/fulcio/issues/250#issuecomment-1289258324
Here are your options:
> 1. You don't sign your code. You release MyApp-v1.exe. People get smart screen warnings for a while until the reputation on that file increases. You release MyApp-v2.exe. People get warnings again until MyApp-v2.exe builds up enough reputation.
> 2. You sign your code with an OV certificate. You release MyApp-v1.exe. People get smart screen warnings for a while until the reputation on that certificate increases. You release MyApp-v2.exe. People don't get warnings because the certificate already has a good reputation. Eventually your certificate expires and it comes time to release MyApp-v47.exe. You renew your certificate, but people still get warnings until the new one builds up reputation.
> 3. You sign your code with an EV certificate. People never get warnings.

@Palakis and I looked a bit into sigstore, but per https://github.com/sigstore/fulcio/issues/250 it does not stop Windows from warning:
Per https://github.com/sigstore/fulcio/issues/250#issuecomment-983595336
> you would still have the same UX of having to click through a warning.
That seems pretty useless then for endusers.
sigstore sounds great for a plethora of other signing purposes...just not for end-user installs...which is our use-case. :/

**Comment by paulpv** [comment]
This problem seems to have two layers:
1. The browser complains about the file before it is downloaded:
  Does the browser itself test the signature? How does it do this? Is it different for each browser?
2. Windows complains about the file after it is downloaded:
  How to accelerate the Smart Screen allowance?
  https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/
  https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/#submit-files-to-microsoft-defender-smartscreen-for-review

**Comment by Jaybonaut** [comment]
Yeah I've dealt with unsigned warnings before, this is beyond that:  Windows will nuke it before you can even double click it claiming it is a threat.  Unless you put 4.13 in an unscanned folder, I can't even get the chance to try to open it.

**Comment by paulpv** [comment]
FYI, I am submitting the following to:
https://www.microsoft.com/en-us/wdsi/filesubmission/?persona=SoftwareDeveloper
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/4f2b4f37-cb2c-48a1-b372-5b81dbfc05ae)

**Comment by paulpv** [comment]
For personal reference, I can track the submission, and future submissions, at:
https://www.microsoft.com/en-us/wdsi/submissionhistory

**Comment by paulpv** [comment]
w00t!
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/9b743318-6abb-443f-9272-365868fb20c8)

**Comment by paulpv** [comment]
w00t! No warning downloading...
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/fad9fa7a-ca55-40eb-8165-fe422f80ecd9)
...OR EVEN INSTALLING!

**Comment by Jaybonaut** [comment]
Congrats, I can confirm
