### ISSUE TITLE
[Bug]: Installation on MacOS fails with Symbol not found: _qt_version_tag_6_5

### ISSUE THREAD

**Issue by pixtur** [obs-ndi/obs-ndi#933]
### Operating System Version

OBS v29.1.1

### OBS Version

v29.1.1 

### NDI Tools Version

5?

### Describe the bug

I'm trying to figure out how to install obs-NDI on Apple Silicon. My experience wasn't really successful so far.

OBS v29.1.1 / MaxOS 13.2.1 (22D68) / Apple M1 Pro
 
- I read and followed the instructions in README.md
- downloaded latest release from https://github.com/obs-ndi/obs-ndi/releases/download/4.13.0/obs-ndi-4.13.0-macos-universal.pkg
- run the installer without warnings
- downloaded and installed http://ndi.link/NDIRedistV5Apple as linked in the README
 
I'm not sure what to expect now (it would be great if the README would link a howto, or tutorial on anything else that would indicate on how to verify a successful installation) 
- No error messages
- No new inputs in OBS->Add Source
- No files related to NDI: in /Applications/OBS.app/Contents/PlugIns
- File is listed in  /Users/me/Library/Application\ Support/obs-studio/plugins/obs-ndi.plugin

I didn't find an option to list the (successfully) installed OBS plugins

The [logfile](https://obsproject.com/logs/a8wvwDDOEoFzH38Z) lists the following lines which I'm trying to understand:

```
22:01:32.802: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
22:01:32.803: os_dlopen(/Users/me/Library/Application Support/obs-studio/plugins/obs-ndi.plugin/Contents/MacOS/obs-ndi->/Users/me/Library/Application Support/obs-studio/plugins/obs-ndi.plugin/Contents/MacOS/obs-ndi): dlopen(/Users/me/Library/Application Support/obs-studio/plugins/obs-ndi.plugin/Contents/MacOS/obs-ndi, 0x0101): Symbol not found: _qt_version_tag_6_5
22:01:32.803:   Referenced from: <DE4B9876-D767-34BD-BBCA-CFB75F3E9BF8> /Users/me/Library/Application Support/obs-studio/plugins/obs-ndi.plugin/Contents/MacOS/obs-ndi
22:01:32.803:   Expected in:     <EA2F3100-9BC7-3459-845C-E424249B9015> /Applications/OBS.app/Contents/Frameworks/QtCore.framework/Versions/A/QtCore
22:01:32.803: 
22:01:32.803: Module '/Users/me/Library/Application Support/obs-studio/plugins/obs-ndi.plugin/Contents/MacOS/obs-ndi' not loaded
22:01:32.803: ---------------------------------
22:01:32.803:   Loaded Modules:
22:01:32.803:     vlc-video
22:01:32.803:     text-freetype2
22:01:32.803:     rtmp-services
22:01:32.803:     obs-x264
22:01:32.803:     obs-websocket
22:01:32.803:     obs-vst
22:01:32.803:     obs-transitions
22:01:32.803:     obs-outputs
22:01:32.803:     obs-filters
22:01:32.803:     obs-ffmpeg
22:01:32.803:     obs-browser
22:01:32.803:     mac-virtualcam
22:01:32.803:     mac-videotoolbox
22:01:32.803:     mac-syphon
22:01:32.803:     mac-capture
22:01:32.803:     mac-avcapture
22:01:32.803:     image-source
22:01:32.803:     frontend-tools
22:01:32.803:     decklink-output-ui
22:01:32.803:     decklink-captions
22:01:32.803:     coreaudio-encoder
22:01:32.803: ---------------------------------
```

**Comment by paulpv** [comment]
https://github.com/obs-ndi/obs-ndi#requirements
> Requirements
> OBS >= 30.0.0 (Qt6 & x64)

You are running OBS 29.1.1.
obs-ndi will not run on OBS 29.1.1
obs-ndi requires OBS >= 30.0.0.
