### ISSUE TITLE
[Bug]: No Source in OBS

### ISSUE THREAD

**Issue by pocketninja112** [obs-ndi/obs-ndi#952]
### Operating System Version

MacOS Sonoma 14.2.1

### OBS Version

30.0.2

### NDI Tools Version

4.9.0

### Describe the bug

Installed the package, no source shows up for NDI, likely due to Sonoma update? 

### Steps to reproduce

1. Install plugin
2.  Open OBS
3. Select + new source

### Expected behavior

When adding a new source, NDI should show up as a source option

**Comment by paulpv** [comment]
@pocketninja112 Please attach or link an OBS log

**Comment by pocketninja112** [comment]
I'm not going to lie, I do not know how to do an OBS log of something that does not exist. I can attach a screen recording of it not showing up, but I don't know what good that will do as it's just proof of what I said?

**Comment by paulpv** [comment]
An OBS log will show us if obs-ndi is successfully initializing or reporting any problems.

**Comment by pocketninja112** [comment]
[2024-01-04 10-04-58.txt](https://github.com/obs-ndi/obs-ndi/files/13831857/2024-01-04.10-04-58.txt)

I don't think it is initializing because it's not even showing up as a source. Here's the log file, there's nothing about it at all

**Comment by paulpv** [comment]
Looks like OBS doesn't even see the obs-ndi plugin.
Please `ls -la /Library/Application Support/obs-studio/plugins` and `ls -la ~/Library/Application Support/obs-studio/plugins`

**Comment by olliedavo** [comment]
i can second this, im having the same issue, ill let you know if i find a fix

**Comment by paulpv** [comment]
@olliedavo Sonoma?
I literally just updated my Ventura to Sonoma yesterday and have not yet tested installing or running obs-ndi on it.

**Comment by paulpv** [comment]
@olliedavo Can you `ls -la /Library/Application Support/obs-studio/plugins` and `ls -la ~/Library/Application Support/obs-studio/plugins`?

**Comment by paulpv** [comment]
FYI, on a MacOS that was updated from Ventura to Sonoma, OBS does load the obs-ndi plugin and shows NDI sources just fine.

I am now mostly just curious about any installation problems.

**Comment by olliedavo** [comment]
> ls -la /Library/Application Support/obs-studio/plugins

when i try this command in terminal nothing happens, am i doing something wrong?

**Comment by pocketninja112** [comment]
It shows up in my plugins in the app support folder in Library, so not sure why the install wouldn't work.

**Comment by pocketninja112** [comment]
Also, "no such file or directory" when input into terminal

**Comment by paulpv** [comment]
Sorry, the whitespace path needs to be escaped:

```
ls -la /Library/Application\ Support/obs-studio/plugins
ls -la ~/Library/Application\ Support/obs-studio/plugins
```

**Comment by wind34012614** [comment]
> Sorry, the whitespace path needs to be escaped:
> 
> 
> 
> ```
> 
> ls -la /Library/Application\ Support/obs-studio/plugins
> 
> ls -la ~/Library/Application\ Support/obs-studio/plugins
> 
> ```

No such file or directory

**Comment by zonky2** [comment]
same problem at

Operating System Version
Debian

OBS Version
30.0.2 (64bit)

NDI Tools Version
4.13.0

**Comment by Trouffman** [comment]
Closing this as this is usually coming from an installation error.
Please do a full re-install and follow the installation step at : https://github.com/obs-ndi/obs-ndi/wiki/1.-Installation
