### ISSUE TITLE
Is z flip 4 not compatible with obs studio?

### ISSUE THREAD

**Issue by kangs07** [obs-ndi/obs-ndi#958]
### Operating System Version

Windows 11

### OBS Version

30

### Describe the bug

Tried all the tutorials on youtube about black screen on video capture device. Got no problem when playing on my pc with obs. I just cant get the mobile set up right.

**Comment by paulpv** [comment]
We need more info.

I assume the "z flip" is your mobile device?

What can you not get set up right?

Is it just not showing up in OBS Studio?

Is it showing up in NDI Studio Monitor?

**Comment by kangs07** [comment]
> We need more info.
> 
> I assume the "z flip" is your mobile device?
>  yes sir my phone is z flip 4
> What can you not get set up right?
> i think i did everything correctly, phone to usb c to hdmi in (card capture), hdmi out and usb cord to laptop. I also did run obs as administrator, also high performance in graphic settings.
> Is it just not showing up in OBS Studio?
> yes bro all i get is black screen
> Is it showing up in NDI Studio Monitor?

**Comment by paulpv** [comment]
Where is NDI in your setup?

**Comment by kangs07** [comment]
> Where is NDI in your setup?

I dont know what is NDI bro sorry haha maybe thats what im lacking

**Comment by kangs07** [comment]
https://youtu.be/JfyQ_KdN6Ow?feature=shared this was my setup. For now ill try searching NDI maybe thats what im missing

**Comment by paulpv** [comment]
Your issue is not an obs-ndi issue.
It is a general obs capture device issue.
We can't really help you here.
Sorry.
Closing.
