### ISSUE TITLE
[Bug]: Lost audio_output_close for dummy_audio_queue

### ISSUE THREAD

**Issue by walker-WSH** [obs-ndi/obs-ndi#963]
### Operating System Version

windows

### OBS Version

30

### OBS Installation Method

exe

### OBS-NDI Version

latest

### OBS-NDI Installation Method

exe

### OBS Log [URL]

none

### NDI Version

latest

### Describe the bug

`audio_output_open` is called for `dummy_audio_queue` while no `audio_output_close.`
This makes `audio_thread` of NDI is still running after `obs_shutdown`.

It seems you forget call `audio_output_close`. 
please confirm it, thanks~

**Comment by ogmkp** [comment]
On linux, I can say that with the sound offset problem on monitoring, I still hear the sound of NDI for 1 to 3 sec while OBS freezes waiting to close.
OBS is waiting for the NDI thread to finish its sound buffer.
#667

**Comment by paulpv** [comment]
This should be fixed in https://github.com/obs-ndi/obs-ndi/releases/tag/4.13.2
