### ISSUE TITLE
Download Failed: The server name or address could not be resolved [Bug]: 

### ISSUE THREAD

**Issue by TheTrekkie** [obs-ndi/obs-ndi#967]
### Operating System Version

Not sure

### OBS Version

27.2.4

### OBS Installation Method

Link

### OBS-NDI Version

4.9.0

### OBS-NDI Installation Method

Link

### NDI Version

4.9.0

### Describe the bug

Not letting me install NDI so I can see it in OBS

### Screenshots

![Capture](https://github.com/obs-ndi/obs-ndi/assets/157420573/56af3a24-d822-4491-ac21-ab366df7d06a)

### Additional context

I have to download these specific version for work and I am not sure what I did wrong. I followed the steps that I had from my work and it is not working.

**Comment by TheTrekkie** [comment]
[HBCD MEVO Camera Guide-Final -V2.pdf](https://github.com/obs-ndi/obs-ndi/files/14015318/HBCD.MEVO.Camera.Guide-Final.-V2.pdf)


This is the guide that I was given

**Comment by paulpv** [comment]
This project only supports its most recent version(s).

That doc/product is talking about OBS 27 and obs-ndi 4.9.0.
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/f01d5696-46cf-451f-9c03-3aaa0918355b)

We do not support either of those versions any more.
Even if we did, the fix would be to update to the latest version.

Update to the latest version of OBS and obs-ndi.

Closing
