### ISSUE TITLE
4.13.1 on the front page problem

### ISSUE THREAD

**Issue by Jaybonaut** [obs-ndi/obs-ndi#982]
### Operating System Version

Does not matter

### CPU

N/A

### GPU

N/A

### NDI Devices

N/A

### OBS Version

Does not apply

### OBS Installation Method

Does not apply

### OBS-NDI Version

Does not apply

### OBS-NDI Installation Method

Does not apply

### [Extra] Installation Steps

4.13.1 for all 3 operating systems on the front page lead to a 404 error.  4.13.0 exists of course.

### NDI Version

4.13.1

### Describe the bug

4.13.1 for all 3 operating systems on the front page lead to a 404 error.  4.13.0 exists of course.

### Steps to reproduce the problem

Go to [here](https://github.com/obs-ndi/obs-ndi) and it lists 4.13.1 for all operating systems but they all link to a page that does not exist.

**Comment by RayneYoruka** [comment]
https://github.com/obs-ndi/obs-ndi/actions/runs/7905580374

**Comment by Jaybonaut** [comment]
> https://github.com/obs-ndi/obs-ndi/actions/runs/7905580374

Defender goes nuts on that download.  I just wanted to bring attention to the front page issue.

**Comment by paulpv** [comment]
@Jaybonaut Fixed now?

**Comment by Jaybonaut** [comment]
> @Jaybonaut Fixed now?

The one in the link does, but the one on the front page is messed up somehow (Windows in this case.)  It places a .part on the desktop (where I download it) and then states 'This app can not run on your pc.'  When I try to launch the executable.  The one from the link shows up as a zip archive and works just fine.

**Comment by paulpv** [comment]
The Windows download problem is related to the post-release steps that have to be taken and are documented here:
https://github.com/obs-ndi/obs-ndi/wiki/3.-Development#windows-1

What browser are you using?

Unfortunately, Chrome Google Safe Browsing needs some time after release to detect that this file is not malicious.

There appears to be no way to submit to Google an exe url for them to expediate scanning and allowing.

A user can "Download suspicious file" anyway and eventually Google Safe Browsing will approve the file:
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/d3e649c0-e276-46ec-9fa6-2fc1b81afc47)

It is a shitty system, but it is what it is.

If we bought a signing certificate then we could sign our app during the build and this should pass through these types of checks.

**Comment by paulpv** [comment]
Thanks for catching this.
Much of this was a result of the 4.13.1 release being broken due to an Apple agreement needing to be agreed to.
The rest is known limitation when working with unsigned release files.
Closing this resolved (since I did take some action to update the wiki docs)

**Comment by paulpv** [comment]
Firefox probably has its own "suspicious file" verification process, as well as Safari, Edge, Brave, etc.
It will either fix itself over time as people proceed anyway, or I would have to submit the file to each individual browser verification process... which does not sound scalable or reasonable or even normal.

I don't know how other OBS plugins release, or if they have the same problem.
OBS-NDI is based on the official obs-plugintemplate code, so I would not expect this to be a big problem. :/

**Comment by Jaybonaut** [comment]
> Firefox probably has its own "suspicious file" verification process, as well as Safari, Edge, Brave, etc. It will either fix itself over time as people proceed anyway, or I would have to submit the file to each individual browser verification process... which does not sound scalable or reasonable or even normal.
> 
> I don't know how other OBS plugins release, or if they have the same problem. OBS-NDI is based on the official obs-plugintemplate code, so I would not expect this to be a big problem. :/

I suppose just linking the zipped version could help fix the issue.  For anyone having problems with the Windows version on the front page, try this instead:  [Link to Windows zip](https://github.com/obs-ndi/obs-ndi/actions/runs/7905580374/artifacts/1257625200)

**Comment by paulpv** [comment]
I made a Pull Request change to obs-plugintemplate to produce the Windows zip file in the release.
I thought I made this change in our repo first.
I'll reopen this ticket and confirm.

**Comment by Jaybonaut** [comment]
This seems to have been fixed.  Thanks!
