### ISSUE TITLE
NDI Tools v6 Compatible?

### ISSUE THREAD

**Issue by dleffler** [obs-ndi/obs-ndi#999]
I see NDI Tools version 6 was just released...is this plugin compatible?

**Comment by Trouffman** [comment]
The NDI Runtime for 6 can be used, most of the time, unless you are on a brand new macOS.

There is a PR in the pipe that add official support across all OS for NDI v6 (not the new features but at least compatiblity)

Also : no new feature for NDI v6 are currently supported (10bit color / HDR etc)

**Comment by youcangetme** [comment]
The plugin demands NDI 5 Runtime on Windows 11 PRO. I had to reinstall it to continue using OBS.

**Comment by Trouffman** [comment]
> The plugin demands NDI 5 Runtime on Windows 11 PRO. I had to reinstall it to continue using OBS.

If you could provide the OBS log file for this it will be very useful.

**Comment by youcangetme** [comment]
I goofed. I reverted without trying to do further trouble shooting. I have another PC and I will try to see if I can replicate it there and get a log. It was doing the same thing.

**Comment by youcangetme** [comment]
[2024-04-12 19-45-12.txt](https://github.com/obs-ndi/obs-ndi/files/14964549/2024-04-12.19-45-12.txt)
Well, you are in luck!
Not much in the logs. I did reinstall NDI 5 and its still complaining about not finding it.

**Comment by Trouffman** [comment]
It looks for the lib at :

C:/Program Files/NDI/NDI 5 Tools/Runtime/Processing.NDI.Lib.x64.dll

Please screenshot the content of this folder :
C:/Program Files/NDI/NDI 5 Tools/Runtime/

Also, please confirm how you installed NDI Tool and did you install the runtime ?

**Comment by dleffler** [comment]
My guess is the NDI v6 tools are installed in /NDI 6 Tools/ and NOT /NDI 5 Tools/

**Comment by Trouffman** [comment]
@dleffler that is correct but it should not be a problem if you I stall ether NDI Runtime  as this will set the proper Environment variables on windows :D

**Comment by Trouffman** [comment]
I did a couple more test. (win 11 home)
THis will boil down to your environment variables and if you had the runtime installed before or not.

### Most liekly source of the issue : 
Seems there is a problem when you insatll NDI Tools, then NDI runtime, then remove runtime, the system variable do not rever back to the one in the NDI Tools. to fix, simply remove/reinstall the NDI Tools.


### How to fix : 
- Remove NDI tools and NDI Runtime and NDI SDK (all version)
- Wipe the folder C:\Program Files\NDI < might be clean after uninstall but better be sure.
- Reinstall NDI Tools (v6)

Optional : Install NDI Runtime (v6 is fine too)

(on WIn10/11 for NDI v6 you can do via command line : winget install NDI.NDITools // winget install NDI.NDIRuntime) 

- Reboot.

- Open the environment variable dialog. (start menau > searhc > Environment variable)
You should have the System variables :
NDI_RUNTIME_DIR_V5 >> directing to either the NDI tools or the NDI Runtime folder. > this is waht the plugin use to find the required files.

Example when the runtime are installed : 
![image](https://github.com/obs-ndi/obs-ndi/assets/2151317/b5c02ad4-4854-42ec-a3ee-5f600bf709cd)

Example with only the ndi tools are installed :
![image](https://github.com/obs-ndi/obs-ndi/assets/2151317/839781c0-5489-4d94-81c2-d7a4e4c97439)

### Conclusion 
This plugin work with NDI 6 Tools / NDI 6 Runtime installed /test on the following :
On WIn 10 /11 home with OBS 30.1.2 

If you have the issue : library not found > check the env. variable and that the ndi tools / ndi runtime are installed. 

Side note : I tested on linux ubuntu 22.04.01 as well.
On Mac it is workign as well BUT there is a bug in the NDI Runtime package from NDI and you need to run sudo chmod 755 /usr/local/lib after you install the package. (only if this is a first time install, if you had v5 in there, that should be no problem as the folder was already created.)

**Comment by Trouffman** [comment]
The workaround is also documented here :
https://github.com/obs-ndi/obs-ndi/discussions/1002

This might be useful over time as this was also a problem at some point on the old v4

**Comment by youcangetme** [comment]
Sorry, I never updated my findings :( 

Turns out you need to reboot after installing the update to v6.

**Comment by gsudhan** [comment]
I have downgraded from ndi tools 6 to 5 but there is something in my system that is pointing to 6 and giving the error 
Cannot find "Processing.NDI.Lib.x64.dll" from the NDI 6 Runtime Directory. 
any idea where to find this pointer?

**Comment by RayneYoruka** [comment]
> I have downgraded from ndi tools 6 to 5 but there is something in my system that is pointing to 6 and giving the error Cannot find "Processing.NDI.Lib.x64.dll" from the NDI 6 Runtime Directory. any idea where to find this pointer?

Enviornment variables.

![Image](https://github.com/user-attachments/assets/a12cfd02-c801-41a9-ad00-22a565f0df01)

**Comment by Trouffman** [comment]
if you have issue open a new ticket with the required info. 

most likely you have not installed NDI Runtime.
https://github.com/DistroAV/DistroAV/wiki/1.-Installation#install-required-ndi-runtime
